'use strict';
// No game process, DOM or user files are required by these state-machine regressions.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const timers=new Map();let timerId=0;
const sandbox={window:{},setTimeout:fn=>{timers.set(++timerId,fn);return timerId;},clearTimeout:id=>timers.delete(id)};
vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../../standalone/scene.js'),'utf8'),sandbox);
const Scene=sandbox.window.StudentAgeScene,json=v=>JSON.parse(JSON.stringify(v));
const doc={persons:{0:{id:0,name:'主角'},3:{id:3,name:'小明'},4:{id:4,name:'小红'},5:{id:5,name:'老师'}},backgrounds:{100:{id:100,url:'bg/room'}},cgs:{1:{id:1,urls:['cg/test']}},faces:{},events:{1:{id:1,talkId:[10]},2:{id:2,talkId:[40]}},options:{100:{id:100,content:'留下',talkId:[30]},101:{id:101,content:'下一事件',nextEvtId:2}},talks:{
  10:{id:10,bg:100,roleIds:[3],roles:[[3,1002,1,1,0],[4,1002,1,2,0]],nextTalk:[20]},
  20:{id:20,roleIds:[3],roles:[[3,3004,200,.2,0,.8],[3,3008,50,.4,0],[3,3000,10]],nextTalk:[25]},
  25:{id:25,roleIds:[4],roles:[],option:[100,101]},
  30:{id:30,roleIds:[3],roles:[[4,2002,0]],screenEffect:[4015,1]},
  40:{id:40,roleIds:[0],roles:[]}
},branchFolders:{'25:101':{parentTalkId:25,optionId:101,talkIds:[],continuation:{kind:'event',eventId:2}}}};
let checks=0;function test(name,fn){fn();checks++;console.log('PASS '+name);}
test('actual route inherits background, cast, relative X/Y and expression',()=>{const original=JSON.stringify(doc),s=Scene.reconstruct(doc,20,{roots:[10]});assert.equal(s.background,100);assert.equal(s.roles[3].x,-600);assert.equal(s.roles[3].y,0);assert.equal(s.roles[3].nativeTargetY,50);assert.equal(s.roles[3].face,10);assert.equal(s.roles[4].x,800);assert.equal(s.roles[4].visible,true);assert.equal(JSON.stringify(doc),original);assert.equal(s.motions.find(m=>m.code===3004).duration,.8);assert.equal(s.motions.find(m=>m.code===3008).delay,.4);});
test('each dialogue keeps its own motion origin; inherited poses never repeat movement',()=>{const s=Scene.reconstruct(doc,20,{roots:[10]});assert.equal(s.motionStarts[3].x,-800);assert.equal(s.motionStarts[3].y,0);assert.equal(s.motionStarts[3].face,0);const inherited=Scene.apply(doc,s,doc.talks[25]);assert.equal(inherited.motionStarts[3].x,-600);assert.equal(inherited.motionStarts[3].y,0);assert.equal(inherited.roles[3].face,10);assert.equal(inherited.roles[3].x,-600);assert.equal(inherited.motions.length,0);assert.equal(s.motionStarts[3].x,-800);const entry=Scene.apply(doc,Scene.blank(),{id:99,roles:[[3,1002,1,2],[3,3004,80,0,0,-1]]});assert.equal(entry.motionStarts[3].x,800);assert.equal(entry.motionStarts[3].visible,false);assert.equal(entry.roles[3].x,880);assert.equal(entry.motions.find(m=>m.code===3004).duration,.4);});
test('same-axis repeated entry preserves existing movement',()=>{let s=Scene.reconstruct(doc,20,{roots:[10]});s=Scene.apply(doc,s,{id:99,roles:[[3,1002,1,1,0]]});assert.equal(s.roles[3].x,-600);assert.equal(s.roles[3].y,50);});
test('initial background supplies role-specific clothes, inherited until explicitly changed',()=>{const d=json(doc);d.backgrounds[100].cloth=[1,2,3];d.backgrounds[200]={id:200,cloth:[8,9,10]};let s=Scene.apply(d,Scene.blank(),{id:1,roleIds:[-1]});s=Scene.apply(d,s,{id:2,bg:100,roles:[[3,1002,1,1],[1,1002,1,2],[5,1002,1,3]]});assert.equal(s.roles[3].cloth,1);assert.equal(s.roles[1].cloth,2);assert.equal(s.roles[5].cloth,3);s=Scene.apply(d,s,{id:3,bg:200,roles:[[4,1002,1,2],[3,3006,6]]});assert.equal(s.roles[4].cloth,1);assert.equal(s.roles[3].cloth,6);});
test('entry before movement and slot allocation/reuse match game rules',()=>{let s=Scene.apply(doc,Scene.blank(),{id:99,roles:[[3,3004,80],[3,1002,1,2],[4,1002,1,2],[5,1002,1,2]]});assert.equal(s.roles[3].x,880);assert.equal(s.roles[4].x,500);assert.equal(s.roles[5].x,1100);s=Scene.apply(doc,s,{id:100,roles:[[4,2002],[0,1002,1,2]]});assert.equal(s.roles[0].x,500);});
test('implicit speakers enter opposite prior speaker; protagonist zero is supported',()=>{let s=Scene.apply(doc,Scene.blank(),{id:1,roleIds:[3],roles:[]});assert.equal(s.roles[3].x,-800);s=Scene.apply(doc,s,{id:2,roleIds:[0]});assert.equal(s.roles[0].x,800);s=Scene.apply(doc,s,{id:3,roleIds:[-1]});assert.equal(s.speaker,'旁白');assert(!s.roles[-1]);});
test('new non-entry action brings character in but exit of unknown actor does not',()=>{let s=Scene.apply(doc,Scene.blank(),{id:1,roles:[[4,2002],[3,3000,4]]});assert(!s.roles[4]);assert(s.roles[3].visible);assert.equal(s.roles[3].face,4);s=Scene.apply(doc,s,{id:2,roles:[[3,2002]]});s=Scene.apply(doc,s,{id:3,roleIds:[3],roles:[]});assert.equal(s.roles[3].visible,true);assert.equal(s.roles[3].face,0);});
test('flip, shadow, outfit and native emphasis scale remain inherited',()=>{let s=Scene.apply(doc,Scene.blank(),{id:1,roles:[[3,1003,-1,1],[3,3003,1.8],[3,3006,2],[3,3005],[3,3012]]});assert.equal(s.roles[3].y,-850);assert.equal(s.roles[3].scale,2.2);assert.equal(s.roles[3].cloth,2);assert(s.roles[3].flip);assert(s.roles[3].shadow);s=Scene.apply(doc,s,{id:2,roles:[[3,3007],[3,3013],[3,3003,0]]});assert.equal(s.roles[3].scale,0);assert(!s.roles[3].flip);assert(!s.roles[3].shadow);});
test('CG and exit inherit through explicit option route',()=>{const s=Scene.reconstruct(doc,30,{roots:[10]});assert.equal(s.cg,1);assert.equal(s.background,100);assert.equal(s.roles[4].visible,false);assert.equal(s.trace.join(','),'10,20,25,30');});
test('event transition resets inherited scene',()=>{const s=Scene.reconstruct(doc,40,{roots:[10]});assert.equal(s.background,0);assert(!s.roles[3]);assert(s.roles[0].visible);});
test('unsupported effects are preserved and unavailable routes never silently play',()=>{const d=json(doc);d.talks[20].roles.push([3,9876,8]);d.talks[20].check=[[1,1]];d.talks[20].nextTalk2=[999];const s=Scene.reconstruct(d,20,{roots:[10]});assert(s.warnings.some(x=>x.includes('9876')));assert(s.routeChoices.every(x=>x.conditional));assert(s.routeChoices.find(x=>x.id===999).available===false);assert.deepEqual(d.talks[20].roles.at(-1),[3,9876,8]);});
test('route search handles cycles and unlinked dialogues',()=>{const d=json(doc);d.talks[30].nextTalk=[10];assert.deepEqual(json(Scene.pathTo(d,30,[10]).path),[10,20,25,30]);d.talks[88]={id:88,content:'孤立句'};assert.equal(Scene.reconstruct(d,88,{roots:[10]}).warnings.length,1);});
test('draft dialogue chain inherits without an event entry and ignores unlinked neighbours',()=>{const d=json(doc);d.events={};d.talks[15]={id:15,bg:200,roles:[[5,1002,1,1]]};const s=Scene.reconstruct(d,20);assert.deepEqual(json(s.trace),[10,20]);assert.equal(s.background,100);assert.equal(s.roles[3].face,10);assert.equal(s.roles[3].x,-600);assert.equal(s.roles[3].y,0);assert.equal(s.roles[3].nativeTargetY,50);assert.equal(s.roles[4].visible,true);assert(!s.roles[5]);assert.equal(Scene.pathTo(d,20,[]).inferred,true);assert.equal(Scene.reconstruct(d,25).roles[3].x,-600);});
test('unassigned draft chain works beside another event, with explicit entry taking priority',()=>{const d=json(doc);d.events={2:d.events[2]};let s=Scene.reconstruct(d,20);assert.deepEqual(json(s.trace),[10,20]);assert.equal(s.background,100);d.events[1]={id:1,talkId:[20]};s=Scene.reconstruct(d,20);assert.deepEqual(json(s.trace),[20]);assert.equal(s.background,0);assert(!s.roles[4]);assert(!Scene.pathTo(d,20,[20]).inferred);});
test('draft branch uses connected choice path and entryless cycles terminate safely',()=>{const d=json(doc);d.events={};const s=Scene.reconstruct(d,30);assert.deepEqual(json(s.trace),[10,20,25,30]);assert.equal(s.background,100);assert.equal(s.roles[4].visible,false);d.talks[30].nextTalk=[10];const cycle=Scene.pathTo(d,20,[]);assert.equal(cycle.found,false);assert.deepEqual(json(cycle.path),[20]);});
test('player chooses actual branches, backtracks, resets, and pauses timers',()=>{let selections=[],choices=[];const p=new Scene.Player({getDoc:()=>doc,getContext:()=>({roots:[10]}),onRender:()=>{},onSelect:id=>selections.push(id),onChoices:c=>choices=c});p.select(10);p.next();assert.equal(p.scene.talkId,20);p.next();assert.equal(p.scene.talkId,25);p.next();assert.equal(choices.length,2);p.choose(choices[0]);assert.equal(p.scene.talkId,30);p.back();assert.equal(p.scene.talkId,25);p.play();assert(p.resumeAfterChoice);p.pause();assert(!p.resumeAfterChoice);p.choose(choices[0]);assert(!p.playing);p.reset();assert.equal(p.scene.talkId,10);p.play();assert.equal(timers.size,1);p.dispose();assert.equal(timers.size,0);});
test('play and replay animate the selected dialogue from its predecessor without advancing',()=>{const frames=[];const p=new Scene.Player({getDoc:()=>doc,getContext:()=>({roots:[10]}),onRender:(scene,flags)=>frames.push({scene:json(scene),flags})});p.select(20);assert.equal(frames.at(-1).flags.animate,false);for(let repeat=0;repeat<2;repeat++){p.play();assert.equal(frames.at(-1).flags.animate,true);assert.equal(frames.at(-1).scene.motionStarts[3].x,-800);assert.equal(frames.at(-1).scene.roles[3].x,-600);assert.equal(p.scene.talkId,20);p.pause();p.refresh();}p.dispose();});
test('portrait candidate ordering respects mod overrides and native cache grade',()=>{const d=json(doc);d.persons[3].url2=['role/3'];let r={id:3,grade:1,cloth:0,face:10};assert.equal(Scene.portraitCandidates(d,r)[0],'role/3');d.persons[3].l2d2=['native-model'];assert.equal(Scene.portraitCandidates(d,r)[0],'portrait-cache/3-1-0-10.png');d.faces[3010]={id:3010,icon:'Mods/Example/face.png'};assert.equal(Scene.portraitCandidates(d,r)[0],'Mods/Example/face.png');});
test('automatic lighting follows speakers while preserving explicitly configured highlights',()=>{const original=json(doc),s=Scene.apply(doc,Scene.blank(),{id:1,roleIds:[3],highlights:[4],roles:[[3,1002,1,1],[4,1002,1,2]]});assert.deepEqual(json(s.highlightIds),[3,4]);assert.deepEqual(json(Scene.apply(doc,s,{id:9,roleIds:[0,3],studioLighting:{0:false,3:false}}).highlightIds),[0,3]);const n=Scene.apply(doc,s,{id:2,roleIds:[4],highlights:[3]});assert.deepEqual(json(n.highlightIds),[4,3]);assert.deepEqual(json(Scene.apply(doc,n,{id:3,roleIds:[-1],highlights:[3,4]}).highlightIds),[3,4]);assert.deepEqual(json(Scene.apply(doc,n,{id:4,roleIds:[]}).highlightIds),[]);assert.deepEqual(json(doc),original);});
test('speaker colour uses PersonCfg gender, with neutral narration and mixed or unknown groups',()=>{const d=json(doc);d.persons[0].gender=1;d.persons[3].gender=1;d.persons[4].gender=2;for(const [ids,gender] of [[[0],1],[[3],1],[[4],2],[[0,3],1],[[3,4],0],[[5],0],[[-1],0]])assert.equal(Scene.apply(d,Scene.blank(),{id:1,roleIds:ids}).speakerGender,gender);});
test('BGM carries through later lines and a finished one-shot does not restart',()=>{const made=[],cues={sfx:{1:[{audioId:4,volume:.5}]},bgm:[{id:'a',audioId:7,talkIds:[1,2,4],loop:false,volume:.8}]};const p=new Scene.AudioPlayer({getCues:()=>cues,getUrl:id=>'test/'+id,createAudio:url=>{const a={url,ended:false,paused:true,count:0,play(){this.paused=false;this.count++;return {catch(){}};},pause(){this.paused=true;}};made.push(a);return a;}});p.enter(1);const music=p.bgm;assert.equal(music.count,1);assert.equal(made.length,2);p.enter(2);assert.equal(p.bgm,music);assert.equal(music.count,1);music.ended=true;p.enter(4);assert.equal(p.bgm,music);assert.equal(music.count,1);p.enter(3);assert.equal(p.bgm,music);p.enter(4);assert.equal(p.bgm,music);assert.equal(music.count,1);p.stop();assert.equal(p.bgm,null);});
test('legacy BGM and SFX survive migration and explicit managed BGM owns its range',()=>{const made=[],cues={sfx:{1:[{audioId:4,volume:.5}],3:[{audioId:8}]},nativeAudio:{1:7},bgm:[{id:'range',audioId:9,talkIds:[4],loop:false,volume:1}]};const p=new Scene.AudioPlayer({getCues:()=>cues,getLegacy:id=>id===3?{id:8,type:2}:id===6?{id:6,type:1}:null,getUrl:id=>'test/'+id,createAudio:url=>{const a={url,ended:false,paused:true,count:0,play(){this.paused=false;this.count++;return {catch(){}};},pause(){this.paused=true;}};made.push(a);return a;}});p.enter(1);const native=p.bgm;assert.equal(native.url,'test/7');assert(native.loop);assert.equal(made.length,2);p.enter(2);assert.equal(p.bgm,native);assert.equal(native.count,1);p.enter(3);assert.equal(p.bgm,native);assert.equal(made.filter(a=>a.url==='test/8').length,1);p.enter(4);assert(native.paused);assert.equal(p.bgm.url,'test/9');p.enter(5);assert.equal(p.bgm.url,'test/9');p.enter(6);assert.equal(p.bgm.url,'test/6');p.enter(7);assert.equal(p.bgm.url,'test/6');p.stop();});
test('original default music fills empty ranges, persists between lines, and never overrides authored music',()=>{let fallback={id:4,url:'original/default',volume:.6},cues={bgm:[{id:'chosen',audioId:7,talkIds:[3,4],loop:false,volume:.8}]};const make=url=>({url,ended:false,count:0,play(){this.count++;this.paused=false;return {catch(){}};},pause(){this.paused=true;}});const p=new Scene.AudioPlayer({getCues:()=>cues,getDefaultBgm:()=>fallback,getUrl:id=>'mod/'+id,createAudio:make});p.enter(1);const original=p.bgm;assert.equal(original.url,'original/default');assert.equal(original.volume,.6);assert(original.loop);p.enter(2);assert.equal(p.bgm,original);assert.equal(original.count,1);p.enter(3);const chosen=p.bgm;assert(original.paused);assert.equal(chosen.url,'mod/7');assert(!chosen.loop);chosen.ended=true;p.enter(4);assert.equal(p.bgm,chosen);assert.equal(chosen.count,1);p.enter(5);assert.equal(p.bgm,chosen);assert.equal(chosen.count,1);chosen.ended=false;p.pause();assert(p.bgm.paused);p.resume();assert(!p.bgm.paused);p.stop();assert.equal(p.bgm,null);fallback=null;p.enter(8);assert.equal(p.bgm,null);fallback={id:4,url:'original/default'};p.enter(8);assert.equal(p.bgm.url,'original/default');p.stop();});

test('protagonist gender uses distinct portraits and speech colour without changing other actors',()=>{const d=json(doc);d.persons[0]={id:0,name:'白雨',gender:1,url:['boy','girl'],url2:['boy2','girl2'],l2d:['boy-model','girl-model'],l2d2:['boy-model2','girl-model2']};d.protagonistGender=2;assert.equal(Scene.apply(d,Scene.blank(),{id:1,roleIds:[0]}).speakerGender,2);const paths=Scene.portraitCandidates(d,{id:0,grade:0,cloth:0,face:0});assert(paths.includes('girl'));assert(paths.includes('portrait-cache/0-female-0-0-0.png'));assert(!paths.includes('boy'));assert(!paths.includes('portrait-cache/0-0-0-0.png'));assert(Scene.portraitCandidates(d,{id:0,grade:1,cloth:0,face:0}).includes('girl2'));d.protagonistGender=1;assert.equal(Scene.apply(d,Scene.blank(),{id:1,roleIds:[0]}).speakerGender,1);assert.equal(d.persons[0].gender,1);});

test('native male/female exits retain their gender for preview selection',()=>{const d=json(doc);d.talks[20].nextTalk=[25,30];let r=Scene.routes(d,d.talks[20]);assert.deepEqual(json(r.map(r=>[r.id,r.gender,r.genderOnly])),[[25,1,true],[30,2,true]]);d.talks[20].check=[[1,2]];d.talks[20].nextTalk2=[30,40];r=Scene.routes(d,d.talks[20]);assert.deepEqual(json(r.filter(r=>r.gender===2).map(r=>[r.id,r.type])),[[30,'next'],[40,'alternate']]);assert(r.every(r=>r.conditional&&!r.genderOnly));});
test('native scene change clears old cast before new entry, including occupied slots and flips',()=>{const d=json(doc);d.backgrounds[200]={id:200,url:'bg/classroom'};let s=Scene.apply(d,Scene.blank(),{id:1,bg:100,roles:[[3,1002,1,2],[4,1002,1,2],[3,3007]]});s=Scene.apply(d,s,{id:2,bg:200,roles:[[5,1002,1,3]]});assert.deepEqual(Object.keys(s.roles),['5']);s=Scene.apply(d,s,{id:3,roles:[[3,1002,1,2]]});assert.equal(s.roles[3].x,800);assert.equal(s.roles[3].flip,false);assert.equal(s.motionStarts[3].visible,false);});
test('bg zero and repeated background retain actors; black -1 clears and -2 retains',()=>{let s=Scene.apply(doc,Scene.blank(),{id:1,bg:100,roles:[[3,1002,1,1],[3,3004,75]]});for(const bg of [0,100,-2]){s=Scene.apply(doc,s,{id:2,bg});assert.equal(s.roles[3].x,-725);assert.equal(s.background,100);}s=Scene.apply(doc,s,{id:3,bg:-1});assert.deepEqual(Object.keys(s.roles),[]);assert.equal(s.background,100);});
test('scene change with implicit speaker re-enters from native default axis',()=>{const d=json(doc);d.backgrounds[200]={id:200};let s=Scene.apply(d,Scene.blank(),{id:1,bg:100,roleIds:[3],roles:[[3,1002,1,2],[3,3004,75],[3,3007]]});s=Scene.apply(d,s,{id:2,bg:200,roleIds:[3],roles:[]});assert.equal(s.roles[3].x,-800);assert.equal(s.roles[3].flip,false);assert.equal(s.motionStarts[3].visible,false);});
test('CG and comic modes bypass cast clearing until their native exit',()=>{const d=json(doc);d.backgrounds[200]={id:200};for(const screen of [[4015,1],[4016,1,0]]){let s=Scene.apply(d,Scene.blank(),{id:1,bg:100,roles:[[3,1002,1,1]],screenEffect:screen});s=Scene.apply(d,s,{id:2,bg:200,screenEffect:[4017]});assert(s.roles[3].visible);s=Scene.apply(d,s,{id:3,bg:100});assert.deepEqual(Object.keys(s.roles),[]);}});
test('phone keeps local cast, separates multiple remote slots and hides remote cast on hangup',()=>{let s=Scene.apply(doc,Scene.blank(),{id:1,bg:100,roleIds:[0],highlights:[0],roles:[[0,1002,1,2]],screenEffect:[4007,100,3,4]});assert.deepEqual(json(s.phone.local),[0]);assert(s.phone.localRight);assert.equal(s.roles[0].x,800);assert.equal(s.roles[3].x,-800);assert.equal(s.roles[4].x,-1100);s=Scene.apply(doc,s,{id:2,roleIds:[0],screenEffect:[4008]});assert.equal(s.phone,null);assert.equal(s.roles[3].visible,false);assert.equal(s.roles[4].visible,false);assert(s.roles[0].visible);});
test('phone actions retain native movement, expression and emphasis across dialogue lines',()=>{let s=Scene.apply(doc,Scene.blank(),{id:1,bg:100,roleIds:[0],highlights:[0],roles:[[0,1002,1,2]],screenEffect:[4007,100,3]});s=Scene.apply(doc,s,{id:2,roleIds:[3],roles:[[3,3004,160,0,0,.4],[3,3008,70,.4,0],[3,3003,1],[3,3000,10]]});assert.equal(s.roles[3].x,-640);assert.equal(s.roles[3].y,70);assert.equal(s.roles[3].scale,1.1);assert.equal(s.roles[3].face,10);s=Scene.apply(doc,s,{id:3,roleIds:[0]});assert.equal(s.roles[3].x,-640);assert.equal(s.roles[3].y,70);s=Scene.apply(doc,s,{id:4,roleIds:[0],screenEffect:[4008]});assert.equal(s.phone,null);s=Scene.apply(doc,s,{id:5,roleIds:[0]});assert.equal(s.phone,null);assert(!s.roles[3]);});
test('phone effect without a speaker preserves native no-op and warns instead of inventing a speaker',()=>{const row={id:1,bg:100,roleIds:[],screenEffect:[4007,100,3]},s=Scene.apply(doc,Scene.blank(),row);assert.equal(s.phone,null);assert(s.warnings.some(w=>w.includes('没有说话人')));assert.deepEqual(row.roleIds,[]);});
test('built-in phone with protagonist as remote retains inherited local actor and outfit without rewriting data',()=>{
  // Minimal native command sequence; no reporter dialogue or assets are embedded.
  const d=json(doc);d.backgrounds[200]={id:200,url:'bg/outdoors'};
  d.events={1:{id:1,type:2,talkId:[1]}};d.talks={
    1:{id:1,bg:100,roleIds:[],roles:[[4,1002,1,2,0],[4,3006,1]],nextTalk:[2]},
    2:{id:2,bg:100,roleIds:[],roles:[],nextTalk:[3]},
    3:{id:3,bg:0,roleIds:[4],highlights:[4],roles:[[0,1002,0,1],[4,3000,7]],screenEffect:[4007,200,0],nextTalk:[4]},
    4:{id:4,bg:0,roleIds:[0],highlights:[0],roles:[[0,3000,1]],screenEffect:[],nextTalk:[5]},
    5:{id:5,bg:0,roleIds:[],roles:[[0,2002]],screenEffect:[4008]}
  };
  const before=JSON.stringify(d);
  for(const id of [3,4]){
    const s=Scene.reconstruct(d,id,{roots:[1],grade:1});
    assert.deepEqual(json(s.phone.local),[4]);assert.deepEqual(json(s.phone.remote),[0]);
    assert.equal(s.phone.left,200);assert.equal(s.phone.right,100);assert(s.phone.localRight);
    assert(s.roles[4].visible);assert(s.roles[0].visible);
    assert.equal(s.roles[4].cloth,1);assert.equal(s.roles[4].face,7);
    assert.equal(s.roles[4].x,800);assert.equal(s.roles[0].x,-800);
  }
  const end=Scene.reconstruct(d,5,{roots:[1],grade:1});
  assert.equal(end.phone,null);assert(end.roles[4].visible);assert.equal(end.roles[0].visible,false);
  assert.equal(JSON.stringify(d),before);
});
test('outfits persist through exit, scene changes and phone re-entry, reset at a new event',()=>{
  const d=json(doc),before=JSON.stringify(d);d.backgrounds[200]={id:200,cloth:[0]};
  let s=Scene.apply(d,Scene.blank(),{id:1,bg:100,roles:[[4,1002,1,1],[4,3006,1]]});
  s=Scene.apply(d,s,{id:2,roles:[[4,2002]]});s=Scene.apply(d,s,{id:3,roles:[[4,1002,1,1],[4,3000,6]]});
  assert.equal(s.roles[4].cloth,1);assert.equal(s.roles[4].face,6);
  s=Scene.apply(d,s,{id:4,bg:200,roles:[[4,1002,1,1]]});assert.equal(s.roles[4].cloth,1);
  s=Scene.apply(d,s,{id:5,roleIds:[0],screenEffect:[4007,100,4]});assert.equal(s.roles[4].cloth,1);
  s=Scene.apply(d,s,{id:6,roles:[[4,3006,0],[4,2002]]});s=Scene.apply(d,s,{id:7,roles:[[4,1002,1,1]]});assert.equal(s.roles[4].cloth,0);
  assert.equal(Scene.apply(d,Scene.blank(),{id:8,bg:200,roleIds:[4]}).roles[4].cloth,0);
  assert.equal(JSON.stringify(doc),before);
});
test('static face fallback follows native missing-row and empty-grade semantics',()=>{
  const d=json(doc);d.persons[4]={id:4,url:['young-body'],url2:['older-body'],l2d:[],l2d2:[]};
  d.faces={4100:{id:4100,icon:'older-default',icon_xx:'young-default'},4106:{id:4106,icon:'older-face',icon_xx:'young-face'},4107:{id:4107,icon:'',icon_xx:'young-seven'}};
  for(const [grade,face,path,missing] of [[0,6,'young-face',false],[1,6,'older-face',false],[1,7,'older-body',true],[0,7,'young-seven',false],[0,8,'older-default',true],[1,8,'young-default',true]]){
    const role={id:4,cloth:1,face,grade};assert.deepEqual(json(Scene.portraitCandidates(d,role)),[path]);assert.equal(Scene.portraitSource(d,role).missing,missing);
  }
  d.persons[4].url2=[];assert.equal(Scene.portraitSource(d,{id:4,cloth:1,face:6,grade:1}).path,'young-face');
});
console.log(`Scene engine: ${checks} regression groups passed.`);

test('preview entry suppresses only its synthetic transition',()=>{vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../../standalone/screen-effects.js'),'utf8'),sandbox);const d=json(doc);d.backgrounds[200]={id:200,url:'bg/other'};d.talks={1:{id:1,bg:100,nextTalk:[2]},2:{id:2,bg:200,screenEffect:[4006],nextTalk:[3]},3:{id:3,bg:100}};d.events={1:{id:1,talkId:[1]}};const frames=[],p=new Scene.Player({getDoc:()=>d,getContext:()=>({roots:[1]}),onRender:s=>frames.push(s)});p.select(1);assert.equal(p.scene.transition,null);p.select(2);p.play({initial:true});assert.equal(frames.at(-1).transition,null);assert.equal(frames.at(-1).screen.command[0],4006);p.pause();p.next();assert(frames.at(-1).transition);p.dispose();});
