// Production workshop UI with isolated reference/save fixtures; no user Mod writes.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..'),schemas=JSON.parse(fs.readFileSync(path.join(root,'catalog-schema.json'))).schemas;
const features=JSON.parse(fs.readFileSync(path.join(root,'workshop-features.json'))).filter(f=>f.group==='恋爱与送礼');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROME_PATH,headless:true});try{
const page=await browser.newPage({viewport:{width:1600,height:1000}}),errors=[],calls=[];page.on('pageerror',e=>errors.push(e.message));
let revision='r1';const local={GiftEvtCfg:{1000000:{id:1000000,item:1,npc:[101,102],talkId:[[11],[12,13]],type:[],cond:[],redpoint:1,futureField:{keep:true}}},LoveBreakfastCfg:{1000001:{id:1000001,npc:101,item:1,msgTxt:'今天也要好好吃早餐。',msgIcon:null,cond:[],weight:1}},LoveVindicateRateCfg:{101:{id:101,favorParms:[.18,.01,1,1,1],attrParms:[.3,.01,1,1,1]}}};
const refs={PersonCfg:{101:{id:101,name:'小雅'},102:{id:102,name:'小夏'}},ItemCfg:{1:{id:1,name:'早餐面包'}},BookCfg:{2:{id:2,name:'诗集'}},TalkCfg:{11:{id:11,content:'谢谢你的礼物'},12:{id:12,content:'男主角入口'},13:{id:13,content:'女主角入口'}},LoveActionCfg:{10:{id:10,name:'看电影',funcId:602}},LoveVindicateCfg:{6:{id:6,target:.5,txt:'顺其自然',color:'#f79646'}},LoveDrawCfg:{1:{id:1,color:'#e52c2c'},10101:{id:10101,name:'情侣画',img:'',video:'draw',cond:[],talkId:[11],unknown:'keep'}}};
const project={id:'local:qa',name:'恋爱与送礼功能验收'},info={project,revision,features,tables:Object.keys(schemas).map(name=>({name,label:schemas[name].label,schema:schemas[name],localCount:Object.keys(local[name]||{}).length})),commands:{condition:[],effect:[]}};
await page.route('http://studio.test/**',async route=>{const req=route.request(),url=new URL(req.url());calls.push(url.pathname+url.search);if(url.pathname==='/')return route.fulfill({contentType:'text/html',body:'<!DOCTYPE html><html lang="zh-CN"><body></body></html>'});if(url.pathname==='/api/display-settings')return route.fulfill({json:{workshopFavorites:[]}});if(url.pathname==='/api/workshop')return route.fulfill({json:{...info,revision}});if(url.pathname==='/api/table'){const name=url.searchParams.get('name');assert(!name.includes('/'),'combined table sent to backend');return route.fulfill({json:{name,schema:schemas[name]||{fields:[]},rows:{...refs[name],...local[name]},referenceRows:refs[name]||{},localRows:local[name]||{},localIds:Object.keys(local[name]||{}),revision}});}if(url.pathname==='/api/table-save'){const data=req.postDataJSON();assert.equal(data.revision,revision);local[data.name]=data.rows;revision+='x';return route.fulfill({json:{ok:true,revision,rows:data.rows}});}return route.fulfill({status:404,json:{error:'unexpected '+url.pathname}});});
await page.goto('http://studio.test/');for(const file of ['styles.css','workshop.css','editor-theme.css','glass-palette.css','glass-theme.css','glass-tones.css','frosted-glass.css'])await page.addStyleTag({path:path.join(root,file)});
await page.evaluate(project=>{window.STUDIO_BOOTSTRAPPING=true;window.STUDIO_PROJECTS=()=>[project];window.STUDIO_CURRENT_PROJECT=()=>project.id;window.STUDIO_IDS={ensure:async()=>{},allocate:()=>1000002};window.StudentAgeConditions={summary:()=>'',parameterHTML:()=>''};window.STUDIO_NOTIFY=(msg,error)=>{if(error)throw Error(msg)};},project);
for(const file of ['record-labels.js','search.js','workshop.js'])await page.addScriptTag({path:path.join(root,file)});
await page.evaluate(()=>STUDIO_OPEN_WORKSHOP());
await page.locator('[data-feature="gift-events"]').first().click();await page.waitForSelector('[data-gift-remove="0"]');
assert.equal(await page.locator('.wk-gift-recipient').count(),2);
await page.click('[data-gift-remove="0"]');assert.deepEqual(await page.evaluate(()=>StudentAgeWorkshopTest.W.rows[1000000].npc),[102]);assert.deepEqual(await page.evaluate(()=>StudentAgeWorkshopTest.W.rows[1000000].talkId),[[12,13]]);
await page.click('[data-wk="undo"]');assert.equal(await page.locator('.wk-gift-recipient').count(),2);
await page.click('[data-gift-add]');assert.deepEqual(await page.evaluate(()=>StudentAgeWorkshopTest.W.rows[1000000].type),[0,0,0]);await page.click('[data-gift-remove="2"]');
await page.selectOption('[data-path="type.1"]','1');await page.click('[data-ref="item"]');await page.click('[data-choice-id="2"]');await page.click('#wk-save');await page.waitForFunction(()=>!StudentAgeWorkshopTest.W.busy && document.querySelector('#wk-save').disabled);
assert.deepEqual(local.GiftEvtCfg[1000000].talkId,[[11],[12,13]]);assert.deepEqual(local.GiftEvtCfg[1000000].type,[0,1]);assert.equal(local.GiftEvtCfg[1000000].item,2);assert.deepEqual(local.GiftEvtCfg[1000000].futureField,{keep:true});
if(process.env.UI_SCREENSHOT){fs.mkdirSync(process.env.UI_SCREENSHOT,{recursive:true});await page.screenshot({path:path.join(process.env.UI_SCREENSHOT,'gift-events.png')});}
await page.evaluate(()=>StudentAgeWorkshopTest.home());await page.locator('[data-feature="love-breakfast"]').first().click();await page.waitForFunction(()=>StudentAgeWorkshopTest.W.table?.name==='LoveBreakfastCfg'&&!StudentAgeWorkshopTest.W.busy);await page.fill('[data-path="msgTxt"]','荀彧：早餐准备好了。');await page.click('#wk-save');await page.waitForFunction(()=>!StudentAgeWorkshopTest.W.busy && document.querySelector('#wk-save').disabled);assert.equal(local.LoveBreakfastCfg[1000001].msgIcon,null);assert.match(local.LoveBreakfastCfg[1000001].msgTxt,/荀彧/);
await page.evaluate(()=>StudentAgeWorkshopTest.home());await page.locator('[data-feature="love-confession"]').first().click();await page.waitForFunction(()=>StudentAgeWorkshopTest.W.table?.name==='LoveVindicateCfg'&&!StudentAgeWorkshopTest.W.busy);assert.equal(await page.locator('[data-wk="new"]').count(),0);await page.fill('[data-path="txt"]','<img src=x onerror=alert(1)>');assert.equal(await page.locator('#wk-preview blockquote img').count(),0);await page.click('#wk-save');await page.waitForFunction(()=>!StudentAgeWorkshopTest.W.busy && document.querySelector('#wk-save').disabled);assert.equal(local.LoveVindicateCfg[6].target,.5);
await page.locator('.wk-module-tabs [data-table="LoveVindicateRateCfg"]').click();await page.waitForFunction(()=>StudentAgeWorkshopTest.W.table?.name==='LoveVindicateRateCfg'&&!StudentAgeWorkshopTest.W.busy);assert.equal(await page.locator('[data-path^="favorParms."]').count(),5);await page.fill('[data-path="favorParms.0"]','.2');await page.click('#wk-save');await page.waitForFunction(()=>!StudentAgeWorkshopTest.W.busy && document.querySelector('#wk-save').disabled);assert.deepEqual(local.LoveVindicateRateCfg[101].favorParms,[.2,.01,1,1,1]);
await page.evaluate(()=>StudentAgeWorkshopTest.home());await page.locator('[data-feature="love-draw"]').first().click();await page.waitForFunction(()=>StudentAgeWorkshopTest.W.table?.name==='LoveDrawCfg'&&!StudentAgeWorkshopTest.W.busy);assert.equal(await page.locator('[data-path="name"]').count(),0);await page.click('[data-row="10101"]');assert.equal(await page.locator('[data-path="color"]').count(),0);await page.fill('[data-path="name"]','小雅的画');await page.click('#wk-save');await page.waitForFunction(()=>!StudentAgeWorkshopTest.W.busy && document.querySelector('#wk-save').disabled);assert.equal(local.LoveDrawCfg[10101].unknown,'keep');
await page.evaluate(()=>StudentAgeWorkshopTest.home());await page.locator('[data-feature="love-breakfast"]').first().click();await page.waitForFunction(()=>StudentAgeWorkshopTest.W.table?.name==='LoveBreakfastCfg'&&!StudentAgeWorkshopTest.W.busy);assert.equal(await page.inputValue('[data-path="msgTxt"]'),'荀彧：早餐准备好了。');if(process.env.UI_SCREENSHOT)await page.screenshot({path:path.join(process.env.UI_SCREENSHOT,'love-breakfast.png')});
assert.deepEqual(errors,[]);console.log('PASS: recipient alignment, optional types, undo, item/book picker, save/reopen, null/unknown preservation, fixed records, parameter slots, escaped preview and draw variants');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
