/* Software-owned pickers shared by event and character editors. */
(()=>{'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const api=async(path,data)=>{const r=await fetch('/api/'+path,{method:data===undefined?'GET':'POST',headers:{'X-Studio-Token':STUDIO_TOKEN,'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)}),v=await r.json();if(!r.ok){const error=Error(v.error||'读取失败');error.status=r.status;throw error;}return v;};
function panel(title){const d=document.createElement('dialog');d.className='character-picker';d.innerHTML=`<header><h2>${esc(title)}</h2><button data-picker-close aria-label="关闭">×</button></header><div class="character-picker-body"></div><p class="character-picker-error" role="status"></p>`;document.body.append(d);let resolve;const promise=new Promise(r=>resolve=r);const end=v=>{d.close();d.remove();resolve(v);};d.querySelector('[data-picker-close]').onclick=()=>end(null);d.oncancel=e=>{e.preventDefault();end(null);};d.showModal();return {d,body:d.querySelector('.character-picker-body'),promise,end,error:e=>d.querySelector('[role=status]').textContent=e.message||String(e)};}
async function choices(title,rows,{image=null,selected=null,extra=null,table=null,projectId=null,multiple=false}={}){if(['PersonCfg','BgCfg'].includes(table))return STUDIO_ASSET_PICKER.pickRecords(table==='PersonCfg'?'portrait':'background',{title,rows,image,selected,projectId,multiple});const p=panel(title);p.d.setAttribute('data-dismiss-outside','');p.body.innerHTML='<input class="character-choice-search" placeholder="搜索名称或编号"><div class="character-choice-grid"></div>';p.body.querySelector('input').hidden=rows.length<10;const paint=()=>{const q=p.body.querySelector('input').value;p.body.querySelector('.character-choice-grid').innerHTML=rows.filter(r=>StudentAgeSearch.matches(q,r.id,r.name,r.description)).map(r=>`<button data-character-choice="${r.id}" class="${String(r.id)===String(selected)?'active':''}">${image?`<img src="${esc(image(r))}" loading="lazy" alt="${esc(r.name)}">`:''}<strong>${StudentAgeRecordLabels.html(r.id,r.name||r.title||r.url||'未命名')}</strong>${r.description?`<small>${esc(r.description)}</small>`:''}</button>`).join('')+(extra?'<button data-choice-extra class="character-add-card" aria-label="添加头像">＋<span>添加头像</span></button>':'');};p.body.oninput=paint;p.body.onclick=e=>{const b=e.target.closest('[data-character-choice]');if(b)p.end(rows.find(r=>String(r.id)===b.dataset.characterChoice));if(e.target.closest('[data-choice-extra]')){p.end(null);extra();}};paint();return p.promise;}
const eventDescription=id=>({110:'选择收礼人和礼物物品，赠送时播放指定对话。',0:'回合开始时检查条件。',[-2]:'首次满足条件闲聊时播放一次剧情，之后使用设置的闲聊进度文字。',[-24]:'在指定角色小游戏的所选关卡开始前播放。',2:'达到设定好感度后，闲聊入口出现原版红点提示。',20:'触发关系剧情，完成后解锁一次性行动。',11:'选择约会行动与角色，包括看电影。',521:'选择约会行动与角色，包括看电影。',21:'打招呼相关剧情。',22:'恋爱时选择话题播放；可设置重复出现与亲密度变化。',70:'玩家主动打电话时触发；左右分屏显示白雨与通话对象。',71:'玩家接到电话时触发；左右分屏显示白雨与通话对象。',522:'恋爱社交按钮触发，需要设置指定角色。'})[id]||'按游戏对此事件类型的规则及事件条件触发。';
function eventName(id,rows={}){return window.StudentAgeEventBindings?.socialNames?.[id]|| (Number(id)===110?'送礼对话':Number(id)===4?'行动触发事件':rows[id]?.name||window.StudentAgeEventTypes?.[id]?.name||'未识别事件类型（ID '+id+'）');}
// EvtCfg.npc is interpreted by each native trigger, not always a PersonCfg ID.
function eventParameter(id){return ({[-2]:['PersonCfg','角色'],[-24]:['PersonCfg','角色'],11:['PersonCfg','角色'],2:['PersonCfg','角色'],20:['PersonCfg','关系任务角色'],21:['PersonCfg','打招呼的角色'],22:['PersonCfg','聊天角色'],30:['SceneItem','场景物品'],60:['PersonStateCfg','显示的状态'],61:['PersonCfg','路人角色'],62:['ItemCfg','点击的物品'],63:['PersonCfg','路人角色'],70:['PersonCfg','打给谁'],71:['PersonCfg','谁打来的'],131:['ClubDailyCfg','社团活动'],520:['PersonCfg','表白角色'],521:['PersonCfg','恋人'],522:['PersonCfg','恋爱社交角色'],523:['PersonCfg','送生日礼物的角色']})[Number(id)]||null;}
async function eventType(projectId,current,parameters={}){
 const p=panel('选择事件类型');p.d.classList.add('event-type-picker');let rows={...window.StudentAgeEventTypes,[-24]:{id:-24,name:'社交小游戏事件'}},group='全部',selected=Number(current),npc=Number(parameters.npc)||0,mapId=Number(parameters.mapId)||0,phone=parameters.phone?structuredClone(parameters.phone):null,phoneChanged=false;
 delete rows[522];delete rows[-2];
 const linked=window.StudentAgeEventBindings.create(parameters);
 const mapValues=new Map([[Number(current)===37?'phase':'place',mapId]]);
 const refs={...window.StudentAgeEventReferences},loading=new Map(),typed=new Map([[eventParameter(current)?.[0]||'raw',npc]]);
 const table=async name=>{if(loading.has(name))return loading.get(name);const pending=api('table?'+new URLSearchParams({projectId,name})).then(v=>{refs[name]={...refs[name],...v.rows};return refs[name];});loading.set(name,pending);return pending;};
 p.body.innerHTML='<div class="event-type-layout"><section><nav class="character-filters">'+['全部','回合与行动','人物社交','电话','其他'].map(x=>`<button data-type-group="${x}">${x}</button>`).join('')+'</nav><input data-event-search placeholder="搜索事件类型、名称或编号"><div class="character-choice-grid"></div></section><aside class="event-parameter-panel"></aside></div><footer class="event-type-footer"><button data-event-cancel>取消</button><button data-event-confirm class="primary">应用类型与参数</button></footer>';
 const category=id=>[70,71].includes(id)?'电话':[-2,-24,2,11,20,21,22,110,520,521,522,523].includes(id)?'人物社交':[0,1,3,4,10,101,102,104].includes(id)?'回合与行动':'其他';
 function objectName(){const meta=eventParameter(selected),row=meta&&refs[meta[0]]?.[npc];return row?.name||row?.title||(npc?'原有对象（ID '+npc+'）':'选择'+(meta?.[1]||'对象'));}
 function right(){const meta=eventParameter(selected),tel=[70,71].includes(selected);p.body.querySelector('aside').innerHTML=`<h3>参数设置</h3><strong>${esc(eventName(selected,rows))}</strong><p>${esc(eventDescription(selected))}</p>${meta?`<label>${esc(meta[1])}<button data-event-object>${esc(objectName())} ▾</button></label>`:'<p class="helper">此类型通过下方事件条件设置触发要求。</p>'}${selected===60?'<p class="helper">这里设置事件显示的状态图标；需要持有该状态时，请在事件条件中添加“具有状态”。</p>':''}${selected===30?'<p class="helper">场景物品来自已有事件的场景物品编号，与背包物品分别管理。</p>':''}${selected===70?'<p class="helper">所选人物需已加入游戏电话联系人。</p>':''}${selected===37?`<label>生日派对阶段<select data-event-phase>${[[0,'任意阶段'],[1,'开场剧情'],[2,'派对选项']].map(([v,l])=>`<option value="${v}" ${mapId===v?'selected':''}>${l}</option>`).join('')}${![0,1,2].includes(mapId)?`<option selected value="${mapId}">原有阶段 ${mapId}</option>`:''}</select></label>`:[21,61,63].includes(selected)?`<label>发生地点<button data-event-place>${esc(refs.MapCfg?.[mapId]?.name||(mapId?'地点 '+mapId:'不限地点'))} ▾</button></label>`:''}${tel&&phone?`<label>电话画面对话<button data-event-phone-talk>${esc(phone.name||'选择对话')} ▾</button></label><label>对方所在场景<button data-event-phone-bg>${esc((refs.BgCfg?.[phone.bg]&&window.StudentAgeAssetNames?.name(refs.BgCfg[phone.bg],'background',refs.BgCfg))||'场景 '+phone.bg)} ▾</button></label><p class="helper">设置通话角色后，会同步所选对话的电话画面。对话文字和说话角色保持原样。</p>`:''}${window.StudentAgeEventBindings.socialKinds[selected]?'':`<details><summary>原始对象参数</summary><label>对象 ID<input data-event-raw type="number" step="1" value="${npc}"></label><p class="helper">用于保留尚未识别的扩展对象。</p></details>`}`;linked.mount(p.body.querySelector('aside'),{type:selected,npc,projectId,repaint:right,error:p.error});if(selected===11||selected===521){const aside=p.body.querySelector('aside'),label=aside.querySelector('[data-event-object]')?.closest('label');if(label)aside.append(label);}}
 const paint=()=>{if(!p.d.open)return;const q=p.body.querySelector('[data-event-search]').value;p.body.querySelectorAll('[data-type-group]').forEach(b=>b.classList.toggle('active',b.dataset.typeGroup===group));const list=Object.values(rows).filter(r=>Number(r.id)!==521&&(Number(r.id)===Number(current)||Number(r.id)<800||Number(r.id)>=1000)).map(r=>({...r,name:eventName(r.id,rows)}));if(!rows[current])list.push({id:current,name:eventName(current,rows)});p.body.querySelector('.character-choice-grid').innerHTML=list.filter(r=>(group==='全部'||category(Number(r.id))===group)&&StudentAgeSearch.matches(q,r.id,r.name,eventDescription(Number(r.id)))).map(r=>`<button data-event-type-id="${r.id}" class="${Number(r.id)===selected?'active':''}"><strong>${StudentAgeRecordLabels.html(r.id,r.name||r.title||r.url||'未命名')}</strong><small>${esc(eventDescription(Number(r.id)))}</small></button>`).join('');right();};
 async function objectRows(){const meta=eventParameter(selected);if(!meta)return [];if(meta[0]==='SceneItem'){const events=await table('EvtCfg'),items={};for(const r of Object.values(events))if(Number(r.type)===30&&r.npc)items[r.npc]??={id:Number(r.npc),name:r.title||'场景物品 '+r.npc};refs.SceneItem=items;return Object.values(items);}return Object.values(await table(meta[0])).map(r=>({...r,name:r.name||r.title||r.desc||'项目 '+r.id}));}
 p.body.querySelector('[data-event-search]').oninput=paint;
 p.body.onchange=e=>{if(e.target.hasAttribute('data-event-raw')){const n=Number(e.target.value);if(!e.target.value.trim()||!Number.isInteger(n)||n>2147483647||n<-2147483648){e.target.setCustomValidity('请填写有效的对象整数编号。');e.target.reportValidity();return;}npc=n;typed.set(eventParameter(selected)?.[0]||'raw',npc);phoneChanged=[70,71].includes(selected);right();}if(e.target.hasAttribute('data-event-phase'))mapId=Number(e.target.value);};
 p.body.onclick=async e=>{const b=e.target.closest('button');if(!b)return;try{if(b.dataset.typeGroup){group=b.dataset.typeGroup;paint();}if(b.dataset.eventTypeId){typed.set(eventParameter(selected)?.[0]||'raw',npc);mapValues.set(selected===37?'phase':'place',mapId);selected=Number(b.dataset.eventTypeId);mapId=mapValues.get(selected===37?'phase':'place')||0;npc=typed.get(eventParameter(selected)?.[0]||'raw')||0;paint();}if(b.hasAttribute('data-event-object')){b.disabled=true;const meta=eventParameter(selected),list=await objectRows(),choice=await choices('选择'+meta[1],list.filter(r=>Number(r.id)!==0),{selected:npc,table:meta[0],projectId});if(choice){npc=Number(choice.id);typed.set(meta[0],npc);phoneChanged=[70,71].includes(selected);}right();}if(b.hasAttribute('data-event-place')){const chosen=await choices('选择发生地点',[{id:0,name:'不限地点'},...Object.values(await table('MapCfg')).filter(r=>r.id)],{selected:mapId});if(chosen){mapId=chosen.id;right();}}if(b.hasAttribute('data-event-phone-talk')){const chosen=await choices('选择电话画面对话',parameters.phoneTalks||[],{selected:phone.talkId});if(chosen){phone={...phone,talkId:chosen.id,name:chosen.name};phoneChanged=true;right();}}if(b.hasAttribute('data-event-phone-bg')){const chosen=await choices('选择对方场景',Object.values(await table('BgCfg')).map(r=>({...r,name:window.StudentAgeAssetNames?.name?.(r,'background',refs.BgCfg||{})||r.name||r.url||'场景 '+r.id})),{selected:phone.bg,table:'BgCfg',projectId});if(chosen){phone.bg=chosen.id;phoneChanged=true;right();}}if(b.hasAttribute('data-event-cancel'))p.end(null);if(b.hasAttribute('data-event-confirm')){const invalid=p.body.querySelector(':invalid');if(invalid){invalid.reportValidity();return;}const draft=linked.value(),social=draft.social;if(social?.kind==='topic'&&!social.title.trim()){p.error('请填写话题名称。');return;}p.end({id:selected===-2?2:selected===-24?4:selected,name:eventName(selected,rows),npc,mapId,social,bindings:parameters.bindings?linked.value():undefined,phone:phoneChanged&&phone&&[70,71].includes(selected)?{...phone,role:npc}:null});}}catch(error){b.disabled=false;p.error(error);}};
 paint();Promise.all([table('EvtTypeCfg'),table('MapCfg'),table('PersonCfg')]).then(([types])=>{rows={...rows,...types};delete rows[-2];delete rows[522];if(p.d.open)paint();}).catch(p.error);return p.promise;
}
async function calendar(value){const p=panel('选择生日'),now=Array.isArray(value)&&value.length===3?value:[1990,1,1];let year=Number(now[0])||1990,month=Number(now[1])||1;p.d.classList.add('character-calendar');p.body.innerHTML='<div class="calendar-month"><button data-month="-1">←</button><input aria-label="出生年份" type="number" min="1" max="9999"><select aria-label="出生月份">'+Array.from({length:12},(_,i)=>`<option value="${i+1}">${i+1} 月</option>`).join('')+'</select><button data-month="1">→</button></div><div class="calendar-week">'+['日','一','二','三','四','五','六'].map(x=>`<span>${x}</span>`).join('')+'</div><div class="calendar-days"></div><button data-birthday-clear>不设置生日</button>';
 const paint=()=>{p.body.querySelector('input').value=year;p.body.querySelector('select').value=month;const date=new Date(0);date.setFullYear(year,month-1,1);const first=date.getDay();date.setFullYear(year,month,0);const total=date.getDate();p.body.querySelector('.calendar-days').innerHTML='<span></span>'.repeat(first)+Array.from({length:total},(_,i)=>`<button data-birthday-day="${i+1}" class="${year===now[0]&&month===now[1]&&i+1===now[2]?'active':''}">${i+1}</button>`).join('');};p.body.onchange=()=>{year=Math.max(1,Math.min(9999,Number(p.body.querySelector('input').value)||1990));month=Number(p.body.querySelector('select').value);paint();};p.body.onclick=e=>{const n=e.target.closest('[data-month]'),d=e.target.closest('[data-birthday-day]');if(n){month+=Number(n.dataset.month);if(month>12){year++;month=1;}if(month<1){year--;month=12;}year=Math.max(1,Math.min(9999,year));paint();}if(d)p.end([year,month,Number(d.dataset.birthdayDay)]);if(e.target.closest('[data-birthday-clear]'))p.end([]);};paint();return p.promise;}
async function media(options){const p=panel(options.title||(options.mode==='expression'?'表情数据库':'立绘素材库'));let source='original',sourceProjectId='',affection='',clothing='',query='',page=0,sequence=0,items=[],projects=[];p.d.classList.add('character-media');let timer,observer;const originalEnd=p.end;p.end=v=>{clearTimeout(timer);observer?.disconnect();sequence++;originalEnd(v);};p.d.querySelector('[data-picker-close]').onclick=()=>p.end(null);p.d.oncancel=e=>{e.preventDefault();p.end(null);};
 p.body.innerHTML='<nav class="character-filters">'+[['original','原版'],['mod','模组'],['custom','自添加']].map(([v,l])=>`<button data-media-source="${v}">${l}</button>`).join('')+'</nav><select data-media-project hidden aria-label="来源模组"></select><nav class="character-filters">'+[['','全部'],['yes','好感角色'],['no','非好感角色']].map(([v,l])=>`<button data-media-affection="${v}">${l}</button>`).join('')+'</nav><nav class="character-filters">'+['全部','夏季校服','冬季校服','日常服','其他'].map(v=>`<button data-media-clothing="${v==='全部'?'':v}">${v}</button>`).join('')+'</nav><input id="character-media-search" placeholder="搜索人物、服装或表情"><button data-media-folder hidden>设置自添加素材文件夹</button><div class="character-media-grid"></div><button data-media-more hidden>加载更多</button>';
 const params=()=>({projectId:options.projectId,revision:options.revision(),source,sourceProjectId,kind:'portrait',variantMode:options.mode,affection,clothingCategory:clothing,q:query,page:String(page),pageSize:'40'});
 async function fetchImages(){observer?.disconnect();observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting){observer.unobserve(e.target);const img=e.target,url=img.dataset.image;let attempt=0;const run=async()=>{if(!p.d.open||!img.isConnected)return;try{const r=await fetch(url,{headers:{'X-Studio-Token':STUDIO_TOKEN}});if(r.status===425&&attempt++<30){setTimeout(run,1000);return;}if(!r.ok){img.alt='预览暂不可用';return;}const blob=await r.blob();if(!img.isConnected)return;const src=URL.createObjectURL(blob);img.onload=()=>URL.revokeObjectURL(src);img.src=src;}catch{img.alt='预览暂不可用';}};run();}},{root:p.body,rootMargin:'100px'});p.body.querySelectorAll('img[data-image]').forEach(i=>observer.observe(i));}
 async function reload(more=false){const request=++sequence;if(!more){page=0;items=[];observer?.disconnect();p.body.querySelector('.character-media-grid').innerHTML='<p>正在读取素材…</p>';}p.body.querySelectorAll('[data-media-source]').forEach(b=>b.classList.toggle('active',b.dataset.mediaSource===source));p.body.querySelectorAll('[data-media-affection]').forEach(b=>b.classList.toggle('active',b.dataset.mediaAffection===affection));p.body.querySelectorAll('[data-media-clothing]').forEach(b=>b.classList.toggle('active',b.dataset.mediaClothing===clothing));p.body.querySelector('[data-media-project]').hidden=source!=='mod';p.body.querySelector('[data-media-folder]').hidden=source!=='custom';p.error('正在读取…');try{const result=await api('asset-catalog?'+new URLSearchParams(params()));if(request!==sequence||!p.d.open)return;items=more?items.concat(result.items):result.items;p.body.querySelector('.character-media-grid').innerHTML=items.map((item,i)=>`<button data-media-item="${i}"><img data-image="${esc(item.previewUrl+'&token='+encodeURIComponent(STUDIO_TOKEN))}" alt="${esc(item.name)}"><strong>${esc(item.name)}</strong><small>${esc(item.sourceProjectName||'')}${options.mode==='expression'?' · '+esc(item.expressionName):''}</small></button>`).join('')||'<p>没有匹配素材。</p>';p.body.querySelector('[data-media-more]').hidden=items.length>=result.total;p.error(result.warnings?.join('；')||'未明确标注季节的服装归入“其他”。点击图片即可使用。');fetchImages();}catch(e){if(request===sequence)p.error(e);}}
 p.body.onclick=async e=>{const b=e.target.closest('button');if(!b)return;try{if(b.dataset.mediaSource){source=b.dataset.mediaSource;await reload();}else if(b.dataset.mediaAffection!==undefined){affection=b.dataset.mediaAffection;await reload();}else if(b.dataset.mediaClothing!==undefined){clothing=b.dataset.mediaClothing;await reload();}else if(b.hasAttribute('data-media-more')){page++;await reload(true);}else if(b.hasAttribute('data-media-folder')){const path=await window.STUDIO_CHOOSE_ASSET_FOLDER?.('portrait');if(path){const cfg=await api('asset-folders');await api('asset-folders',{kind:'portrait',path,settingsRevision:cfg.revision});await reload();}}else if(b.dataset.mediaItem!==undefined){const item=items[Number(b.dataset.mediaItem)];b.disabled=true;p.error('正在读取所选图片…');const url=new URL(item.previewUrl,location.href);let result;for(let retry=0;retry<60&&p.d.open;retry++){try{result=await api('character-image',{...Object.fromEntries(url.searchParams),projectId:options.projectId,revision:options.revision()});break;}catch(error){if(error.status!==425||retry===59)throw error;await new Promise(r=>setTimeout(r,1000));}}if(result&&p.d.open)p.end({...result,item});}}catch(err){b.disabled=false;p.error(err);}};
 p.body.oncontextmenu=e=>{const card=e.target.closest('[data-media-item]'),item=card&&items[Number(card.dataset.mediaItem)];if(source==='custom'&&item)window.StudentAgeContextMenu(e,item.origin==='imported'?'删除该自定义人物':'删除自定义素材',async()=>{if(await window.STUDIO_DELETE_CUSTOM_ASSET(item,params()))await reload();});};
 p.body.querySelector('input').oninput=e=>{query=e.target.value;clearTimeout(timer);sequence++;items=[];observer?.disconnect();p.body.querySelector('.character-media-grid').innerHTML='<p>正在搜索…</p>';timer=setTimeout(()=>reload(),180);};p.body.querySelector('[data-media-project]').onchange=e=>{sourceProjectId=e.target.value;reload();};
 try{const result=await api('projects');projects=Array.isArray(result)?result:result.projects||[];p.body.querySelector('[data-media-project]').innerHTML='<option value="">全部模组</option>'+projects.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('');}catch(e){p.error(e);}reload();return p.promise;}
async function outfitLocations(places,current=[],name='服装',isDefault=false){
 places=places.filter(r=>String(r.name||'').trim()&&!/^(?:场景|地点|背景)?\s*#?\d+$/.test(String(r.name).trim())).map(r=>({...r,id:Number(r.id)}));
 const p=panel('设置穿着地点'),chosen=new Set(current.map(Number));let group='全部';p.d.classList.add('outfit-location-picker');
 p.body.innerHTML=`<label>服装名称<input data-outfit-name value="${esc(name)}" maxlength="120"></label><nav class="character-filters">${['全部',...new Set(places.map(x=>x.group))].map(g=>`<button data-place-group="${esc(g)}">${esc(g)}</button>`).join('')}</nav><input data-place-search placeholder="搜索地点"><p>${isDefault?'未单独指定服装的地点都会使用这套默认服装。':'未选择地点时，仅供手动换装。选中的地点会改用这套服装。'}</p><button data-place-all>全选当前分类</button><div class="character-choice-grid"></div>`;const footer=document.createElement('footer');footer.className='outfit-location-footer';footer.innerHTML='<button data-outfit-confirm class="primary">确定</button>';p.d.append(footer);
 const paint=()=>{const q=p.body.querySelector('[data-place-search]').value,rows=places.filter(r=>group==='全部'||r.group===group);p.body.querySelector('[data-place-all]').textContent=rows.length&&rows.every(r=>chosen.has(r.id))?'取消全选当前分类':'全选当前分类';p.body.querySelectorAll('[data-place-group]').forEach(b=>b.classList.toggle('active',b.dataset.placeGroup===group));p.body.querySelector('.character-choice-grid').innerHTML=places.filter(r=>(group==='全部'||r.group===group)&&StudentAgeSearch.matches(q,r.name,r.id)).map(r=>`<button data-place-id="${r.id}" class="${chosen.has(r.id)?'active':''}" aria-pressed="${chosen.has(r.id)}">${chosen.has(r.id)?'✓ ':''}${esc(r.name)} <small>${r.id}</small></button>`).join('');};
 p.body.querySelector('[data-place-search]').oninput=paint;p.d.onclick=e=>{const b=e.target.closest('[data-place-id]'),g=e.target.closest('[data-place-group]');if(b){const id=Number(b.dataset.placeId);chosen.has(id)?chosen.delete(id):chosen.add(id);paint();}if(g){group=g.dataset.placeGroup;paint();}if(e.target.closest('[data-place-all]')){const rows=places.filter(r=>group==='全部'||r.group===group),all=rows.length&&rows.every(r=>chosen.has(r.id));for(const r of rows)all?chosen.delete(r.id):chosen.add(r.id);paint();}if(e.target.closest('[data-outfit-confirm]')){const name=p.body.querySelector('[data-outfit-name]').value.trim();if(!name){p.error('请填写服装名称。');return;}p.end({name,backgrounds:[...chosen]});}};paint();return p.promise;
}
function contextMenu(event,label,action){event.preventDefault();event.stopPropagation();document.querySelectorAll('.studio-delete-menu').forEach(n=>n.remove());const menu=document.createElement('div');menu.className='studio-delete-menu';const b=document.createElement('button');b.textContent=label;menu.append(b);(event.target.closest('dialog')||document.body).append(menu);menu.style.left=Math.min(event.clientX,innerWidth-190)+'px';menu.style.top=Math.min(event.clientY,innerHeight-70)+'px';b.onclick=async()=>{menu.remove();try{await action();}catch(e){window.STUDIO_REPORT_ERROR?.(e);}};setTimeout(()=>document.addEventListener('pointerdown',e=>{if(!menu.contains(e.target))menu.remove();},{once:true}),0);menu.onkeydown=e=>{if(e.key==='Escape'){e.stopPropagation();menu.remove();}};b.focus();}
async function deleteCustomAsset(item,params){
 const p=panel('删除自定义素材？');p.body.innerHTML='<p>'+esc(item.name||'所选素材')+'</p><p>从自定义素材库移除。文件夹素材会移到原目录下的 .StudentAgeStudioDeleted 文件夹。</p><button data-no>取消</button><button class="danger-button" data-yes>删除</button>';p.body.querySelector('[data-no]').onclick=()=>p.end(false);p.body.querySelector('[data-yes]').onclick=()=>p.end(true);if(!await p.promise)return false;
 if(!await window.STUDIO_NAV.saveAll())return false;
 const project=await api('project?id='+encodeURIComponent(params.projectId));
 const result=await api('asset-catalog-delete',{...params,revision:project.revision,sourceRevision:project.revision,assetId:item.rawAssetId||item.assetId,assetRevision:item.mediaRevision});
 await window.STUDIO_REFRESH_CURRENT_PROJECT?.();await window.STUDIO_WORKSHOP_NAV?.refreshAssets?.();window.dispatchEvent(new CustomEvent('studio-assets-removed',{detail:{projectId:params.projectId,revision:result.revision}}));return true;
}
window.STUDIO_DELETE_CUSTOM_ASSET=deleteCustomAsset;
window.StudentAgeContextMenu=contextMenu;
window.StudentAgeCharacterUI={esc,api,choices,calendar,media,outfitLocations,eventType,eventName,eventDescription,eventParameter};
})();
