(()=>{'use strict';
const UI=StudentAgeCharacterUI,esc=UI.esc,copy=v=>structuredClone(v),tables=['PersonCfg','PersonGrowCfg','ModFaceCfg','KZoneAvatarCfg','KZoneProfileCfg'];
function create(host,options){
const api=options.api,S={data:null,tables:{},outfits:{},romance:{},cloth:0,previewFace:0,saved:'',revision:null,selected:null,tab:'profile',face:null,grade:1,search:'',page:0,busy:false,undo:[],redo:[],last:null};
const $=s=>host.querySelector(s),readonly=()=>!!options.project.readOnly,people=()=>Object.fromEntries(Object.entries(S.tables.PersonCfg||{}).filter(([id])=>!S.data?.goalImageIds?.includes(id))),person=()=>people()[S.selected],all=n=>({...S.data?.tables[n]?.referenceRows,...S.tables[n]}),snapshot=()=>JSON.stringify({tables:S.tables,outfits:S.outfits,romance:S.romance}),dirty=()=>!!S.data&&(snapshot()!==S.saved||!!host.querySelector('[aria-invalid="true"]'));
const notify=()=>{host.querySelectorAll('#character-form fieldset').forEach(n=>n.disabled=readonly()||S.busy);options.onState?.({busy:S.busy,dirty:dirty(),readOnly:readonly(),canUndo:S.undo.length>0,canRedo:S.redo.length>0,revision:S.revision});};
const imageURL=path=>'/api/assets?'+new URLSearchParams({projectId:options.project.id,path,token:options.token});
const headURL=id=>'/api/space-head?'+new URLSearchParams({projectId:options.project.id,personId:id,token:options.token});
function change(fn,key){if(readonly()||S.busy)throw Error('当前人物不可编辑。');if(!key||S.last!==key){S.undo.push(snapshot());if(S.undo.length>60)S.undo.shift();}S.last=key||null;S.redo=[];fn();notify();}
function restore(serialized){const data=JSON.parse(serialized);S.tables=data.tables;S.outfits=data.outfits||{};S.romance=data.romance||{};if(!person())S.selected=Object.keys(people())[0]||null;S.last=null;render();notify();}
function history(from,to){if(readonly()||S.busy||!S[from].length)return;S[to].push(snapshot());restore(S[from].pop());}
function defaults(table){return Object.fromEntries((S.data.tables[table].schema.fields||[]).map(f=>[f.name,copy(f.default??(f.type.startsWith('list')?[]:f.type==='string'?'':0))]));}
function newPerson(duplicate=false){const before=person();let selected;change(()=>{selected=STUDIO_IDS.allocate('PersonCfg',all('PersonCfg'));const p=duplicate&&before?copy(before):{...defaults('PersonCfg'),name:'未命名人物',gender:1};p.id=selected;if(![1,2].includes(Number(p.gender)))p.gender=1;if(duplicate)p.name+=' · 副本';S.tables.PersonCfg[selected]=p;if(!duplicate)S.tables.PersonGrowCfg[selected]={...defaults('PersonGrowCfg'),id:selected,ItemPref:Array.from({length:11},(_,i)=>[i+1,0])};if(duplicate){if(S.romance[before.id])S.romance[selected]=copy(S.romance[before.id]);if(S.outfits[before.id])S.outfits[selected]=copy(S.outfits[before.id]);for(const table of ['PersonGrowCfg','KZoneProfileCfg'])if(all(table)[before.id])S.tables[table][selected]={...copy(all(table)[before.id]),id:selected};for(const face of Object.values(all('ModFaceCfg')))if(Math.floor(face.id/1000)===before.id){const id=selected*1000+face.id%1000;S.tables.ModFaceCfg[id]={...copy(face),id};}}});S.selected=String(selected);S.face=null;S.cloth=0;S.previewFace=0;render();}
function removePerson(){if(!person())return;const selected=S.selected;change(()=>{delete S.outfits[selected];delete S.romance[selected];delete S.tables.PersonCfg[selected];delete S.tables.PersonGrowCfg[selected];delete S.tables.KZoneProfileCfg[selected];for(const key of Object.keys(S.tables.ModFaceCfg))if(Math.floor(Number(key)/1000)===Number(selected))delete S.tables.ModFaceCfg[key];});S.selected=Object.keys(people())[0]||null;render();options.status('人物已从草稿移除，可以撤销。若其他剧情仍引用该人物，保存时会提示。');}
const labels={ItemPref:'礼物喜好',attr:'初始属性',grow:'属性成长',className:'所在班级',examRank:'考试排名',studyRank:'学习排名',focusAttrId:'重点属性',trait:'人物特质',speciality:'人物特长',personalitys:'性格数值',minigame:'小游戏',items:'携带物品',state:'初始状态',order:'排序'};
const model=StudentAgeCharacterModel.create({S,host,person,all,change,options,imageURL,readonly,pickMedia,pickAvatar,notify});
const controls=StudentAgeCharacterControls.create({S,host,person,all,change,renderForm,pathValue,imageURL,options,notify});
const references={focusAttrId:'PersonAttrCfg',trait:'TraitsCfg',speciality:'TraitsCfg',items:'ItemCfg',state:'PersonStateCfg'};
function field(value,path,type='float',ref=null){if(/^PersonGrowCfg\.\d+\.ItemPref$/.test(path)){const prefs=new Map((value||[]).map(pair=>[Number(pair[0]),pair[1]]));return `<div class="character-gifts">${Array.from({length:11},(_,i)=>i+1).map(id=>`<div class="character-gift"><span>${esc(S.refs?.ItemTagCfg?.[id]?.name||'物品类型 '+id)}</span><button data-gift-step="-1" data-gift-id="${id}" aria-label="减少${esc(S.refs?.ItemTagCfg?.[id]?.name||id)}喜好">−</button><input type="number" step="1" data-gift-id="${id}" value="${prefs.get(id)??0}" aria-label="${esc(S.refs?.ItemTagCfg?.[id]?.name||id)}喜好"><button data-gift-step="1" data-gift-id="${id}" aria-label="增加${esc(S.refs?.ItemTagCfg?.[id]?.name||id)}喜好">＋</button></div>`).join('')}</div>`;}if(Array.isArray(value)||type.startsWith('list<')){const arr=Array.isArray(value)?value:[],sub=type.startsWith('list<')?type.slice(5,-1):'float';if(!ref&&!sub.startsWith('list')&&!arr.some(v=>v!==null&&typeof v==='object'))return StudentAgeConditions.parameterHTML(arr,`data-person-raw="${esc(path)}"`,sub);return `<div class="character-array">${arr.map((v,i)=>`<div><span>${i+1}</span>${field(v,path+'.'+i,sub,ref)}<button data-person-remove="${esc(path+'.'+i)}" aria-label="删除此项">×</button></div>`).join('')}<button data-person-add="${esc(path)}" data-item-type="${esc(sub)}">＋ 添加一项</button></div>`;}if(ref){let rows=S.refs?.[ref]||{};if(ref==='ItemTagCfg')rows=Object.fromEntries(Object.entries(rows).filter(([id])=>Number(id)>=1&&Number(id)<=11));if(path.endsWith('.focusAttrId')){const range=S.data.tables.PersonGrowCfg.schema.fields.find(f=>f.name==='focusAttrId')?.range||{};rows=Object.fromEntries(Object.entries(rows).filter(([id,r])=>(!range.filter||range.filter.values.includes(r[range.filter.field]))&&!range.skips?.includes(Number(id))));}return `<select data-person-value="${esc(path)}" data-number><option value="0">未设置</option>${Object.values(rows).map(r=>`<option value="${r.id}" ${Number(value)===r.id?'selected':''}>${esc(r.name||r.title||'项目 '+r.id)}</option>`).join('')}${value&&!rows[value]?`<option selected value="${esc(value)}">未识别的原有记录（${esc(value)}）</option>`:''}</select>`;}return type==='string'?`<input data-person-value="${esc(path)}" value="${esc(value||'')}">`:`<input type="number" data-number data-person-value="${esc(path)}" value="${Number(value)||0}" step="${type==='int'?'1':'any'}">`;}
function renderList(){const ids=Object.keys(people()).filter(id=>StudentAgeSearch.matches(S.search,id,people()[id].name));S.page=Math.min(S.page,Math.max(0,Math.ceil(ids.length/50)-1));$('#character-list').innerHTML=ids.slice(S.page*50,S.page*50+50).map(id=>`<button data-person-select="${id}" class="${String(S.selected)===id?'active':''}"><strong>${StudentAgeRecordLabels.html(id,people()[id].name||'未命名人物')}</strong></button>`).join('')||'<p class="helper">尚未添加人物。</p>';$('#character-page').textContent=(S.page+1)+' / '+Math.max(1,Math.ceil(ids.length/50));}
function render(){host.className='character-workspace';host.innerHTML=`<div class="character-workspace-layout"><aside class="character-list-panel"><input id="character-search" placeholder="搜索人物名称或编号" value="${esc(S.search)}"><button data-person="new" class="primary" ${readonly()?'disabled':''}>＋ 添加角色</button><div id="character-list"></div><div class="character-pagination"><button data-person-page="-1">←</button><span id="character-page"></span><button data-person-page="1">→</button></div></aside><section class="character-content"><nav class="character-tabs">${[['profile','人物资料'],['growth','成长与喜好'],['faces','表情与服装'],['model','人物图片与大小']].map(([v,l])=>`<button data-person-tab="${v}" class="${S.tab===v?'active':''}">${l}</button>`).join('')}</nav><div id="character-form"></div></section><aside id="character-preview"></aside></div>`;renderList();renderForm();notify();}
function renderForm(){model.stop();host.classList.toggle('character-model-mode',S.tab==='model');if(S.tab==='model'){model.render();return;}const p=person(),form=$('#character-form');if(!p){form.innerHTML='<p class="helper">在左侧添加或选择角色。</p>';renderPreview();return;}const id=S.selected;let content='';
if(S.tab==='profile'){content=controls.social()+`<label>姓名<input data-person-value="PersonCfg.${id}.name" value="${esc(p.name||'')}"></label><div class="character-personal-row"><label>性别<button data-person="gender" aria-label="点击切换性别">${Number(p.gender)===2?'女':'男'}</button></label><label>生日<button data-person="birthday">${p.birthday?.length===3?esc(p.birthday[0]+' 年 '+p.birthday[1]+' 月 '+p.birthday[2]+' 日'):'选择生日'}</button></label></div><label>人物介绍<textarea rows="4" data-person-value="PersonCfg.${id}.introduction">${esc(p.introduction||'')}</textarea></label><div class="character-image-fields"><button data-person-media="portrait" data-grade="0">小学立绘 · 选择图片</button><button data-person-media="portrait" data-grade="1">中学立绘 · 选择图片</button></div><button data-person="avatar" class="character-avatar-button">${avatarMarkup(p)}<span>企鹅头像 · 更换</span></button><button data-person="space">设置企鹅空间</button><div class="character-contact-row"><label>电话号码<input data-person-value="PersonCfg.${id}.telephone" value="${esc(p.telephone||'')}"></label><label>普通昵称<input data-character-nickname="0" value="${esc(p.nicknames?.[0]||'')}"></label><label>恋爱昵称<input data-character-nickname="1" value="${esc(p.nicknames?.[1]||'')}"></label></div><label>备注<textarea data-person-value="PersonCfg.${id}.note">${esc(p.note||'')}</textarea></label>`+controls.romance();
}else if(S.tab==='growth'){const g=all('PersonGrowCfg')[id]||{...defaults('PersonGrowCfg'),ItemPref:[]};content=g?`<p class="helper">正在编辑 ${esc(p.name)} 的成长与喜好。</p>${S.data.tables.PersonGrowCfg.schema.fields.filter(f=>!['id','trait','speciality'].includes(f.name)).map(f=>`<label>${esc(labels[f.name]||f.label)}${controls.form(f,g)??field(g[f.name]??f.default,'PersonGrowCfg.'+id+'.'+f.name,f.type,references[f.name])}</label>`).join('')}<div class="character-traits-pair">${['trait','speciality'].map(key=>{const f=S.data.tables.PersonGrowCfg.schema.fields.find(f=>f.name===key);return f?`<label>${esc(labels[key])}${field(g[key]??f.default,'PersonGrowCfg.'+id+'.'+key,f.type,references[key])}</label>`:'';}).join('')}</div>`:'<p>这个角色尚未设置成长与喜好。</p><button data-person="growth-add" class="primary">添加成长与喜好</button>';
}else{const faces=Object.values(all('ModFaceCfg')).filter(f=>Math.floor(f.id/1000)===Number(id)&&Math.floor(f.id%1000/100)===S.cloth);if(!faces.some(f=>f.id===S.face))S.face=faces[0]?.id||null;const face=all('ModFaceCfg')[S.face];content=outfitEditor()+`<div class="character-image-heading"><h3>这套服装的立绘图片</h3><button data-person="image-add">＋ 添加立绘图片</button></div><div class="character-outfit-images">`+faces.map(f=>{const image=f[S.grade?'icon':'icon_xx']||f[S.grade?'icon_xx':'icon'];return `<button data-person-face="${f.id}" class="${S.face===f.id?'active':''}">${image?`<img src="${esc(imageURL(image))}" alt="${esc(f.name||'默认')}">`:'<span class="character-empty-image">选择图片</span>'}<strong>${esc(f.name||'表情 '+f.id%100)}</strong>${f.id%100===0?'<small>默认立绘</small>':''}</button>`;}).join('')+'</div>'+(face?`<label>这张立绘的表情名称<input data-person-value="ModFaceCfg.${face.id}.name" value="${esc(face.name||'')}"></label><div class="character-image-fields">${[0,1].map(g=>`<button data-person-media="expression" data-grade="${g}">${g?'中学':'小学'} · 更换图片</button>`).join('')}</div>${face.id%100?'<button data-person="image-delete">删除这张立绘</button>':''}`:'<p class="helper">添加第一张立绘后，它会成为这套服装的默认表情。</p>');}

form.innerHTML=`<div class="character-record-title"><h2>${StudentAgeRecordLabels.html(p.id,p.name||'未命名人物')}</h2><button data-record-table="PersonCfg" data-record-id="${p.id}" ${readonly()?'disabled':''}>ID ${p.id} · 修改</button></div><fieldset ${readonly()||S.busy?'disabled':''}>${content}</fieldset>`;renderPreview();}
function avatarMarkup(p){const a=all('KZoneAvatarCfg')[p.kzoneHeadId];return `<img src="${esc(a?.icon?imageURL(a.icon):headURL(p.id))}" alt="企鹅头像" loading="lazy">`;}
let previewSequence=0;
function outfitRows(){const p=person();if(!p)return [];const slots=new Set([0,...Object.keys(S.outfits[p.id]||{}).map(Number),...Object.values(all('ModFaceCfg')).filter(f=>Math.floor(f.id/1000)===p.id).map(f=>Math.floor(f.id%1000/100))]);return [...slots].sort((a,b)=>a-b).map(id=>({id,name:S.outfits[p.id]?.[id]?.name||(id?'服装 '+id:'默认服装')}));}
function outfitEditor(){return `<div class="character-outfit-list">${outfitRows().map(r=>`<button data-person-cloth="${r.id}" class="${S.cloth===r.id?'active':''}">${esc(r.name)}</button>`).join('')}</div><div class="character-image-fields"><button data-person="outfit-add" class="primary">＋ 加入该角色服装</button><button data-person="outfit-locations">设置穿着地点</button>${S.cloth?'<button data-person="outfit-delete">删除服装</button>':''}</div>`;}
function previewFaces(){const p=person(),rows=new Map([[0,{id:0,name:'默认'}]]);for(const f of Object.values(all('ModFaceCfg')))if(Math.floor(f.id/1000)===p.id&&Math.floor(f.id%1000/100)===S.cloth)rows.set(f.id%100,{id:f.id%100,name:f.name||StudentAgeExpressions.names[f.id%100]||'表情 '+f.id%100});const models=p[S.grade?'l2d2':'l2d']||[];if(models.length)for(const [id,name]of StudentAgeExpressions.names.entries())if(!rows.has(id))rows.set(id,{id,name});return [...rows.values()];}
function renderPreview(){const request=++previewSequence,node=$('#character-preview'),p=person();if(!p){node.innerHTML='';return;}if(!outfitRows().some(r=>r.id===S.cloth))S.cloth=0;const faces=previewFaces();if(!faces.some(f=>f.id===S.previewFace))S.previewFace=0;
 const face=all('ModFaceCfg')[p.id*1000+S.cloth*100+S.previewFace],base=all('ModFaceCfg')[p.id*1000+S.cloth*100],gradeKey=S.grade?'icon':'icon_xx',otherKey=S.grade?'icon_xx':'icon',path=face?.[gradeKey]||face?.[otherKey]||base?.[gradeKey]||base?.[otherKey]||p[S.grade?'url2':'url']?.[0]||p[S.grade?'url':'url2']?.[0],models=p[S.grade?'l2d2':'l2d']||[],model=models[Number(p.gender)===2&&models.length>1?1:0],native=model&&Object.values(S.data?.tables.PersonCfg.referenceRows||{}).find(r=>(r[S.grade?'l2d2':'l2d']||[]).includes(model)),nativeId=native?.id,src=path?imageURL(/^(Mods|Textures|StudentAgeStudio)[\\/]/i.test(path)?path:'role_full/'+path):native?imageURL(`portrait-cache/${nativeId}${nativeId===0&&Number(p.gender)===2?'-female':''}-${S.grade}-${S.cloth}-${S.previewFace}.png`):'';
 node.innerHTML=`<h3>立绘预览</h3><div class="character-filters"><button data-character-grade="0" class="${S.grade===0?'active':''}">小学</button><button data-character-grade="1" class="${S.grade===1?'active':''}">中学</button></div><button data-person-media="portrait" data-grade="${S.grade}" class="character-preview-image" ${readonly()?'disabled':''}>${src?`<img src="${esc(src)}" alt="${esc(p.name)}立绘">`:'<span>点击选择立绘</span>'}</button><p>${esc(p.name)}</p><div class="character-preview-options"><label>表情<select data-preview-face>${faces.map(r=>`<option value="${r.id}" ${S.previewFace===r.id?'selected':''}>${esc(r.name)}</option>`).join('')}</select></label><label>服装<select data-preview-cloth>${outfitRows().map(r=>`<option value="${r.id}" ${S.cloth===r.id?'selected':''}>${esc(r.name)}</option>`).join('')}</select></label></div><p class="character-preview-error" role="status"></p>`;
 const img=node.querySelector('img'),grade=S.grade,cloth=S.cloth,faceId=S.previewFace,gender=Number(p.gender)===2?2:1;if(img&&native&&!path){img.dataset.nativeRole=nativeId;let attempts=0;img.onerror=async()=>{if(request!==previewSequence||!img.isConnected)return;img.hidden=true;try{const result=await api('/api/portraits',{projectId:options.project.id,role:nativeId,grade,cloth,face:faceId,gender});if(request!==previewSequence||!img.isConnected)return;if(result.status==='ready'){img.onload=()=>img.hidden=false;img.src=src+'&v='+Date.now();}else if(result.status==='rendering'&&attempts++<60)setTimeout(()=>img.onerror(),1000);else node.querySelector('[role=status]').textContent=result.message||'立绘暂不可用。';}catch(error){if(request===previewSequence)node.querySelector('[role=status]').textContent=error.message;}};}
}
function assignOutfit(slot,value){S.outfits[S.selected]??={};for(const other of Object.values(S.outfits[S.selected]))other.backgrounds=(other.backgrounds||[]).filter(id=>!value.backgrounds.includes(id));S.outfits[S.selected][slot]=copy(value);}
async function setLocations(slot=S.cloth){const selected=S.selected,current=S.outfits[selected]?.[slot]||{name:slot?'服装 '+slot:'默认服装',backgrounds:[]},value=await UI.outfitLocations(S.data.places||[],current.backgrounds,current.name,slot===0);if(value&&S.selected===selected){change(()=>assignOutfit(slot,value));renderForm();}}
async function addOutfit(){const slot=Array.from({length:9},(_,i)=>i+1).find(id=>!outfitRows().some(r=>r.id===id));if(slot===undefined)throw Error('该角色已拥有九套附加服装。');await pickMedia('new-outfit',S.grade,slot);}
function pathValue(path,create=false){const parts=path.split('.'),field=parts.pop();if(parts.some(x=>['__proto__','constructor','prototype'].includes(x))||['__proto__','constructor','prototype'].includes(field))throw Error('字段无效');if(create&&parts.length>=2&&!S.tables[parts[0]][parts[1]])S.tables[parts[0]][parts[1]]=copy(all(parts[0])[parts[1]]||{...defaults(parts[0]),id:Number(parts[1])});const target=parts.reduce((o,k)=>o?.[k],S.tables);return {target,field,value:target?.[field]};}
async function pickMedia(kind,grade,slot=S.cloth){const selected=S.selected,faceId=S.face,result=await UI.media({mode:kind==='expression'?'expression':'portrait',projectId:options.project.id,revision:()=>S.revision});if(!result)return;S.revision=result.revision;notify();if(S.selected!==selected)return;let location=null;
 if(kind!=='expression'){const current=S.outfits[selected]?.[slot]||{name:slot?'服装 '+slot:'默认服装',backgrounds:[]};location=await UI.outfitLocations(S.data.places||[],current.backgrounds,current.name,slot===0);if(!location||S.selected!==selected)return;}
 change(()=>{const url=result.url||result.assetPath,p=person();if(kind==='expression'){if(!faceId)throw Error('请先选择表情。');S.tables.ModFaceCfg[faceId]=copy(all('ModFaceCfg')[faceId]||{id:faceId,name:StudentAgeExpressions.names[faceId%100]||'表情 '+faceId%100,icon:'',icon_xx:'',photobooth:''});S.tables.ModFaceCfg[faceId][grade?'icon':'icon_xx']=url;p[grade?'l2d2':'l2d']=[];S.previewFace=faceId%100;}else{assignOutfit(slot,location);const id=p.id*1000+slot*100,old=all('ModFaceCfg')[id];S.tables.ModFaceCfg[id]={id,name:'默认',icon:url,icon_xx:url,photobooth:'',...copy(old||{}),[grade?'icon':'icon_xx']:url};if(slot>0){p.l2d=[];p.l2d2=[];if(!p.url?.length)p.url=p.url2?.length?copy(p.url2):[url];if(!p.url2?.length)p.url2=copy(p.url);S.outfits[selected][0]??={name:'默认服装',backgrounds:[]};}if(slot===0){const key=grade?'url2':'url';p[key]=[url,...(p[key]||[]).slice(1)];p[grade?'l2d2':'l2d']=[];}S.cloth=slot;S.previewFace=0;S.face=id;}});S.grade=grade;renderForm();}
async function addOutfitImage(){const selected=S.selected,slot=S.cloth,grade=S.grade,result=await UI.media({mode:'expression',title:'选择立绘图片',projectId:options.project.id,revision:()=>S.revision});if(!result)return;S.revision=result.revision;notify();if(S.selected!==selected||S.cloth!==slot)return;
 const taken=new Set(Object.keys(all('ModFaceCfg')).filter(id=>Math.floor(Number(id)/1000)===Number(selected)&&Math.floor(Number(id)%1000/100)===slot).map(id=>Number(id)%100));let face=taken.has(0)?Array.from({length:99},(_,i)=>i+1).find(n=>!taken.has(n)):0;if(face===undefined)throw Error('这套服装最多支持 100 张表情立绘。');
 const sourceFace=Number(result.item?.previewFace);if(face!==0&&sourceFace>0&&sourceFace<100&&!taken.has(sourceFace))face=sourceFace;
 const sourceName=result.item?.expressionName,name=face===0?'默认':sourceName&&sourceName!=='默认'?sourceName:'表情 '+face,url=result.url||result.assetPath;
 change(()=>{const id=Number(selected)*1000+slot*100+face;S.tables.ModFaceCfg[id]={id,name,icon:url,icon_xx:url,photobooth:''};S.face=id;S.previewFace=face;person()[grade?'l2d2':'l2d']=[];S.outfits[selected]??={};S.outfits[selected][slot]??={name:slot?'服装 '+slot:'默认服装',backgrounds:[]};if(face===0&&slot===0){const p=person();p[grade?'url2':'url']=[url];p[grade?'l2d2':'l2d']=[];}});renderForm();
}
const imageInput=document.createElement('input');imageInput.type='file';imageInput.accept='image/png,image/jpeg,image/webp,image/bmp,image/x-tga,.bmp,.tga';imageInput.id='character-avatar-file';imageInput.hidden=true;document.body.append(imageInput);
async function pickAvatar(){const rows=[{id:0,name:'使用人物大头照'},...Object.values(all('KZoneAvatarCfg')).map(r=>({...r,name:r.name||'头像 '+r.id}))],selected=S.selected;const choice=await UI.choices('选择企鹅头像',rows,{selected:person().kzoneHeadId,image:r=>r.icon?imageURL(r.icon):headURL(person().id),extra:()=>imageInput.click()});if(choice&&S.selected===selected){change(()=>setAvatar(choice.id));renderForm();}}
function setAvatar(id){person().kzoneHeadId=id;const profile=all('KZoneProfileCfg')[S.selected];if(profile)S.tables.KZoneProfileCfg[S.selected]={...copy(profile),icon:id};}
imageInput.onchange=async()=>{const file=imageInput.files[0];imageInput.value='';if(!file||readonly())return;const selected=S.selected;S.busy=true;notify();try{if(file.size>24*1024*1024)throw Error('头像图片需小于 24 MB。');const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(file);});const result=await api('/api/image-import',{projectId:options.project.id,revision:S.revision,fileName:file.name,data});S.revision=result.revision;S.busy=false;if(S.selected!==selected)return;change(()=>{const id=STUDIO_IDS.allocate('KZoneAvatarCfg',all('KZoneAvatarCfg'));S.tables.KZoneAvatarCfg[id]={id,type:0,state:0,name:file.name,icon:result.url};setAvatar(id);});renderForm();}catch(e){options.status(e.message,true);}finally{S.busy=false;notify();}};
function setGift(id,value){if(!Number.isInteger(value)||value>2147483647||value<-2147483648)throw Error('喜好数值需要填写整数。');change(()=>{const p=pathValue('PersonGrowCfg.'+S.selected+'.ItemPref',true),rows=p.target[p.field]||[];p.target[p.field]=rows.filter(row=>Number(row[0])!==id).concat([[id,value]]).sort((a,b)=>a[0]-b[0]);},'gift-'+id);}
async function action(e){const b=e.target.closest('button');if(!b||b.disabled||S.busy)return;if(b.dataset.personSelect){S.selected=b.dataset.personSelect;S.face=null;S.cloth=0;S.previewFace=0;S.last=null;renderList();renderForm();notify();return;}if(b.dataset.personTab){S.tab=b.dataset.personTab;render();return;}if(b.dataset.characterGrade!==undefined){S.grade=Number(b.dataset.characterGrade);renderPreview();return;}if(b.dataset.personPage){S.page=Math.max(0,S.page+Number(b.dataset.personPage));renderList();return;}if(b.dataset.personCloth!==undefined){S.cloth=Number(b.dataset.personCloth);S.face=null;S.previewFace=0;renderForm();return;}if(b.dataset.personFace){S.face=Number(b.dataset.personFace);S.previewFace=S.face%100;renderForm();return;}if(readonly())return;if(await controls.click(b))return;if(b.dataset.giftStep){const id=Number(b.dataset.giftId),v=all('PersonGrowCfg')[S.selected]?.ItemPref?.find(r=>Number(r[0])===id)?.[1]||0;setGift(id,v+Number(b.dataset.giftStep));renderForm();return;}if(b.dataset.personMedia){let kind=b.dataset.personMedia;if(b.closest('#character-preview')&&S.previewFace>0){S.face=Number(S.selected)*1000+S.cloth*100+S.previewFace;kind='expression';}await pickMedia(kind,Number(b.dataset.grade));return;}if(b.dataset.personCloth!==undefined){S.cloth=Number(b.dataset.personCloth);S.face=null;S.previewFace=0;renderForm();return;}if(b.dataset.personFace){S.face=Number(b.dataset.personFace);S.previewFace=S.face%100;renderForm();return;}if(b.dataset.personRemove){change(()=>{const p=pathValue(b.dataset.personRemove,true);p.target.splice(Number(p.field),1);});renderForm();return;}if(b.dataset.personAdd){change(()=>{const p=pathValue(b.dataset.personAdd,true);p.target[p.field]??=[];p.target[p.field].push(b.dataset.personAdd.endsWith('.ItemPref')?[1,0]:b.dataset.itemType.startsWith('list')?[]:b.dataset.itemType==='string'?'':0);});renderForm();return;}
 const key=b.dataset.person;if(key==='outfit-add')await addOutfit();if(key==='outfit-locations')await setLocations();if(key==='outfit-delete'&&S.cloth){change(()=>{delete S.outfits[S.selected]?.[S.cloth];for(const k of Object.keys(S.tables.ModFaceCfg))if(Math.floor(Number(k)/1000)===Number(S.selected)&&Math.floor(Number(k)%1000/100)===S.cloth)delete S.tables.ModFaceCfg[k];});S.cloth=0;S.face=null;S.previewFace=0;renderForm();}if(key==='new')newPerson();if(key==='gender'){change(()=>person().gender=Number(person().gender)===2?1:2);renderForm();}if(key==='birthday'){const value=await UI.calendar(person().birthday);if(value){change(()=>person().birthday=value);renderForm();}}if(key==='avatar')await pickAvatar();if(key==='space')await options.openSpace(Number(S.selected));if(key==='growth-add'){change(()=>S.tables.PersonGrowCfg[S.selected]={...defaults('PersonGrowCfg'),id:Number(S.selected)});renderForm();}if(key==='image-add')await addOutfitImage();if(key==='image-delete'){change(()=>{delete S.tables.ModFaceCfg[S.face];});S.face=null;renderForm();}}
host.addEventListener('click',e=>{if(e.target.closest('button')){e.preventDefault();action(e).catch(err=>options.status(err.message,true));}});
function handleInput(e){const el=e.target;if(e.isComposing)return;if(!readonly()&&!S.busy&&controls.input(el))return;if(el.dataset.personRaw&&!readonly()&&!S.busy){const result=StudentAgeConditions.readParameterInput(el);if(!result.error)change(()=>{const p=pathValue(el.dataset.personRaw,true);p.target[p.field]=result.values;},el.dataset.personRaw);notify();return;}if(el.dataset.giftId&&!readonly()&&!S.busy){try{if(!el.value.trim())throw Error('请填写喜好数值。');setGift(Number(el.dataset.giftId),Number(el.value));el.setCustomValidity('');el.removeAttribute('aria-invalid');}catch(err){el.setCustomValidity(err.message);el.setAttribute('aria-invalid','true');options.status(err.message,true);}return;}if(el.id==='character-search'){S.search=el.value;S.page=0;renderList();return;}if(el.hasAttribute('data-preview-face')){S.previewFace=Number(el.value);const face=Number(S.selected)*1000+S.cloth*100+S.previewFace;if(all('ModFaceCfg')[face])S.face=face;S.tab==='faces'?renderForm():renderPreview();return;}if(el.hasAttribute('data-preview-cloth')){S.cloth=Number(el.value);S.face=null;S.previewFace=0;renderForm();return;}if(el.hasAttribute('data-person-aliases')&&!readonly()&&!S.busy){if(e.isComposing)return;const raw=el.value.replace(/，/g,',');el.value=raw;change(()=>person().nicknames=[...new Set(raw.split(',').map(s=>s.trim()).filter(Boolean))],'aliases');return;}if(!el.dataset.personValue||readonly()||S.busy)return;try{const value=el.hasAttribute('data-number')?Number(el.value):el.value;if(typeof value==='number'&&!Number.isFinite(value))return;change(()=>{const p=pathValue(el.dataset.personValue,true);p.target[p.field]=value;},el.dataset.personValue);renderList();if(el.dataset.personValue.endsWith('.name'))$('.character-record-title h2').innerHTML=StudentAgeRecordLabels.html(person().id,person().name);renderPreview();}catch(err){options.status(err.message,true);}}
host.addEventListener('input',handleInput);host.addEventListener('compositionend',e=>{handleInput(e);});host.addEventListener('change',e=>{if(e.target.tagName==='SELECT')handleInput(e);});
let menu=null;function closeMenu(){menu?.remove();menu=null;}
host.addEventListener('contextmenu',e=>{const row=e.target.closest('[data-person-select]');if(!row||readonly())return;e.preventDefault();S.selected=row.dataset.personSelect;renderList();renderForm();closeMenu();menu=document.createElement('div');menu.className='character-context';menu.innerHTML='<button data-copy-person>创建副本</button><button data-delete-person>删除角色</button>';menu.style.left=Math.min(e.clientX,innerWidth-180)+'px';menu.style.top=Math.min(e.clientY,innerHeight-110)+'px';document.body.append(menu);menu.onclick=e=>{if(e.target.closest('[data-copy-person]'))newPerson(true);if(e.target.closest('[data-delete-person]'))removePerson();closeMenu();};});
const outside=e=>{if(menu&&!menu.contains(e.target))closeMenu();};document.addEventListener('pointerdown',outside);const escapeMenu=e=>{if(e.key==='Escape')closeMenu();};document.addEventListener('keydown',escapeMenu);host.addEventListener('error',e=>{if(e.target.tagName==='IMG'&&!e.target.hasAttribute('data-native-role')){e.target.hidden=true;e.target.parentElement.classList.add('image-unavailable');}},true);
async function save(){const invalid=host.querySelector('[aria-invalid="true"]');if(invalid){invalid.focus();if(!await STUDIO_SAVE_REVIEW.confirm(['部分参数输入尚未完成。继续将保存已生效的内容，未能解析的输入沿用上一次有效值。']))return;}if(readonly())throw Error('订阅模组只能查看，请先创建副本。');if(!dirty())return;if(S.busy)throw Error('请等待图片读取完成。');S.busy=true;notify();try{const result=await api('/api/characters-save',{projectId:options.project.id,revision:S.revision,tables:copy(S.tables),outfits:copy(S.outfits),romance:copy(S.romance)});S.tables=result.tables;S.outfits=result.outfits||{};S.romance=result.romance||{};S.revision=result.revision;S.saved=snapshot();S.undo=[];S.redo=[];S.last=null;await options.onSaved?.(result);options.status('人物资料、成长、服装立绘与头像已一起保存。');render();}finally{S.busy=false;notify();}}
const premiseRemoved=e=>{if(options.project.id!==e.detail.projectId)return;const pairs=new Set(e.detail.pairs);window.STUDIO_STRIP_PREMISES(S.tables,pairs);window.STUDIO_STRIP_PREMISES(S.romance,pairs);S.revision=e.detail.revision;S.saved=snapshot();render();notify();};window.addEventListener('studio-premises-removed',premiseRemoved);const onPremiseCreated=e=>{if(options.project.id===e.detail.projectId&&S.revision===e.detail.previousRevision){S.revision=e.detail.revision;notify();}};window.addEventListener('studio-premise-created',onPremiseCreated);
 async function load(){S.busy=true;notify();try{S.data=await api('/api/characters?'+new URLSearchParams({projectId:options.project.id}));S.revision=S.data.revision;S.outfits=copy(S.data.outfits||{});S.romance=copy(S.data.romance||{});for(const table of tables)S.tables[table]=copy(S.data.tables[table].localRows);S.refs={};await Promise.all([...new Set([...Object.values(references),'ItemTagCfg','BookCfg'])].map(async n=>{S.refs[n]=(await api('/api/table?'+new URLSearchParams({projectId:options.project.id,name:n}))).rows;}));S.saved=snapshot();S.selected=Object.keys(people())[0]||null;render();}finally{S.busy=false;notify();}}
return {jsonRead:name=>{const path={"PersonCfg": ["tables", "PersonCfg"], "PersonGrowCfg": ["tables", "PersonGrowCfg"], "ModFaceCfg": ["tables", "ModFaceCfg"], "KZoneAvatarCfg": ["tables", "KZoneAvatarCfg"], "KZoneProfileCfg": ["tables", "KZoneProfileCfg"]}[name];if(!path||!S.data)return null;return path.reduce((v,k)=>v?.[k],JSON.parse(snapshot()));},
 jsonWrite(name,rows){const path={"PersonCfg": ["tables", "PersonCfg"], "PersonGrowCfg": ["tables", "PersonGrowCfg"], "ModFaceCfg": ["tables", "ModFaceCfg"], "KZoneAvatarCfg": ["tables", "KZoneAvatarCfg"], "KZoneProfileCfg": ["tables", "KZoneProfileCfg"]}[name];if(!path)return false;if(readonly()||S.busy)throw Error('当前页面暂不可编辑。');const data=JSON.parse(snapshot());let parent=data;for(const k of path.slice(0,-1))parent=parent[k];if(JSON.stringify(parent[path.at(-1)])===JSON.stringify(rows))return true;S.undo.push(snapshot());if(S.undo.length>60)S.undo.shift();S.redo=[];parent[path.at(-1)]=structuredClone(rows);restore(JSON.stringify(data));notify();return true;},
 jsonSaved(name,rows,revision){const path={"PersonCfg": ["tables", "PersonCfg"], "PersonGrowCfg": ["tables", "PersonGrowCfg"], "ModFaceCfg": ["tables", "ModFaceCfg"], "KZoneAvatarCfg": ["tables", "KZoneAvatarCfg"], "KZoneProfileCfg": ["tables", "KZoneProfileCfg"]}[name];if(!path)return;const data=JSON.parse(S.saved);let parent=data;for(const k of path.slice(0,-1))parent=parent[k];parent[path.at(-1)]=structuredClone(rows);S.saved=JSON.stringify(data);S.revision=revision;notify();},load,save,dirty,snapshot,state:S,undo:()=>history('undo','redo'),redo:()=>history('redo','undo'),delete:removePerson,discard(){restore(S.saved);S.undo=[];S.redo=[];notify();},destroy(){model.stop();window.removeEventListener('studio-premise-created',onPremiseCreated);window.removeEventListener('studio-premises-removed',premiseRemoved);previewSequence++;closeMenu();imageInput.remove();document.removeEventListener('pointerdown',outside);document.removeEventListener('keydown',escapeMenu);},navigation:{capture:()=>({selected:S.selected,tab:S.tab,face:S.face,cloth:S.cloth,previewFace:S.previewFace,grade:S.grade,search:S.search,page:S.page}),restore:v=>{Object.assign(S,{selected:people()[v.selected]?v.selected:Object.keys(people())[0]||null,tab:v.tab||'profile',face:v.face,cloth:v.cloth??0,previewFace:v.previewFace??0,grade:v.grade??1,search:v.search||'',page:v.page||0});render();}},focusSearch:()=>$('#character-search')?.focus(),test:{newPerson,removePerson,pickAvatar,pickMedia,addOutfit,setLocations,addOutfitImage}};
}
window.StudentAgeCharacters={create};
})();
