(() => {
'use strict';
const C=window.StudentAgeConditions,esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),copy=v=>JSON.parse(JSON.stringify(v)),plain=v=>String(v??'').replace(/<\/?(?:color|size|b|i|u|s|sup|sub|font|material|align|link|sprite)(?:=[^>]*)?>/gi,''),name=r=>plain(r?.name||r?.title||r?.content||r?.id||'未设置');
function open(options={}){
 const projectId=options.projectId||window.STUDIO_CURRENT_PROJECT?.();if(!projectId)return Promise.resolve(null);
 return new Promise(resolve=>{
 const templates=[...(options.templates||[])],refs={...(options.refs||{})},localIds=options.localIds||{},dialog=document.createElement('dialog');dialog.className='condition-library condition-browser';dialog.setAttribute('aria-label','条件目录');document.body.append(dialog);
 let draft=copy(options.rows||[]),mode='conditions',configSource='mod',presetEntries=[],presetsLoaded=false,presetBusy=false,category=options.category||'全部',query='',page=0,closed=false,timer=null,entries=[],modEntries=[],modId='all',modLoaded=false,modWarning='',loadSequence=0,status='正在读取原版已有条件…',originalCache=null;const abort=new AbortController(),sampleVariants=new Map();
 const hash=location.hash.slice(1),token=window.STUDIO_TOKEN&&window.STUDIO_TOKEN!=='__STUDIO_TOKEN__'?window.STUDIO_TOKEN:(hash.startsWith('token=')?hash.slice(6):hash);
 async function api(path,payload){const response=await fetch('/api/'+path,{method:payload===undefined?'GET':'POST',headers:{'X-Studio-Token':token,'Content-Type':'application/json'},body:payload===undefined?undefined:JSON.stringify(payload),signal:abort.signal});const data=await response.json();if(!response.ok||data.error)throw Error(data.error||'读取失败');return data;}
 const hasErrors=()=>!!dialog.querySelector('[aria-invalid="true"]');
 function finish(value){if(closed||presetBusy)return;if(value){for(const input of dialog.querySelectorAll('[data-library-raw]')){const result=C.readCommandInput(input);if(!result.error&&result.values.length<2){input.setAttribute('aria-invalid','true');input.parentElement.querySelector('.command-input-error').textContent='请填写完整条件，至少包含条件类型和判断方式。';}}}if(value&&hasErrors()){dialog.querySelector('[aria-invalid="true"]').focus();return;}closed=true;window.removeEventListener('studio-premises-removed',premisesRemoved);clearTimeout(timer);abort.abort();dialog.close();dialog.remove();resolve(value);}
 const premisesRemoved=event=>{if(event.detail.projectId!==projectId)return;const pairs=new Set(event.detail.pairs),matches=row=>Array.isArray(row)&&[50,111].includes(Number(row[0]))&&pairs.has(Number(row[2])+':'+Number(row[3]));draft=draft.filter(row=>!matches(row));templates.splice(0,templates.length,...templates.filter(t=>!matches(t.template)));for(const list of [entries,modEntries,presetEntries])for(const entry of list){if(entry.rows)entry.rows=entry.rows.filter(row=>!matches(row));if(entry.premises)entry.premises=entry.premises.filter(p=>!pairs.has(p.eventId+':'+p.slot));}originalCache=null;renderCatalogue();renderSelected();};window.addEventListener('studio-premises-removed',premisesRemoved);
 dialog.innerHTML=`<header><div><h2>条件目录</h2><p>点击左侧添加，在右侧编辑。多条条件需要全部满足。</p></div><button data-library-close aria-label="取消并关闭">×</button></header><div class="condition-browser-layout"><section class="condition-browser-catalog"><nav aria-label="条件与配置"><button data-library-mode="conditions">条件</button><button data-library-mode="configs">条件配置</button></nav><nav class="condition-config-filter" aria-label="配置来源" hidden><button data-library-config="mod">模组配置</button><button data-library-config="user">用户配置</button></nav><div class="condition-mod-filter" hidden><label>模组 <select data-library-mod><option value="all">全部模组</option>${(window.STUDIO_PROJECTS?.()||[]).map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('')}</select></label></div><nav class="condition-category-filter" aria-label="条件分类"></nav><div class="condition-preset-save" hidden><input data-preset-name type="text" maxlength="120" placeholder="配置名称（可选）" aria-label="条件配置名称"><button data-preset-save>保存当前配置</button></div><input type="search" class="condition-library-search" placeholder="搜索条件、名称或拼音" aria-label="搜索条件"><p class="condition-library-status" role="status"></p><section class="condition-library-results"></section><footer><button data-library-page="-1">上一页</button><span class="condition-library-page"></span><button data-library-page="1">下一页</button></footer></section><aside class="condition-browser-selected"><h3>已添加条件 <span data-selected-count></span></h3><div class="condition-selected-list"></div></aside></div><footer class="condition-browser-actions"><span>完成后应用，可在编辑界面撤销。</span><button data-library-cancel>取消</button><button class="primary" data-library-apply>完成</button></footer>`;
 dialog.addEventListener('contextmenu',event=>{const button=event.target.closest('[data-library-key]');if(!button||options.readOnly)return;const entry=catalogue().find(e=>e.key===button.dataset.libraryKey),row=entry?.rows?.[0];if(!row||Number(row[0])!==111)return;window.StudentAgeContextMenu(event,'删除前提',async()=>{if(!await window.STUDIO_DELETE_PREMISE(row))return;const pair=Number(row[2])+':'+Number(row[3]);draft=window.STUDIO_STRIP_PREMISES(draft,new Set([pair]));for(let i=templates.length-1;i>=0;i--)if(Number(templates[i].template?.[0])===111&&Number(templates[i].template[2])+':'+Number(templates[i].template[3])===pair)templates.splice(i,1);entries=entries.filter(e=>!e.rows?.some(r=>Number(r[0])===111&&Number(r[2])+':'+Number(r[3])===pair));originalCache=null;renderCatalogue();renderSelected();});});
 if(!templates.some(t=>Number(t.template?.[0])===7&&Number(t.template?.[1])===0))templates.unshift({label:'人物关系',template:[7,0,0,1],match:{0:7,1:0},parameters:[{index:2,label:'与谁',type:'int',range:{table:'PersonCfg'}},{index:3,label:'关系是',type:'int',range:{table:'OtherRelationCfg'}}]});
 Promise.all(['PersonCfg','OtherRelationCfg'].map(async table=>{const data=await api('table?'+new URLSearchParams({projectId,name:table}));refs[table]={...(table==='OtherRelationCfg'?window.StudentAgeCommandTypes.otherRelations():{}),...data.rows,...refs[table]};})).then(()=>{if(!closed){originalCache=null;renderCatalogue();renderSelected();}}).catch(e=>message(e.message));
 const getTemplate=row=>templates.find(t=>C.family(t.template,t).key.startsWith('premise:')&&C.match(row,t))||templates.find(t=>C.match(row,t));
 function family(row){return C.family(row,getTemplate(row));}
 function titleFor(row){if(row.length<2)return '自定义条件';const f=family(row);if(f.key==='attribute')return name(refs.PersonAttrCfg?.[row[2]])||'属性数值';if(f.key==='favor')return (refs.PersonCfg?.[row[2]]?name(refs.PersonCfg[row[2]]):'人物')+'好感度';if(f.title==='自定义条件')return refs.ConditionTypeCfg?.[row[0]]?name(refs.ConditionTypeCfg[row[0]])+'条件':'自定义条件';return f.title;}
 function variants(row){const f=family(row);return templates.filter(t=>C.family(t.template,t).key===f.key);}
 function catalogue(){
  if(mode==='configs')return configSource==='mod'?modEntries.filter(e=>modId==='all'||e.projectId===modId):presetEntries;
  if(originalCache)return originalCache;
  const groups=new Map();
  for(const t of templates){const f=C.family(t.template,t);if(!groups.has(f.key))groups.set(f.key,{key:f.key,title:f.title,category:f.category,rows:[f.key.startsWith('premise:')?[111,1,t.template[2],t.template[3],1]:f.key.startsWith('premise-talk:')?[3,3,Number(t.template[2])]:copy(t.template)]});}
  // Numeric comparisons are a single entry per attribute, regardless of operator.
  groups.delete('attribute');for(const r of Object.values(refs.PersonAttrCfg||{})){groups.set('attr:'+r.id,{key:'attr:'+r.id,title:name(r),category:'数值',rows:[[4,9005,Number(r.id),0]]});}
  if(groups.has('favor'))groups.get('favor').rows[0]=[7,9005,Number(Object.keys(refs.PersonCfg||{})[0]||3),0];
  // Every observed native rule remains reachable. Unknown rules share a family
  // entry and offer their exact original usages on the right without guessing.
  sampleVariants.clear();
  for(const e of entries.filter(e=>e.origin!=='named'))for(const row of e.rows){if(getTemplate(row))continue;const key='observed:'+row[0],list=sampleVariants.get(Number(row[0]))||[];if(!list.some(v=>JSON.stringify(v.row)===JSON.stringify(row)))list.push({row,title:e.title});sampleVariants.set(Number(row[0]),list);if(!groups.has(key))groups.set(key,{key,title:(refs.ConditionTypeCfg?.[row[0]]?name(refs.ConditionTypeCfg[row[0]]):'原版特殊判断 '+row[0])+' · 其他用法',rows:[row],category:C.categoryOf([row],templates),observed:true});}
  originalCache=[...groups.values()].sort((a,b)=>(b.key==='relationship')-(a.key==='relationship'));return originalCache;
 }
 function renderCatalogue(){
  const all=catalogue();const CT=window.StudentAgeCommandTypes,categoryFor=CT.foldSingles(all,e=>CT.conditionCategory(e.rows[0],refs));
  // Categories follow the game's own ConditionTypeCfg (first row of each entry), in that table's order.
  const nav=dialog.querySelector('.condition-category-filter'),names=['全部',...CT.categoryOrder('ConditionTypeCfg',all.map(categoryFor),refs)];if(!names.includes(category))category='全部';if(nav.dataset.keys!==names.join('|')){nav.dataset.keys=names.join('|');nav.innerHTML=names.map(v=>`<button data-library-category="${esc(v)}">${esc(v)}</button>`).join('');}
  let filtered=all.filter(e=>(mode==='configs'||category==='全部'||categoryFor(e)===category)&&(!query||StudentAgeSearch.matches(query,e.title,e.projectName,...e.rows.flat())));if(!filtered.length&&query&&mode==='conditions')filtered=entries.filter(e=>e.origin==='original'&&(category==='全部'||categoryFor(e)===category)&&StudentAgeSearch.matches(query,e.title)).map(e=>({...e,title:e.title+' · 已有组合'}));const pages=Math.max(1,Math.ceil(filtered.length/24));page=Math.min(page,pages-1);const visible=filtered.slice(page*24,(page+1)*24);
  dialog.querySelectorAll('[data-library-mode]').forEach(b=>b.classList.toggle('active',b.dataset.libraryMode===mode));dialog.querySelectorAll('[data-library-config]').forEach(b=>b.classList.toggle('active',b.dataset.libraryConfig===configSource));dialog.querySelectorAll('[data-library-category]').forEach(b=>b.classList.toggle('active',b.dataset.libraryCategory===category));
  dialog.querySelector('.condition-category-filter').hidden=mode!=='conditions';dialog.querySelector('.condition-config-filter').hidden=mode!=='configs';dialog.querySelector('.condition-mod-filter').hidden=mode!=='configs'||configSource!=='mod';dialog.querySelector('.condition-preset-save').hidden=mode!=='configs'||configSource!=='user';dialog.querySelector('[data-preset-save]').disabled=presetBusy||options.readOnly;
  dialog.querySelector('.condition-library-results').innerHTML=visible.map((e,i)=>`<div class="condition-library-tile"><button class="condition-library-entry" data-library-entry="${i}" data-library-key="${esc(e.key)}"><strong>${esc(plain(e.title))}<span aria-hidden="true">＋</span></strong><small>${mode==='configs'?e.rows.length+' 条条件':esc(e.category||C.categoryOf(e.rows,templates))}${e.projectName?' · '+esc(e.projectName):''}</small></button>${mode==='configs'&&configSource==='user'?`<button class="danger-text" data-preset-delete="${esc(e.key)}" aria-label="删除配置 ${esc(e.title)}">删除配置</button>`:''}</div>`).join('')+(mode==='conditions'?`<button class="condition-library-entry condition-custom-entry" data-library-custom><strong>自定义条件 <span>＋</span></strong><small>用逗号输入完整参数</small></button>`:'');
  dialog.querySelector('.condition-library-results').onclick=async event=>{if(options.readOnly||presetBusy||hasErrors())return;const custom=event.target.closest('[data-library-custom]');if(custom){draft.push([0]);renderSelected();return;}const button=event.target.closest('[data-library-entry]');if(!button)return;const e=visible[Number(button.dataset.libraryEntry)];if(!e)return;rememberPremises(e.premises||[]);draft.push(...copy(e.rows));renderSelected();
   if(e.projectId){const required=new Set(e.rows.flatMap(r=>(getTemplate(r)?.parameters||[]).map(p=>p.range?.table).filter(Boolean)));try{const loaded=await Promise.all([...required].map(async table=>[table,(await api('table?projectId='+encodeURIComponent(e.projectId)+'&name='+encodeURIComponent(table))).rows]));if(closed)return;for(const [table,rows] of loaded)refs[table]={...rows,...refs[table]};originalCache=null;if(!dialog.querySelector('.condition-selected-list').contains(document.activeElement))renderSelected();}catch(error){if(!closed)message('条件已添加，引用名称未读到：'+error.message);}}
  };
  dialog.querySelector('.condition-library-page').textContent=`${filtered.length} 项 · ${page+1} / ${pages}`;dialog.querySelector('[data-library-page="-1"]').disabled=page===0;dialog.querySelector('[data-library-page="1"]').disabled=page>=pages-1;message(mode==='conditions'?status:configSource==='mod'?(modLoaded?(modWarning||'点击配置，将整组条件加入右侧。'):'正在读取模组配置…'):(presetsLoaded?'点击配置引用；保存当前配置会保存右侧全部条件。':'正在读取用户配置…'));
 }
 function message(value){dialog.querySelector('.condition-library-status').textContent=value;}
 function referenceOptions(p,value){const table=refs[p.range?.table]||{},rows=Object.values(table).filter(r=>(!p.range.startId||Number(r.id)>=p.range.startId)&&(!p.range.endId||Number(r.id)<=p.range.endId));return (!rows.some(r=>Number(r.id)===Number(value))?`<option value="${esc(value)}" selected>${Number(value)===0?'未设置':'编号 '+esc(value)}</option>`:'')+rows.map(r=>`<option value="${esc(r.id)}" ${Number(r.id)===Number(value)?'selected':''}>${esc(name(r))}</option>`).join('');}
 function field(p,value,index){const attr=`data-library-param="${p.index}" data-library-row="${index}"`,body=p.choices?.length?`<select ${attr}>${p.choices.map(v=>`<option value="${v.id}" ${Number(v.id)===Number(value)?'selected':''}>${esc(v.label)}</option>`).join('')}</select>`:p.range?.table?`<select data-reference-table="${esc(p.range.table)}" ${attr} aria-label="${esc(p.label)}">${referenceOptions(p,value)}</select>`:`<input type="number" ${attr} value="${esc(value)}" step="${/int|long/.test(p.type||'')?'1':'any'}" ${p.min!==undefined?`min="${p.min}"`:''} ${p.max!==undefined?`max="${p.max}"`:''}>`;return `<label class="condition-browser-field"><span>${esc(p.label||'数值')}</span>${body}</label>`;}
 function renderSelected(){
  const list=dialog.querySelector('.condition-selected-list'),scroll=list.scrollTop;dialog.querySelector('[data-selected-count]').textContent=draft.length+' 项';
  list.innerHTML=draft.map((row,index)=>{const t=getTemplate(row),f=family(row),n=f.key.startsWith('premise:')?null:C.numeric(row),vs=variants(row);let body='';
   if(t||n){const params=t?.parameters||[];
    if(f.key.startsWith('premise:')){body=`<button class="condition-premise-toggle" data-library-premise="${index}" aria-label="切换前提达成状态">${Number(row[1])===1?'已达成':'未达成'}</button>`;}else if(n){body=params.filter(p=>p.index!==n.valueIndex&&p.index!==n.upperIndex).map(p=>field(p,row[p.index],index)).join('');const vp=params.find(p=>p.index===n.valueIndex)||{index:n.valueIndex,label:'数值',type:['age','grade','year','mood','round'].includes(f.key)?'int':'float'};body+=`<div class="condition-comparison"><button data-library-operator="${index}" title="点击切换比较方式" aria-label="切换比较方式">${esc(n.op)}</button>${field({...vp,label:n.op==='范围'?'下限':({age:'年龄',grade:'年级',year:'年份',mood:'等级',round:'回合'})[f.key]||'数值'},row[n.valueIndex],index)}${n.op==='范围'?field(params.find(p=>p.index===n.upperIndex)||{index:n.upperIndex,label:'上限',type:vp.type},row[n.upperIndex],index):''}</div>`;if(['age','grade','mood','record'].includes(f.key))body+=`<small class="condition-native-hint">支持 ${n.ops.join('、')}，按原版规则判断。</small>`;
    }else{body=(vs.length>1?`<label class="condition-browser-field"><span>判断方式</span><select data-library-variant="${index}">${vs.map((v,i)=>`<option value="${i}" ${v===t?'selected':''}>${esc(v.label)}</option>`).join('')}</select></label>`:'')+params.map(p=>field(p,row[p.index],index)).join('');}
   }else{const uses=sampleVariants.get(Number(row[0]))||[];body=(uses.length?`<label class="condition-browser-field"><span>原版用法</span><select data-library-sample="${index}">${uses.map((v,i)=>`<option value="${i}" ${JSON.stringify(v.row)===JSON.stringify(row)?'selected':''}>${esc(plain(v.title))} · ${esc(v.row.join(','))}</option>`).join('')}</select></label>`:'')+C.rawCommandHTML(row,`data-library-raw="${index}"`);}
   return `<article class="condition-selected-card"><header><strong>${index+1}. ${esc(titleFor(row))}</strong><button data-library-move="${index}" data-delta="-1" ${index===0?'disabled':''} aria-label="上移条件">↑</button><button data-library-move="${index}" data-delta="1" ${index===draft.length-1?'disabled':''} aria-label="下移条件">↓</button><button data-library-delete="${index}" aria-label="删除条件">×</button></header>${body}<small class="condition-edit-error" role="status"></small></article>`;
  }).join('')||'<p class="condition-selected-empty">从左侧选择条件，点击即可添加。</p>';list.scrollTop=scroll;if(options.readOnly)list.querySelectorAll('input,select,button').forEach(el=>el.disabled=true);
 }
 function edit(input){if(options.readOnly)return false;const i=Number(input.dataset.libraryRow),p=Number(input.dataset.libraryParam),row=draft[i];if(!row)return false;const value=Number(input.value),t=getTemplate(row),parameter=t?.parameters?.find(v=>v.index===p),n=C.numeric(row);let error=input.value.trim()===''||!Number.isFinite(value)?'请输入有效数值。':(/int|long/.test(parameter?.type||'')||input.step==='1')&&!Number.isInteger(value)?'请输入整数。':input.min!==''&&input.min!==undefined&&value<Number(input.min)?'数值不能低于 '+input.min:input.max!==''&&input.max!==undefined&&value>Number(input.max)?'数值不能高于 '+input.max:'';
  input.setCustomValidity(error);input.setAttribute('aria-invalid',String(!!error));input.closest('.condition-selected-card').querySelector('.condition-edit-error').textContent=error;if(error)return false;
  row[p]=value;input.closest('.condition-selected-card').querySelector('header strong').textContent=(i+1)+'. '+titleFor(row);if(n?.op==='='&&C.family(row).key==='age')row[3]=value;return true;
 }
 dialog.addEventListener('input',event=>{const el=event.target;if(event.isComposing)return;if(el.matches('.condition-library-search')){query=el.value;page=0;renderCatalogue();}else if(el.dataset.libraryRaw!==undefined){const out=C.readCommandInput(el);if(!out.error)draft[Number(el.dataset.libraryRaw)]=out.values;}else if(el.dataset.libraryParam!==undefined)edit(el);});
 dialog.addEventListener('change',event=>{const el=event.target;if(el.dataset.libraryMod!==undefined){modId=el.value;page=0;renderCatalogue();return;}if(options.readOnly)return;if(el.dataset.libraryVariant!==undefined){const i=Number(el.dataset.libraryVariant),old=draft[i],oldTemplate=getTemplate(old),v=variants(old)[Number(el.value)];if(!v)return;const next=copy(v.template);for(const p of v.parameters||[]){const previous=(oldTemplate?.parameters||[]).find(x=>x.index===p.index&&x.range?.table===p.range?.table);if(previous&&old[p.index]!==undefined)next[p.index]=old[p.index];}draft[i]=next;renderSelected();}
  else if(el.dataset.librarySample!==undefined){const i=Number(el.dataset.librarySample),v=sampleVariants.get(Number(draft[i][0]))?.[Number(el.value)];if(v){draft[i]=copy(v.row);renderSelected();}}
  else if(el.dataset.libraryRaw!==undefined){const out=C.readCommandInput(el);if(!out.error){draft[Number(el.dataset.libraryRaw)]=out.values;renderSelected();}}
  else if(el.dataset.libraryParam!==undefined)edit(el);
 });
 dialog.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;if(b.hasAttribute('data-library-close')||b.hasAttribute('data-library-cancel'))return finish(null);if(b.hasAttribute('data-library-apply'))return finish(copy(draft));if(b.dataset.libraryMode){mode=b.dataset.libraryMode;page=0;query='';dialog.querySelector('.condition-library-search').value='';renderCatalogue();if(mode==='configs'){if(configSource==='mod'&&!modLoaded)loadMods();else if(configSource==='user'&&!presetsLoaded)loadPresets();}return;}if(b.dataset.libraryConfig){configSource=b.dataset.libraryConfig;page=0;query='';dialog.querySelector('.condition-library-search').value='';renderCatalogue();if(configSource==='mod'&&!modLoaded)loadMods();else if(configSource==='user'&&!presetsLoaded)loadPresets();return;}if(b.hasAttribute('data-preset-save')){savePreset();return;}if(b.dataset.presetDelete){deletePreset(b.dataset.presetDelete);return;}if(b.dataset.libraryCategory){category=b.dataset.libraryCategory;page=0;renderCatalogue();return;}if(b.dataset.libraryPage){page=Math.max(0,page+Number(b.dataset.libraryPage));renderCatalogue();return;}if(options.readOnly||presetBusy)return;if(b.dataset.libraryPremise!==undefined){const i=Number(b.dataset.libraryPremise),r=draft[i],reached=Number(r[1])!==1;draft[i]=[111,reached?1:2,r[2],r[3],reached?1:0];renderSelected();return;}if(b.dataset.libraryDelete!==undefined){draft.splice(Number(b.dataset.libraryDelete),1);renderSelected();}else if(b.dataset.libraryMove!==undefined){const i=Number(b.dataset.libraryMove),j=i+Number(b.dataset.delta);if(j>=0&&j<draft.length){[draft[i],draft[j]]=[draft[j],draft[i]];renderSelected();}}else if(b.dataset.libraryOperator!==undefined){if(hasErrors()){dialog.querySelector('[aria-invalid="true"]').focus();return;}const i=Number(b.dataset.libraryOperator),n=C.numeric(draft[i]);if(n){const op=n.ops[(n.ops.indexOf(n.op)+1)%n.ops.length];draft[i]=n.make(op,draft[i][n.valueIndex],n.upperIndex===null?undefined:draft[i][n.upperIndex]);renderSelected();}}});
 function rememberPremises(items){
  let added=false;for(const p of items){const key='premise:'+Number(p.eventId)+':'+Number(p.slot);if(templates.some(t=>C.family(t.template,t).key===key))continue;for(const reached of [true,false]){const row=[111,reached?1:2,Number(p.eventId),Number(p.slot),reached?1:0];templates.unshift({label:(reached?'已达成：':'未达成：')+p.name,template:row,match:Object.fromEntries(row.map((v,i)=>[i,v])),parameters:[]});}added=true;}if(added)originalCache=null;
 }
 function premiseNames(){const out=new Map();for(const row of draft){const f=family(row);if(f.key.startsWith('premise:'))out.set(f.key,{eventId:Number(row[2]),slot:Number(row[3]),name:f.title});}return [...out.values()];}
 function validDraft(){for(const input of dialog.querySelectorAll('[data-library-raw]'))C.readCommandInput(input);if(hasErrors()){dialog.querySelector('[aria-invalid="true"]').focus();return false;}if(!draft.length||draft.some(r=>r.length<2)){message('请先在右侧添加完整条件。');return false;}return true;}
 async function loadPresets(){try{const data=await api('condition-presets');if(closed)return;presetEntries=data.entries||[];presetsLoaded=true;renderCatalogue();}catch(e){if(!closed)message('用户配置读取失败：'+e.message);}}
 async function savePreset(){
  if(options.readOnly||presetBusy||!validDraft())return;presetBusy=true;dialog.querySelector('[data-preset-save]').disabled=true;
  try{const data=await api('condition-presets',{action:'save',title:dialog.querySelector('[data-preset-name]').value,rows:copy(draft),premises:premiseNames()});if(closed)return;presetEntries=data.entries||[];presetsLoaded=true;query='';page=0;dialog.querySelector('.condition-library-search').value='';dialog.querySelector('[data-preset-name]').value='';renderCatalogue();message('已保存用户配置。');}catch(e){if(!closed)message('保存配置失败：'+e.message);}finally{presetBusy=false;if(!closed)dialog.querySelector('[data-preset-save]').disabled=!!options.readOnly;}
 }
 async function deletePreset(key){
  if(options.readOnly||presetBusy)return;presetBusy=true;
  try{const data=await api('condition-presets',{action:'delete',key});if(closed)return;presetEntries=data.entries||[];presetsLoaded=true;renderCatalogue();message('已删除用户配置，右侧已添加条件保持不变。');}catch(e){if(!closed)message('删除配置失败：'+e.message);}finally{presetBusy=false;if(!closed)dialog.querySelector('[data-preset-save]').disabled=!!options.readOnly;}
 }
 async function loadMods(){const seq=++loadSequence;message('正在读取模组条件…');try{const data=await api('condition-library?projectId='+encodeURIComponent(projectId)+'&source=mods');if(closed||seq!==loadSequence)return;modEntries=data.entries||[];modLoaded=true;modWarning=data.warnings?.join('；')||'';renderCatalogue();}catch(e){if(!closed)message('模组条件读取失败：'+e.message);}}
 async function load(){try{const data=await api('condition-library?projectId='+encodeURIComponent(projectId));if(closed)return;for(const t of data.templates||[]){if(!templates.some(x=>JSON.stringify(x.match)===JSON.stringify(t.match)&&x.template?.length===t.template?.length))templates.push(t);}entries=data.entries||[];rememberPremises(entries.filter(e=>e.origin==='named').map(e=>({eventId:e.rows[0][2],slot:e.rows[0][3],name:e.title.replace(/^(?:前提)?[已未]达成：/,'')})));dialog.dataset.originalGroups=String(entries.filter(e=>e.origin==='original').length);originalCache=null;status=data.indexing?'正在后台读取原版完整条件…':data.warning?'部分条件尚未读取：'+data.warning:'点击添加条件，比较方式和参数在右侧设置。';renderCatalogue();if(!dialog.querySelector('.condition-selected-list').contains(document.activeElement))renderSelected();if(data.indexing)timer=setTimeout(load,1500);}catch(e){if(!closed)message('已有条件读取失败：'+e.message);}}
 dialog.oncancel=event=>{event.preventDefault();finish(null);};dialog.showModal();renderCatalogue();renderSelected();load();
 });
}
window.StudentAgeConditionLibrary={open};
})();
