(()=>{'use strict';let dialog=null;const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,body){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-Studio-Token':window.STUDIO_TOKEN},body:JSON.stringify(body)}),data=await r.json();if(!r.ok)throw Error(data.error||'检查失败');return data;}
const dirty=()=>window.STUDIO_HAS_UNSAVED_CHANGES?.()||window.STUDIO_WORKSHOP_NAV?.dirty?.();
async function open(){if(dialog)return;const projectId=window.STUDIO_CURRENT_PROJECT?.();if(!projectId)return;let state=null,busy=false;dialog=document.createElement('dialog');dialog.className='config-doctor-dialog';dialog.innerHTML='<header><h2>检查并修复配置文件</h2><p>检查模组全部配置 JSON 的语法和编号结构。空白待填内容不是错误；不会修改无法确定的剧情含义。</p></header><div class="config-doctor-results" role="status"></div><footer><span data-doctor-status></span><button data-doctor-close>关闭</button><button data-doctor-check>重新检查</button><button data-doctor-repair class="primary" disabled>备份并修复</button></footer>';document.body.append(dialog);const d=dialog,q=s=>d.querySelector(s),status=q('[data-doctor-status]'),list=q('.config-doctor-results');
function lock(value){busy=value;for(const b of d.querySelectorAll('button'))b.disabled=value;q('[data-doctor-repair]').disabled=value||!state?.repairable||state.readOnly;}
function render(){list.innerHTML=state.issues.length?state.issues.map(i=>'<article><h3>'+esc(i.path)+'</h3><p>'+esc(i.message)+'</p><p class="helper">'+esc(i.action||(i.fixable?'可以自动修复':'请手动检查'))+'</p><button data-doctor-json="'+esc(i.path)+'">打开 JSON</button></article>').join(''):'<p class="config-doctor-clean">未发现配置文件语法或编号结构错误。</p>';status.textContent='已检查 '+state.filesChecked+' 个文件 · '+state.issues.length+' 个问题 · '+state.repairable+' 个可自动修复'+(dirty()?'。当前未保存草稿保留，检查对象为磁盘文件。':'');lock(false);}
async function check(){lock(true);status.textContent='正在检查…';try{state=await api('/api/config-check',{projectId});render();}catch(e){status.textContent=e.message;}finally{lock(false);}}
async function repair(){if(!state?.repairable||busy)return;lock(true);status.textContent='正在备份并修复…';try{const retained=dirty(),result=await api('/api/config-repair',{projectId,revision:state.revision,scanToken:state.scanToken});state=result;if(!retained){await window.STUDIO_REFRESH_CURRENT_PROJECT?.();await window.STUDIO_WORKSHOP_NAV?.refreshAssets?.();window.STUDIO_EVENTS?.refresh?.();}render();status.textContent='已备份并修复 '+result.fixed.length+' 个文件'+(result.backup?'。备份：'+result.backup:'')+(retained?'。未保存草稿仍保留，未重载；再次保存前需处理版本变化。':'');}catch(e){status.textContent=e.message;}finally{lock(false);}}
function close(){if(busy)return;d.close();d.remove();dialog=null;}
d.onclick=e=>{if(e.target.closest('[data-doctor-close]'))close();else if(e.target.closest('[data-doctor-check]'))check();else if(e.target.closest('[data-doctor-repair]'))repair();else{const file=e.target.closest('[data-doctor-json]');if(file){close();window.STUDIO_JSON_EDITOR.open(file.dataset.doctorJson).catch(e=>window.STUDIO_NOTIFY?.(e.message,true));}}};d.oncancel=e=>{e.preventDefault();close();};d.showModal();await check();}
window.STUDIO_CONFIG_DOCTOR={open};})();
