(() => {
'use strict';
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const ids=value=>(Array.isArray(value)?value:[]).map(Number).filter(Number.isFinite);
const host=document.createElement('section');host.id='story-events';host.hidden=true;host.setAttribute('aria-label','剧情事件');document.body.append(host);
const confirmation=document.createElement('dialog');confirmation.id='event-delete-dialog';confirmation.setAttribute('aria-labelledby','event-delete-title');document.body.append(confirmation);
const E={context:null,query:'',filter:'all',page:0,busy:false,notice:'',error:false};
const pageSize=40;
const filters=[['all','全部事件',null],['start','回合开始事件',[0]],['end','回合结束事件',[3]],['skip','可跳过按钮事件',[1]],['button','不可跳过按钮事件',[101,102,10]],['social','社交事件',[-24,2,11,20,21,22,521]],['affection','社交触发事件',[2]],['relation','关系事件',[20]],['phone','电话事件',[71,70]],['action','行动触发事件',[4]]];
const defaultType=()=>filters.find(f=>f[0]===E.filter)?.[2]?.find(id=>id>=0)??1;
let knownEventIds=new Set();
function getContext(){return window.STUDIO_EVENT_CONTEXT?.()||{};}
function readonly(){return !!E.context?.readOnly||!!E.context?.project?.readOnly;}
function message(text,error=false){E.notice=text;E.error=error;const node=host.querySelector('[data-events-notice]');if(node){node.textContent=text;node.hidden=!text;node.classList.toggle('error',error);}}
function links(talk,doc){const next=[...ids(talk?.nextTalk),...ids(talk?.nextTalk2)];for(const id of ids(talk?.option)){const option=doc.options?.[id];next.push(...ids(option?.talkId),...ids(option?.talkId2));}return next;}
function walk(starts,doc){const visited=new Set(),stack=ids(starts).reverse();while(stack.length){const id=stack.pop();if(visited.has(id)||!doc.talks?.[id])continue;visited.add(id);for(const next of links(doc.talks[id],doc))if(!visited.has(next))stack.push(next);}return visited;}
function eventRows(){const context=E.context||{},doc=context.doc||{};const rows=context.events?(Array.isArray(context.events)?context.events:Object.values(context.events)):Object.values(doc.events||{});return rows.filter(row=>row&&row.id!=null).sort((left,right)=>Number(left.id)-Number(right.id));}
function conditionSummary(row){const rows=row.condition||[];if(!rows.length)return '未设置额外触发条件';const templates=E.context?.conditionTemplates||[];if(templates.length&&window.StudentAgeConditions?.summary)return window.StudentAgeConditions.summary(rows,templates,E.context.conditionRefs||{})||rows.length+' 项触发条件';return rows.length+' 项触发条件';}
function firstLine(row){const doc=E.context?.doc||{},first=ids(row.talkId).map(id=>doc.talks?.[id]).find(Boolean);return first?.content||'';}
function eventTitle(row){return row.title||row.name||'未命名事件';}
function talkLabel(id){const row=E.context?.doc?.talks?.[id];if(!row)return '对话未载入';const speaker=ids(row.roleIds).map(role=>E.context.doc.persons?.[role]?.name).find(Boolean)||row.roleName;return (speaker?speaker+'：':'')+(row.content||'空白对话');}

function setBusy(value){E.busy=value;host.querySelectorAll('button,input').forEach(node=>node.disabled=value);if(!value)render();}
async function run(action){if(E.busy)return;message('');setBusy(true);try{await action();if(!host.hidden)refresh();}catch(error){message(error.message||String(error),true);}finally{E.busy=false;if(!host.hidden)render();}}
function requireBridge(name){const bridge=window[name];if(typeof bridge!=='function')throw Error('事件编辑尚未就绪，请重新打开工作台。');return bridge;}
function render(){if(host.hidden)return;const context=E.context||{},rows=eventRows(),query=E.query.trim().toLowerCase(),filtered=rows.filter(row=>(E.filter==='all'||filters.find(f=>f[0]===E.filter)?.[2]?.includes(StudentAgeEventBindings.displayType(row)))&&StudentAgeSearch.matches(query,row.id,eventTitle(row),firstLine(row),conditionSummary(row))),dirty=context.dirty??window.STUDIO_HAS_UNSAVED_CHANGES?.();E.page=Math.max(0,Math.min(E.page,Math.ceil(filtered.length/pageSize)-1));const start=E.page*pageSize;
 host.innerHTML=`<header class="events-header"><div><button class="events-back" data-events-back>← 工坊主页</button><h1>剧情事件</h1><p>${esc(context.project?.name||'当前模组')}</p></div><div class="events-header-actions"><button data-events-original>浏览原版事件</button><span class="events-save-state">${readonly()?'订阅模组 · 只读':dirty?'有未保存的修改':'已保存'}</span>${readonly()?'':'<button data-events-save>保存模组</button><button class="primary" data-events-create>＋ 新建事件</button>'}</div></header><main class="events-main"><nav class="events-filters" aria-label="事件类型筛选">${filters.map(([key,name])=>`<button data-event-filter="${key}" aria-pressed="${E.filter===key}">${name}</button>`).join('')}</nav><p class="events-notice ${E.error?'error':''}" data-events-notice role="status" aria-live="polite" ${E.notice?'':'hidden'}>${esc(E.notice)}</p><div class="events-search-row"><input id="event-search" type="search" value="${esc(E.query)}" placeholder="搜索事件名称、条件或首句对话" aria-label="搜索事件"><span>${filtered.length} 项</span></div><div class="event-grid">${filtered.slice(start,start+pageSize).map(row=>{const count=walk(row.talkId,context.doc||{}).size,external=!count&&ids(row.talkId).some(id=>id>0);return `<article class="event-card ${String(row.id)===String(context.currentEvent)?'current':''}" data-event-card="${esc(row.id)}"><button class="event-card-open" data-enter-event="${esc(row.id)}"><strong>${StudentAgeRecordLabels.html(row.id,eventTitle(row))}</strong>${(n=>n?`<span class="id-notes">${n}</span>`:'')(window.STUDIO_ID_NOTES?.('events',row.id)||'')}<span class="event-dialogue-count">${external?'0 句已载入对话':count+' 句对话'}</span><p class="event-condition-summary">${esc(conditionSummary(row))}</p><p class="event-first-line">${esc(firstLine(row)||(external?'已预留入口，对话尚未创建或来自其他模组':count?'首句对话未载入':'尚未添加对话'))}</p><span class="event-open-label">${readonly()?'查看对话':count?'编辑对话':'添加对话'} →</span></button><div class="event-card-actions"><button data-edit-event="${esc(row.id)}">${readonly()?'查看设置':'事件设置'}</button>${readonly()?'':`<button class="danger-text" data-delete-event="${esc(row.id)}">删除事件</button>`}</div></article>`;}).join('')||`<div class="events-empty"><h2>${query?'没有匹配的事件':'这个模组还没有剧情事件'}</h2><p>${query?'试试其他名称或对话内容。':readonly()?'可以返回工坊，复制为本地模组后添加事件。':'新建事件，设置名称和触发条件，再进入事件添加对话。'}</p>${query||readonly()?'':'<button class="primary" data-events-create>＋ 新建事件</button>'}</div>`}</div>${filtered.length>pageSize?`<nav class="events-pagination" aria-label="事件翻页"><button data-events-page="-1" ${E.page===0?'disabled':''}>上一页</button><span>${E.page+1} / ${Math.ceil(filtered.length/pageSize)}</span><button data-events-page="1" ${start+pageSize>=filtered.length?'disabled':''}>下一页</button></nav>`:''}</main>`;
 host.querySelector('[data-events-original]').onclick=()=>run(browseOriginal);
 host.querySelectorAll('[data-event-filter]').forEach(b=>b.onclick=()=>{E.filter=b.dataset.eventFilter;E.page=0;render();});
 host.querySelector('[data-events-back]').onclick=()=>run(async()=>{const open=window.STUDIO_OPEN_WORKSHOP;if(typeof open==='function'){await open();if(document.querySelector('#workshop')?.hidden===false)close();}else throw Error('工坊入口尚未就绪，请重新打开工作台。');});
 host.querySelector('[data-events-save]')?.addEventListener('click',()=>run(async()=>{const result=await requireBridge('STUDIO_SAVE_EVENT_CHANGES')();if(result!==false)message('模组已保存。');}));
 host.querySelectorAll('[data-events-create]').forEach(button=>button.onclick=()=>run(()=>requireBridge('STUDIO_CREATE_EVENT')({type:defaultType()})));
 host.querySelectorAll('[data-enter-event]').forEach(button=>button.onclick=()=>run(async()=>{const id=Number(button.dataset.enterEvent);const result=await requireBridge('STUDIO_ENTER_EVENT')(id);if(result!==false)close();}));
 host.querySelectorAll('[data-edit-event]').forEach(button=>button.onclick=()=>run(()=>requireBridge('STUDIO_EDIT_EVENT')(Number(button.dataset.editEvent))));
 host.querySelectorAll('[data-delete-event]').forEach(button=>button.onclick=()=>deleteEvent(Number(button.dataset.deleteEvent)));
 host.querySelectorAll('[data-events-page]').forEach(button=>button.onclick=()=>{E.page+=Number(button.dataset.eventsPage);render();host.querySelector('.events-main').scrollTop=0;});
 host.querySelector('#event-search').oninput=event=>{const input=event.target,position=input.selectionStart;E.query=input.value;E.page=0;render();const replacement=host.querySelector('#event-search');replacement.focus();replacement.setSelectionRange?.(position,position);};

 if(E.busy)host.querySelectorAll('button,input').forEach(node=>node.disabled=true);else if(host.querySelector('[data-events-save]'))host.querySelector('[data-events-save]').disabled=!dirty||!!context.saving;
}
async function browseOriginal(){
 const projectId=E.context.project.id,api=window.StudentAgeCharacterUI.api;
 const [data,types]=await Promise.all([api('table?'+new URLSearchParams({projectId,name:'EvtCfg'})),api('table?'+new URLSearchParams({projectId,name:'EvtTypeCfg'}))]);
 if(getContext().project?.id!==projectId)return;
 const d=document.createElement('dialog');d.className='character-picker original-events-browser';d.setAttribute('aria-label','原版剧情事件');document.body.append(d);
 const rows=Object.values(data.referenceRows||{}).sort((a,b)=>Number(!!(b.title||b.talkId?.length))-Number(!!(a.title||a.talkId?.length))||Number(a.id)-Number(b.id));let q='',type='',page=0,selected=null;
 d.innerHTML='<header><div><h2>原版剧情事件</h2><p>浏览游戏原有事件的名称、触发条件和配置。</p></div><button data-original-close aria-label="关闭">×</button></header><div class="events-search-row"><input data-original-search placeholder="搜索名称、说明或事件编号"><select data-original-type><option value="">全部类型</option>'+[...new Set(rows.map(r=>Number(r.type)||0))].sort((a,b)=>a-b).map(id=>`<option value="${id}">${esc(types.rows?.[id]?.name||'事件类型 '+id)}</option>`).join('')+'</select></div><div class="original-events-columns"><section><div data-original-list></div><nav class="events-pagination"><button data-original-prev>上一页</button><span data-original-count></span><button data-original-next>下一页</button></nav></section><aside data-original-detail></aside></div><p class="helper">原版没有阻止指定事件加载的配置开关。覆盖触发条件不能拦截所有直接调用，可通过同编号配置覆盖原版事件，但这不等于阻止事件加载。</p>';
 const originalTitle=r=>r.title||r.name||r.desc||r.content?.slice(0,45)||(types.rows?.[r.type]?.name||'事件')+' · '+conditionSummary(r);
 const detail=()=>{const r=rows.find(r=>Number(r.id)===selected);d.querySelector('[data-original-detail]').innerHTML=r?`<h3>${esc(originalTitle(r))}</h3><p>${esc(types.rows?.[r.type]?.name||'类型 '+r.type)} · ${esc(r.id)}</p><h4>触发条件</h4><p>${esc(conditionSummary(r))}</p><h4>事件内容</h4><p class="original-event-content">${esc(r.content||r.desc||'本事件通过对话入口播放。')}</p><dl><dt>发生次数上限</dt><dd>${esc(r.maxcount??'未设置')}</dd><dt>触发概率</dt><dd>${esc(r.rate==null?'未设置':Number(r.rate)*100+'%')}</dd><dt>关联人物或对象</dt><dd>${esc(E.context.conditionRefs?.PersonCfg?.[r.npc]?.name||r.npc||'无')}</dd><dt>对话入口</dt><dd>${esc(ids(r.talkId).join('、')||'无')}</dd></dl>${!readonly()?`<div class="original-event-actions"><button class="primary" data-original-override>${getContext().doc?.events?.[r.id]?'编辑当前模组覆盖':'覆盖到当前模组'}</button>${getContext().doc?.events?.[r.id]?'<button data-original-restore>撤销该模组覆盖</button>':''}</div><p class="helper">保留原编号和对话入口；修改随当前模组保存，可撤销。</p>`:''}<details><summary>查看完整原版配置</summary><pre>${esc(JSON.stringify(r,null,2))}</pre></details>`:'<p>选择左侧事件，查看详情。</p>';};
 const paint=()=>{const found=rows.filter(r=>(!type||Number(r.type)===Number(type))&&StudentAgeSearch.matches(q,r.id,originalTitle(r),r.content,r.desc,conditionSummary(r)));page=Math.max(0,Math.min(page,Math.ceil(found.length/30)-1));d.querySelector('[data-original-list]').innerHTML=found.slice(page*30,page*30+30).map(r=>`<button data-original-event="${r.id}" aria-pressed="${selected===Number(r.id)}"><strong>${StudentAgeRecordLabels.html(r.id,originalTitle(r))}</strong><small>${esc(types.rows?.[r.type]?.name||'类型 '+r.type)}</small></button>`).join('')||'<p>没有匹配的原版事件。</p>';d.querySelector('[data-original-count]').textContent=found.length+' 项 · '+(page+1)+' / '+Math.max(1,Math.ceil(found.length/30));d.querySelector('[data-original-prev]').disabled=page===0;d.querySelector('[data-original-next]').disabled=(page+1)*30>=found.length;detail();};
 const end=()=>{d.close();d.remove();};d.oncancel=e=>{e.preventDefault();end();};d.onclick=async e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-original-override')||b.hasAttribute('data-original-restore')){b.disabled=true;try{const id=selected;if(b.hasAttribute('data-original-restore')){await requireBridge('STUDIO_RESTORE_ORIGINAL_EVENT')(id);paint();}else{await requireBridge('STUDIO_OVERRIDE_ORIGINAL_EVENT')(id);end();await requireBridge('STUDIO_EDIT_EVENT')(id);}}catch(error){message(error.message,true);b.disabled=false;}return;}if(b.hasAttribute('data-original-close'))end();if(b.dataset.originalEvent){selected=Number(b.dataset.originalEvent);paint();}if(b.hasAttribute('data-original-prev')){page--;paint();}if(b.hasAttribute('data-original-next')){page++;paint();}};
 d.querySelector('[data-original-search]').oninput=e=>{q=e.target.value;page=0;paint();};d.querySelector('[data-original-type]').onchange=e=>{type=e.target.value;page=0;paint();};paint();d.showModal();
}

function deleteEvent(id){if(readonly()||E.busy)return;const row=eventRows().find(row=>Number(row.id)===id),projectId=E.context?.project?.id;if(!row)return;confirmation.innerHTML=`<h2 id="event-delete-title">删除事件？</h2><p>删除“${esc(eventTitle(row))}”及其全部所属对话、选项和前提，同时清理遗留的无归属对话。共用对话也会删除，并清除其他事件对它们的关联。</p><p>仍被其他剧情引用的事件，需要先处理引用关系。</p><p data-event-delete-error role="status"></p><div><button data-event-delete-cancel>取消</button><button class="danger-button" data-event-delete-apply>删除事件与对话</button></div>`;confirmation.querySelector('[data-event-delete-cancel]').onclick=()=>confirmation.close();confirmation.querySelector('[data-event-delete-apply]').onclick=async()=>{const button=confirmation.querySelector('[data-event-delete-apply]');button.disabled=true;try{if(getContext().project?.id!==projectId||getContext().doc?.events?.[id]!==row)throw Error('事件已变化，请关闭窗口后重新选择。');const result=await requireBridge('STUDIO_DELETE_EVENT')(id);if(result===false)return;confirmation.close();message('事件及其所属对话已删除。');refresh();}catch(error){confirmation.querySelector('[data-event-delete-error]').textContent=error.message||String(error);}finally{button.disabled=false;}};confirmation.showModal();}
function setContext(next){const changed=next.project?.id!==E.context?.project?.id;if(changed){E.filter='all';E.query='';E.page=0;E.notice='';E.error=false;knownEventIds=new Set();}E.context=next;const rows=eventRows(),current=String(next.currentEvent);if(!changed&&!knownEventIds.has(current)){const index=rows.findIndex(row=>String(row.id)===current);if(index>=0){E.query='';E.page=Math.floor(index/pageSize);}}knownEventIds=new Set(rows.map(row=>String(row.id)));}
function refresh(){if(host.hidden)return;setContext(getContext());render();}
function open(){const next=getContext();if(!next.project){window.STUDIO_REPORT_ERROR?.(Error('请先打开一个模组。'));return false;}window.STUDIO_PAUSE_PREVIEW?.();setContext(next);E.notice='';E.error=false;host.hidden=false;render();return true;}
function close(){host.hidden=true;confirmation.close();}
window.addEventListener('studio-project-ready',()=>{if(!host.hidden)refresh()});
window.STUDIO_EVENTS={open,refresh,close,isOpen:()=>!host.hidden,capture:()=>({filter:E.filter,query:E.query,page:E.page}),restore:v=>{open();Object.assign(E,v);render();}};
})();
