/* Folder purposes write native CFG entry points through the existing draft/save transaction. */
(()=>{'use strict';const copy=structuredClone,UI=StudentAgeCharacterUI,esc=UI.esc;
const label=u=>window.StudentAgeExternalUses.definitions?.find(d=>d.kind===u.kind)?.label||({'gift':'送礼对话','mini-start':'小游戏开场','mini-win':'小游戏胜利','mini-lose':'小游戏失败'}[u.kind])||'已绑定用途';
async function open({folder,talks,catalog,projectId,dialog,alive=()=>true,readOnly=false}){
 const data=await catalog();if(!alive())return null;window.StudentAgeExternalUses.definitions=data.definitions;
 let uses=copy(folder.uses||[]);const defs=data.definitions,refs=data.refs,rows=t=>Object.values(refs[t]||{}),name=(t,id)=>`[${id}] ${refs[t]?.[id]?.name||refs[t]?.[id]?.title||refs[t]?.[id]?.text||refs[t]?.[id]?.content||'未命名'}`;
 // Recognize native bindings made in the built-in editor without changing files.
 const discovered=[];const ids=new Set(folder.talkIds);
 const offer=(d,r,v,extra={})=>{if(!v)return;const entries=Array.isArray(v)?v:[v];for(const [i,id]of entries.entries()){if(!ids.has(id))continue;const u={id:crypto.randomUUID(),kind:d.kind,recordId:r.id,entryId:id,gender:entries.length>1?(i===0?'male':'female'):'both',...extra};if(!discovered.some(x=>x.kind===u.kind&&x.recordId===u.recordId&&x.entryId===u.entryId&&x.npc===u.npc&&x.answer===u.answer))discovered.push(u);}};
 for(const d of defs.filter(d=>!d.disabled))for(const r of rows(d.table)){
  if(d.shape==='gift'){(r.npc||[]).forEach((npc,i)=>offer(d,r,r.talkId?.[i],{npc,item:r.item,giftMode:r.type?.[i]||0}));}
  else if(d.shape==='mini'){const game=Math.floor(r.id/100),level=r.id%100;if(level>=1&&level<=5){const person=rows('PersonGrowCfg').find(p=>p.minigame===game);if(person)offer(d,r,r[d.field],{npc:person.id,level});}}
  else if(d.shape==='answer'){(r.inputs||[]).forEach((answer,i)=>offer(d,r,r.jumps?.[i],{answer}));}
  else offer(d,r,d.shape==='phase'?r[d.field]?.[d.slot]:d.shape==='first'?r[d.field]?.[0]:r[d.field]);
 }
 const available=()=>discovered.filter(u=>!uses.some(x=>x.kind===u.kind&&x.recordId===u.recordId&&x.npc===u.npc&&x.answer===u.answer));
 const p=dialog(folder.name+' · 用途','');p.d.classList.add('external-purpose-dialog');const body=p.d.querySelector('.character-picker-body');
 function paint(){body.innerHTML=`<p class="helper">用途与对话一起保存到模组。一个对话夹可绑定多个入口。移除新绑定会恢复原入口，不会删除对话。</p><div class="external-purpose-list">${uses.map((u,i)=>`<section class="external-purpose-card"><strong>${esc(label(u))}</strong><p>${esc(u.npc?name('PersonCfg',u.npc):u.recordId?'配置 ['+u.recordId+']':'待配置')}${u.level?' · 第 '+u.level+' 关':''} → 对话 [${u.entryId}]</p><div class="idle-tools"><button data-use-edit="${i}">${readOnly?'查看参数':'配置参数'}</button><button data-use-remove="${i}" ${readOnly?'disabled':''}>移除用途</button></div></section>`).join('')||'<p class="idle-empty">尚未设置用途。</p>'}</div>${available().length?`<details><summary>游戏配置中的已有入口 · ${available().length}</summary>${available().map((u,i)=>`<button data-use-existing="${i}" ${readOnly?'disabled':''}>${esc(label(u))} · [${u.recordId}] → [${u.entryId}] · 配置参数</button>`).join('')}</details>`:''}<p data-use-error role="alert"></p><div class="idle-tools"><button data-use-add ${readOnly?'disabled':''}>＋ 添加用途</button><button data-use-apply class="primary" ${readOnly?'disabled':''}>应用到草稿</button></div><p class="helper">默认绑定本夹的第一句，也可指定其他起始句；后续按原有对话跳转播放。应用后仍可撤销，保存模组后才会在游戏中生效。</p>`;}
 async function chooseDefinition(){const q=dialog('选择对话用途',`<div class="external-purpose-list">${defs.map(d=>`<button class="external-purpose-card" data-use-kind="${esc(d.kind)}" ${d.disabled?'disabled':''}><strong>${esc(d.label)}</strong><small>${esc(d.help||'')}</small></button>`).join('')}</div>`);q.d.setAttribute('data-dismiss-outside','');q.d.onclick=e=>{const b=e.target.closest('[data-use-kind]');if(b&&!b.disabled)q.end(defs.find(d=>d.kind===b.dataset.useKind));};return q.promise;}
 async function configure(original,d){
  let u=copy(original);const q=dialog(d.label+' · 参数','');q.d.classList.add('external-purpose-dialog');const area=q.d.querySelector('.character-picker-body');
  const schema=data.schemas[d.table].fields.filter(f=>d.fields.includes(f.name));
  function defaults(row={}){u.params=Object.fromEntries(schema.map(f=>[f.name,copy(row[f.name]??f.default??(f.type?.startsWith('list')?[]:f.type==='string'?'':0))]));u.baseParams=copy(u.params);}
  if(!u.params)defaults(refs[d.table]?.[u.recordId]);
  function resolveGift(){const match=rows(d.table).filter(r=>r.item===u.item&&r.npc?.includes(u.npc));u.recordId=match[0]?.id||0;defaults(match[0]);if(match[0])u.giftMode=match[0].type?.[match[0].npc.indexOf(u.npc)]||0;return match.length;}
  function resolveMini(){const game=refs.PersonGrowCfg?.[u.npc]?.minigame||0;u.recordId=game?game*100+(u.level||1):0;return {game,exists:!!refs.MinigameActionCfg?.[u.recordId]};}
  function summary(f){const v=u.params[f.name],t=f.range?.table;if(Array.isArray(v))return v.length?(t?v.map(id=>name(t,id)).join('、'):v.length+' 项'):'未设置';return t&&v?name(t,v):'未选择';}
  function render(){const mini=resolveMiniIfNeeded();area.innerHTML=`<p class="helper">${esc(d.help||'')}</p><div class="external-purpose-fields">${d.shape==='gift'?`<label>收礼人<button data-use-person>${u.npc?esc(name('PersonCfg',u.npc)):'选择人物'}</button></label><label>具体礼物<button data-use-gift>${u.item?esc(name(refs.ItemCfg?.[u.item]?'ItemCfg':'BookCfg',u.item)):'选择礼物'}</button></label><label>赠送方式<select data-use-value="giftMode"><option value="0" ${!u.giftMode?'selected':''}>交付礼物并播放对话</option><option value="1" ${u.giftMode===1?'selected':''}>仅播放对话，不交付礼物</option></select></label>`:d.shape==='mini'?`<label>人物<button data-use-person>${u.npc?esc(name('PersonCfg',u.npc)):'选择人物'}</button></label><label>关卡<select data-use-value="level">${[1,2,3,4,5].map(i=>`<option value="${i}" ${u.level===i?'selected':''}>第 ${i} 关</option>`).join('')}</select></label><p class="helper" data-use-mini-status>${mini.game?esc(name('MinigameCfg',mini.game))+' · '+(mini.exists?'关卡可用':'该关卡不存在'):'请先在人物界面绑定小游戏。'}</p>`:`<label>${d.label}配置<button data-use-record>${u.recordId?esc(name(d.table,u.recordId)):'选择已有配置'}</button></label>${d.create?'<button data-use-new>新建一条配置</button>':''}`}
   ${d.shape==='answer'?`<label>精确匹配的答案<input data-use-text="answer" maxlength="500" value="${esc(u.answer||'')}" placeholder="填写玩家要输入的答案"></label>`:''}
   ${['pair','gift','answer'].includes(d.shape)?`<label>主角性别<select data-use-string="gender"><option value="both" ${u.gender==='both'?'selected':''}>男主、女主共用</option><option value="male" ${u.gender==='male'?'selected':''}>仅男主（保留女主入口）</option><option value="female" ${u.gender==='female'?'selected':''}>仅女主（保留男主入口）</option></select></label>`:''}
   <label>从哪句开始<select data-use-value="entryId">${folder.talkIds.filter(id=>talks[id]).map(id=>`<option value="${id}" ${u.entryId===id?'selected':''}>[${id}] ${esc((talks[id].content||'空白对话').slice(0,50))}</option>`).join('')}</select></label>
   ${schema.map(f=>{const v=u.params[f.name],k=esc(f.name),title=esc(f.label||f.name);if(f.editorType==='Condition'||f.editorType==='Effect')return `<label>${title}<button data-use-command="${k}">${f.editorType==='Condition'?'编辑条件':'编辑效果'} · ${v?.length||0}</button></label>`;if(f.range?.table)return `<label>${title}<button data-use-reference="${k}">${esc(summary(f))}</button>${f.type?.startsWith('list')?`<button data-use-clear="${k}">清空限制</button>`:''}</label>`;if(f.name==='redpoint')return `<label>${title}<select data-use-param="${k}"><option value="0" ${!v?'selected':''}>不显示</option><option value="1" ${v===1?'selected':''}>显示首次对话提示</option></select></label>`;if(f.type==='string')return `<label>${title}<input data-use-param="${k}" value="${esc(v||'')}"></label>`;if(!f.type?.startsWith('list'))return `<label>${title}<input type="number" step="any" data-use-param="${k}" value="${Number(v)||0}"></label>`;return '';}).join('')}</div><p data-use-error role="alert"></p><button data-use-confirm class="primary" ${readOnly?'disabled':''}>确认参数</button>`;
   if(readOnly)area.querySelectorAll('button,input,select').forEach(n=>n.disabled=true);
  }
  function resolveMiniIfNeeded(){return d.shape==='mini'?resolveMini():{};}
  function valid(){if(!folder.talkIds.includes(u.entryId))throw Error('请先在对话夹中添加对话。');if(d.shape==='mini'&&!resolveMini().exists)throw Error('请先为该人物绑定小游戏，并选择存在的关卡（最多第 5 关）。');if(d.shape==='gift'){if(!u.npc||!u.item)throw Error('请选择收礼人和具体礼物。');if(rows(d.table).filter(r=>r.item===u.item&&r.npc?.includes(u.npc)).length>1)throw Error('该人物和礼物存在多条送礼规则。请先合并重复入口，避免原版抢先匹配另一条对话。');}else if(!u.recordId&&!d.create)throw Error('请选择已有配置。');if(d.shape==='answer'&&!u.answer)throw Error('请填写精确匹配的答案。');if(d.kind==='interact'&&!u.params.npc)throw Error('请选择闲聊人物。');}
  area.oninput=e=>{const n=e.target;if(n.dataset.useText)u[n.dataset.useText]=n.value;if(n.dataset.useParam){const f=schema.find(f=>f.name===n.dataset.useParam);u.params[f.name]=f.type==='string'?n.value:Number(n.value);}};
  area.onchange=e=>{const n=e.target;if(n.dataset.useValue){u[n.dataset.useValue]=Number(n.value);if(n.dataset.useValue==='level')render();}if(n.dataset.useString)u[n.dataset.useString]=n.value;if(n.dataset.useParam){const f=schema.find(f=>f.name===n.dataset.useParam);u.params[f.name]=f.type==='string'?n.value:Number(n.value);}};
  area.onclick=async e=>{const b=e.target.closest('button');if(!b||b.disabled)return;try{
   if(b.hasAttribute('data-use-person')){const r=await UI.choices(d.shape==='gift'?'选择收礼人':'选择小游戏人物',rows('PersonCfg').filter(r=>r.id>0),{table:'PersonCfg',projectId,selected:u.npc});if(r&&q.d.isConnected){u.npc=Number(r.id);if(d.shape==='gift')resolveGift();render();}}
   if(b.hasAttribute('data-use-gift')){const r=await StudentAgeWarehouse.pick(projectId,u.item);if(r&&q.d.isConnected){u.item=Number(r.id);resolveGift();render();}}
   if(b.hasAttribute('data-use-record')){const list=rows(d.table).map(r=>({...r,name:r.name||r.title||r.text||r.content||'配置 '+r.id}));const r=await UI.choices('选择'+d.label+'配置',list,{table:d.table,projectId,selected:u.recordId});if(r&&q.d.isConnected){u.recordId=Number(r.id);defaults(r);if(d.shape==='answer')u.answer=r.inputs?.[0]||'';render();}}
   if(b.hasAttribute('data-use-new')){u.recordId=0;defaults();render();}
   if(b.dataset.useCommand){const f=schema.find(f=>f.name===b.dataset.useCommand),kind=f.editorType==='Condition'?'condition':'effect';const v=await (kind==='condition'?StudentAgeConditionLibrary:StudentAgeEffects).open({projectId,rows:u.params[f.name]||[],templates:data.commands[kind],refs});if(v&&q.d.isConnected){u.params[f.name]=v;render();}}
   if(b.dataset.useReference){const f=schema.find(f=>f.name===b.dataset.useReference),table=f.range.table,list=f.type.startsWith('list'),v=u.params[f.name];const r=await UI.choices(f.label,rows(table),{table,projectId,selected:list?v?.[0]:v});if(r&&q.d.isConnected){u.params[f.name]=list?[...new Set([...(v||[]),Number(r.id)])]:Number(r.id);render();}}
   if(b.dataset.useClear){u.params[b.dataset.useClear]=[];render();}
   if(b.hasAttribute('data-use-confirm')){valid();q.end(u);}
  }catch(e){area.querySelector('[data-use-error]').textContent=e.message;}};
  render();return q.promise;
 }
 body.onclick=async e=>{const b=e.target.closest('button');if(!b||b.disabled)return;try{
  if(b.dataset.useExisting!==undefined){const candidate=available()[Number(b.dataset.useExisting)],d=defs.find(d=>d.kind===candidate.kind);const u=await configure(candidate,d);if(u&&p.d.isConnected){uses.push(u);paint();}}
  if(b.hasAttribute('data-use-add')){if(!folder.talkIds.length)throw Error('请先给此对话夹添加至少一句对话。');const d=await chooseDefinition();if(d&&p.d.isConnected){const u=await configure({id:crypto.randomUUID(),kind:d.kind,entryId:folder.talkIds[0],gender:'both',level:1,giftMode:0},d);if(u&&p.d.isConnected){uses.push(u);paint();}}}
  if(b.dataset.useEdit!==undefined){const i=Number(b.dataset.useEdit),d=defs.find(d=>d.kind===uses[i].kind);if(!d)throw Error('未知用途，请先更新编辑器。');const u=await configure(uses[i],d);if(u&&p.d.isConnected){uses[i]=u;paint();}}
  if(b.dataset.useRemove!==undefined){uses.splice(Number(b.dataset.useRemove),1);paint();}
  if(b.hasAttribute('data-use-apply'))p.end(uses);
 }catch(e){body.querySelector('[data-use-error]').textContent=e.message;}};
 paint();return p.promise;
}
window.StudentAgeExternalUses={open,label};})();
