/* Folder purposes write native CFG entry points through the existing draft/save transaction. */
(()=>{'use strict';const copy=structuredClone,UI=StudentAgeCharacterUI,esc=UI.esc;
const label=u=>window.StudentAgeExternalUses.definitions?.find(d=>d.kind===u.kind)?.label||({'gift':'送礼对话','mini-start':'小游戏开场','mini-win':'小游戏胜利','mini-lose':'小游戏失败'}[u.kind])||'已绑定用途';
async function open({folder,talks,catalog,projectId,dialog,alive=()=>true,readOnly=false}){
 const data=await catalog();if(!alive())return null;window.StudentAgeExternalUses.definitions=data.definitions;
 let uses=copy(folder.uses||[]);const defs=data.definitions,refs=data.refs,rows=t=>Object.values(refs[t]||{}),name=(t,id)=>`[${id}] ${refs[t]?.[id]?.name||refs[t]?.[id]?.title||refs[t]?.[id]?.text||refs[t]?.[id]?.content||'未命名'}`;
 // Recognize native bindings made in the built-in editor without changing files.
 const discovered=[];const ids=new Set(folder.talkIds);
 const offer=(d,r,v,extra={})=>{if(!v)return;const entries=Array.isArray(v)?v:[v];for(const [i,id]of entries.entries()){if(!ids.has(id))continue;const u={id:crypto.randomUUID(),kind:d.kind,recordId:r.id,entryId:id,gender:entries.length>1?(i===0?'male':'female'):'both',...extra};if(!discovered.some(x=>x.kind===u.kind&&x.recordId===u.recordId&&x.entryId===u.entryId&&x.npc===u.npc&&x.answer===u.answer))discovered.push(u);}};
 for(const d of defs.filter(d=>!d.disabled&&d.kind!=='interact'))for(const r of rows(d.table)){
  if(d.shape==='gift'){(r.npc||[]).forEach((npc,i)=>offer(d,r,r.talkId?.[i],{npc,item:r.item,giftMode:r.type?.[i]||0}));}
  else if(d.shape==='mini'){const game=Math.floor(r.id/100),level=r.id%100;if(level>=1&&level<=5){const person=rows('PersonGrowCfg').find(p=>p.minigame===game);if(person)offer(d,r,r[d.field],{npc:person.id,level});}}
  else if(d.shape==='answer'){(r.inputs||[]).forEach((answer,i)=>offer(d,r,r.jumps?.[i],{answer}));}
  else offer(d,r,d.shape==='phase'?r[d.field]?.[d.slot]:d.shape==='first'?r[d.field]?.[0]:r[d.field]);
 }
 const available=()=>discovered.filter(u=>!uses.some(x=>x.kind===u.kind&&x.recordId===u.recordId&&x.npc===u.npc&&x.answer===u.answer));
 const p=dialog(folder.name+' · 添加用途','');p.d.classList.add('external-purpose-dialog','condition-library','condition-browser');const body=p.d.querySelector('.character-picker-body');let query='';const validators=new Map();
 const visibleDefs=defs.filter(d=>!d.disabled&&d.kind!=='interact');
 body.innerHTML=`<div class="condition-browser-layout"><section class="condition-browser-catalog"><h3>用途目录</h3><input type="search" data-use-search placeholder="搜索用途" aria-label="搜索用途"><div class="condition-library-results" data-use-catalog></div><details data-use-discovered><summary>已有游戏入口</summary><div></div></details></section><aside class="condition-browser-selected"><h3>已添加用途 <span data-use-count></span></h3><div class="condition-selected-list" data-use-list></div></aside></div>`;
 const footer=document.createElement('footer');footer.className='condition-browser-actions';footer.innerHTML=`<span data-use-error role="alert"></span><button data-use-cancel>取消</button><button data-use-apply class="primary" ${readOnly?'disabled':''}>完成</button>`;p.d.append(footer);
 function paintCatalogue(){body.querySelector('[data-use-catalog]').innerHTML=visibleDefs.filter(d=>StudentAgeSearch.matches(query,d.label,d.help)).map(d=>`<button class="condition-library-entry" data-use-kind="${esc(d.kind)}" ${readOnly?'disabled':''}><strong>${esc(d.label)}<span>＋</span></strong></button>`).join('');}
 function paint(){const list=body.querySelector('[data-use-list]'),scroll=list.scrollTop;validators.clear();body.querySelector('[data-use-count]').textContent=uses.length+' 项';list.innerHTML=uses.map((u,i)=>`<article class="condition-selected-card external-use-card" data-use-card="${esc(u.id)}"><header><strong>${i+1}. ${esc(label(u))}</strong><button data-use-remove="${i}" class="danger" aria-label="删除${esc(label(u))}" ${readOnly?'disabled':''}>×</button></header><div data-use-parameters></div></article>`).join('')||'<p class="condition-selected-empty">点击左侧用途添加，在这里逐项编辑。</p>';
  uses.forEach((u,i)=>{const d=defs.find(d=>d.kind===u.kind),area=list.children[i].querySelector('[data-use-parameters]');if(d)configure(u,d,area);else area.textContent='原有用途暂不支持编辑，请保留或移除。';});list.scrollTop=scroll;
  const availableUses=available(),existing=body.querySelector('[data-use-discovered]');existing.hidden=!availableUses.length;existing.querySelector('div').innerHTML=availableUses.map((u,i)=>`<button data-use-existing="${i}" ${readOnly?'disabled':''}>${esc(label(u))} [${u.recordId}]</button>`).join('');
 }
 function configure(u,d,area){
  const q=p;
  const schema=data.schemas[d.table].fields.filter(f=>d.fields.includes(f.name));
  function defaults(row={}){u.params=Object.fromEntries(schema.map(f=>[f.name,copy(row[f.name]??f.default??(f.type?.startsWith('list')?[]:f.type==='string'?'':0))]));u.baseParams=copy(u.params);}
  if(!u.params||schema.some(f=>!Object.hasOwn(u.params,f.name)))defaults(refs[d.table]?.[u.recordId]);
  function resolveGift(){const match=rows(d.table).filter(r=>r.item===u.item&&r.npc?.includes(u.npc));u.recordId=match[0]?.id||0;defaults(match[0]);if(match[0])u.giftMode=match[0].type?.[match[0].npc.indexOf(u.npc)]||0;return match.length;}
  function resolveMini(){const game=refs.PersonGrowCfg?.[u.npc]?.minigame||0;const next=game?game*100+(u.level||1):0;if(u.recordId!==next){u.recordId=next;defaults(refs.MinigameActionCfg?.[next]);}return {game,exists:!!refs.MinigameActionCfg?.[u.recordId]};}
  function summary(f){const v=u.params[f.name],t=f.range?.table;if(Array.isArray(v))return v.length?(t?v.map(id=>name(t,id)).join('、'):v.length+' 项'):'未设置';return t&&v?name(t,v):'未选择';}
  function render(){const mini=resolveMiniIfNeeded();area.innerHTML=`<p class="helper">${esc(d.help||'')}</p><div class="external-purpose-fields">${d.shape==='gift'?`<label>收礼人<button data-use-person>${u.npc?esc(name('PersonCfg',u.npc)):'选择人物'}</button></label><label>具体礼物<button data-use-gift>${u.item?esc(name(refs.ItemCfg?.[u.item]?'ItemCfg':'BookCfg',u.item)):'选择礼物'}</button></label><label>赠送方式<select data-use-value="giftMode"><option value="0" ${!u.giftMode?'selected':''}>交付礼物并播放对话</option><option value="1" ${u.giftMode===1?'selected':''}>仅播放对话，不交付礼物</option></select></label>`:d.shape==='mini'?`<label>人物<button data-use-person>${u.npc?esc(name('PersonCfg',u.npc)):'选择人物'}</button></label><label>关卡<select data-use-value="level">${[1,2,3,4,5].map(i=>`<option value="${i}" ${u.level===i?'selected':''}>第 ${i} 关</option>`).join('')}</select></label><div class="external-mini-binding" data-use-mini-status>${mini.game?`<strong>已绑定：${esc(name('MinigameCfg',mini.game))} · 第 ${u.level} 关</strong><p>${mini.exists?'当前关卡入口 ['+u.recordId+']':'该关卡不存在，不能绑定。'}</p>${mini.exists?`<p>关系要求：${esc(refs.RelationCfg?.[refs.MinigameActionCfg[u.recordId].needRelation]?.name||refs.MinigameActionCfg[u.recordId].needRelation||'无')} · 基础信任消耗：${refs.MinigameActionCfg[u.recordId].cost??0}</p><p>共用人物：${esc(rows('PersonGrowCfg').filter(r=>r.minigame===mini.game).map(r=>name('PersonCfg',r.id)).join('、'))}</p>`:''}`:'请先在人物界面绑定小游戏。'}</div>`:`<label>${d.label}配置<button data-use-record>${u.recordId?esc(name(d.table,u.recordId)):'选择已有配置'}</button></label>${d.create?'<button data-use-new>新建一条配置</button>':''}`}
   ${d.shape==='answer'?`<label>精确匹配的答案<input data-use-text="answer" maxlength="500" value="${esc(u.answer||'')}" placeholder="填写玩家要输入的答案"></label>`:''}
   ${['pair','gift','answer'].includes(d.shape)?`<label>主角性别<select data-use-string="gender"><option value="both" ${u.gender==='both'?'selected':''}>男主、女主共用</option><option value="male" ${u.gender==='male'?'selected':''}>仅男主（保留女主入口）</option><option value="female" ${u.gender==='female'?'selected':''}>仅女主（保留男主入口）</option></select></label>`:''}

   ${schema.map(f=>{const v=u.params[f.name],k=esc(f.name),title=esc(f.label||f.name);if(f.editorType==='Condition'||f.editorType==='Effect')return `<label>${title}<button data-use-command="${k}">${f.editorType==='Condition'?'编辑条件':'编辑效果'} · ${v?.length||0}</button></label>`;if(f.range?.table)return `<label>${title}<button data-use-reference="${k}">${esc(summary(f))}</button>${f.type?.startsWith('list')?`<button data-use-clear="${k}">清空限制</button>`:''}</label>`;if(f.type==='list<float>')return `<fieldset class="external-use-values"><legend>${title}</legend>${(v||[]).map((value,i)=>`<label>${esc(d.shape==='mini'&&Math.floor(u.recordId/100)===20?['对手最短间隔（秒）','对手最长间隔（秒）','对手成功率（0～1）','失误抖动时间（秒）'][i]||('参数 '+(i+1)):'参数 '+(i+1))}<input type="number" step="any" data-use-list-param="${k}" data-use-list-index="${i}" value="${value}"></label>`).join('')||'<span>此关卡无此类数值参数</span>'}</fieldset>`;if(f.name==='redpoint')return `<label>${title}<select data-use-param="${k}"><option value="0" ${!v?'selected':''}>不显示</option><option value="1" ${v===1?'selected':''}>显示首次对话提示</option></select></label>`;if(f.type==='string')return `<label>${title}<input data-use-param="${k}" value="${esc(v||'')}"></label>`;if(!f.type?.startsWith('list'))return `<label>${title}<input type="number" step="any" data-use-param="${k}" value="${Number(v)||0}"></label>`;return '';}).join('')}</div><p data-use-error role="alert"></p>`;
   if(readOnly)area.querySelectorAll('button,input,select').forEach(n=>n.disabled=true);
  }
  function resolveMiniIfNeeded(){return d.shape==='mini'?resolveMini():{};}
  function valid(){if(!folder.talkIds.includes(u.entryId))throw Error('请先在对话夹中添加对话。');if(d.shape==='mini'&&!resolveMini().exists)throw Error('请先为该人物绑定小游戏，并选择存在的关卡（最多第 5 关）。');if(d.shape==='gift'){if(!u.npc||!u.item)throw Error('请选择收礼人和具体礼物。');if(rows(d.table).filter(r=>r.item===u.item&&r.npc?.includes(u.npc)).length>1)throw Error('该人物和礼物存在多条送礼规则。请先合并重复入口，避免原版抢先匹配另一条对话。');}else if(!u.recordId&&!d.create)throw Error('请选择已有配置。');if(d.shape==='answer'&&!u.answer)throw Error('请填写精确匹配的答案。');if(d.kind==='interact'&&!u.params.npc)throw Error('请选择闲聊人物。');}
  area.oninput=e=>{const n=e.target;if(n.dataset.useListParam)u.params[n.dataset.useListParam][Number(n.dataset.useListIndex)]=Number(n.value);if(n.dataset.useText)u[n.dataset.useText]=n.value;if(n.dataset.useParam){const f=schema.find(f=>f.name===n.dataset.useParam);u.params[f.name]=f.type==='string'?n.value:Number(n.value);}};
  area.onchange=e=>{const n=e.target;if(n.dataset.useValue){u[n.dataset.useValue]=Number(n.value);if(n.dataset.useValue==='level')render();}if(n.dataset.useString)u[n.dataset.useString]=n.value;if(n.dataset.useParam){const f=schema.find(f=>f.name===n.dataset.useParam);u.params[f.name]=f.type==='string'?n.value:Number(n.value);}};
  area.onclick=async e=>{const b=e.target.closest('button');if(!b||b.disabled)return;try{
   if(b.hasAttribute('data-use-person')){const r=await UI.choices(d.shape==='gift'?'选择收礼人':'选择小游戏人物',rows('PersonCfg').filter(r=>r.id>0),{table:'PersonCfg',projectId,selected:u.npc});if(r&&q.d.isConnected&&uses.includes(u)){u.npc=Number(r.id);if(d.shape==='gift')resolveGift();render();}}
   if(b.hasAttribute('data-use-gift')){const r=await StudentAgeWarehouse.pick(projectId,u.item);if(r&&q.d.isConnected&&uses.includes(u)){u.item=Number(r.id);resolveGift();render();}}
   if(b.hasAttribute('data-use-record')){const list=rows(d.table).map(r=>({...r,name:r.name||r.title||r.text||r.content||'配置 '+r.id}));const r=await UI.choices('选择'+d.label+'配置',list,{table:d.table,projectId,selected:u.recordId});if(r&&q.d.isConnected&&uses.includes(u)){u.recordId=Number(r.id);defaults(r);if(d.shape==='answer')u.answer=r.inputs?.[0]||'';render();}}
   if(b.hasAttribute('data-use-new')){u.recordId=0;defaults();render();}
   if(b.dataset.useCommand){const f=schema.find(f=>f.name===b.dataset.useCommand),kind=f.editorType==='Condition'?'condition':'effect';const v=await (kind==='condition'?StudentAgeConditionLibrary:StudentAgeEffects).open({projectId,rows:u.params[f.name]||[],templates:data.commands[kind],refs});if(v&&q.d.isConnected&&uses.includes(u)){u.params[f.name]=v;render();}}
   if(b.dataset.useReference){const f=schema.find(f=>f.name===b.dataset.useReference),table=f.range.table,list=f.type.startsWith('list'),v=u.params[f.name];const r=await UI.choices(f.label,rows(table),{table,projectId,selected:list?v?.[0]:v});if(r&&q.d.isConnected&&uses.includes(u)){u.params[f.name]=list?[...new Set([...(v||[]),Number(r.id)])]:Number(r.id);render();}}
   if(b.dataset.useClear){u.params[b.dataset.useClear]=[];render();}

  }catch(e){area.querySelector('[data-use-error]').textContent=e.message;}};
  u.entryId=folder.talkIds[0];validators.set(u.id,valid);render();
 }
 body.querySelector('[data-use-search]').oninput=e=>{query=e.target.value;paintCatalogue();};
 body.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled||readOnly)return;
  if(b.dataset.useKind){const d=defs.find(d=>d.kind===b.dataset.useKind);uses.push({id:crypto.randomUUID(),kind:d.kind,entryId:folder.talkIds[0],gender:'both',level:1,giftMode:0});paint();body.querySelector('[data-use-list]').lastElementChild?.scrollIntoView({block:'nearest'});}
  if(b.dataset.useExisting!==undefined){uses.push(copy(available()[Number(b.dataset.useExisting)]));paint();}
  if(b.dataset.useRemove!==undefined){uses.splice(Number(b.dataset.useRemove),1);paint();}
 });
 footer.querySelector('[data-use-cancel]').onclick=()=>p.end(null);
 footer.querySelector('[data-use-apply]').onclick=()=>{if(readOnly)return;let first=null;for(const u of uses){const card=body.querySelector(`[data-use-card="${CSS.escape(u.id)}"]`),error=card.querySelector('[data-use-error]');try{validators.get(u.id)?.();if(error)error.textContent='';}catch(e){if(error)error.textContent=e.message;first??=card;}}if(first){footer.querySelector('[data-use-error]').textContent='请补全右侧标出的用途参数。';first.scrollIntoView({block:'nearest'});return;}p.end(copy(uses));};
 paintCatalogue();
 paint();return p.promise;
}
window.StudentAgeExternalUses={open,label};})();
