/* Objective list, native preview, and compact editing controls. */
(()=>{'use strict';
const UI=StudentAgeCharacterUI,esc=UI.esc,clone=v=>structuredClone(v);
const labels={name:'目标标题',desc:'目标描述',npc:'目标图像',finishType:'移除规则',round:'持续回合',demand:'完成要求',reward:'完成奖励',condition:'出现条件',fail:'失败效果',failTalk:'失败后对话',finishTalk:'完成后对话',before:'前置目标',next:'后续目标组',group:'目标组',renshengguan:'优先匹配的人生观',tag:'目标分类',targetRound:'截止回合',weight:'同组随机权重'};
const removals=[[0,'领取奖励后移除'],[1,'完成时自动移除'],[2,'仅通过效果移除']];
function create(host,options){
 const api=options.api,S={data:null,rows:{},images:{},uploads:{},pending:[],selected:null,tab:'basic',query:'',source:'local',saved:'',revision:null,undo:[],redo:[],last:null,busy:false,refs:{},invalid:{},native:null,resourceError:'',previewState:'progress',focused:false,progress:0,currentRound:1};
 let alive=true,zoom=null;const $=s=>host.querySelector(s),readonly=()=>!!options.project.readOnly||S.source==='reference',rows=()=>S.source==='reference'?S.data?.goals.referenceRows||{}:S.rows,row=()=>rows()[S.selected];
 const snapshot=()=>JSON.stringify({rows:S.rows,pending:S.pending}),dirty=()=>!!S.data&&(snapshot()!==S.saved||Object.keys(S.invalid).length>0||!!host.querySelector('[data-effect-invalid],[aria-invalid="true"]'));
 const imageURL=path=>'/api/assets?'+new URLSearchParams({projectId:options.project.id,path,token:options.token});
 const nativeURL=file=>'/api/goal-ui?'+new URLSearchParams({resource:file,token:options.token});
 const head=id=>S.uploads[id]?.preview||(S.images[id]?.head?imageURL(S.images[id].head):'/api/talk-head?'+new URLSearchParams({projectId:options.project.id,roleId:id??0,grade:2,gender:1,token:options.token}));
 function notify(){options.onState?.({busy:S.busy,dirty:dirty(),readOnly:!!options.project.readOnly,canUndo:!!S.undo.length,canRedo:!!S.redo.length,revision:S.revision});host.querySelectorAll('[data-goal-save]').forEach(b=>b.disabled=!!options.project.readOnly||S.busy||!dirty());host.querySelectorAll('[data-goal-form] fieldset').forEach(f=>f.disabled=readonly()||S.busy);}
 function change(fn,key=null){if(readonly()||S.busy)throw Error('当前目标不可编辑。');if(!key||S.last!==key){S.undo.push(snapshot());if(S.undo.length>40)S.undo.shift();}S.last=key;S.redo=[];fn();notify();}
 function error(e){const msg=e.message||String(e),n=$('[data-goal-error]');if(n)n.textContent=msg;options.status(msg,true);window.STUDIO_REPORT_ERROR?.(e);}
 function restored(value){const data=JSON.parse(value);S.rows=data.rows;S.pending=data.pending||[];S.invalid={};S.last=null;if(!rows()[S.selected])S.selected=Object.keys(rows())[0]||null;render();}
 function history(from,to){if(options.project.readOnly||S.busy||!S[from].length)return;S.source='local';S[to].push(snapshot());restored(S[from].pop());}
 async function load(){S.busy=true;notify();try{const data=await api('/api/goals?'+new URLSearchParams({projectId:options.project.id}));if(!alive)return;S.data=data;S.rows=clone(data.goals.localRows);S.images=data.images||{};S.revision=data.revision;S.pending=[];S.uploads={};S.invalid={};S.saved=snapshot();S.refs={PersonCfg:data.people.rows,IntentCfg:{...data.goals.referenceRows,...S.rows}};
 const needed=new Set(['ConditionTypeCfg','EffectTypeCfg','RenshengguanTypeCfg','TalkCfg',...(data.goals.schema.fields||[]).map(f=>f.range?.table).filter(Boolean),...Object.values(options.info.commands||{}).flat().flatMap(t=>(t.parameters||[]).map(p=>p.range?.table).filter(Boolean))]);
 S.localIds={PersonCfg:data.people.localIds,IntentCfg:data.goals.localIds};await Promise.all([...needed].filter(n=>!S.refs[n]).map(async name=>{const d=await api('/api/table?'+new URLSearchParams({projectId:options.project.id,name}));if(!alive)return;S.refs[name]=d.rows;S.localIds[name]=d.localIds||[];}));if(!alive)return;S.selected=S.rows[S.selected]?S.selected:Object.keys(S.rows)[0]||null;S.undo=[];S.redo=[];render();loadNative();}finally{S.busy=false;if(alive)notify();}}
 async function loadNative(){try{const data=await api('/api/goal-ui');if(!alive)return;S.native=data;S.resourceError='';for(const [name,file]of Object.entries(data.fonts||{})){const font=new FontFace('GoalNative-'+name,`url("${nativeURL(file)}")`);font.load().then(f=>{if(alive)document.fonts.add(f);}).catch(()=>{});}preview();}catch(e){if(alive){S.resourceError=e.message||String(e);preview();}}}
 function render(){if(!S.data)return;observer.disconnect();host.innerHTML=`<section class="goal-workspace"><aside class="goal-list"><header><button data-goal-action="home" class="text-button">← 工坊主页</button><h2>目标</h2><button class="primary" data-goal-action="add" ${options.project.readOnly?'disabled':''}>＋ 添加目标</button></header><nav class="character-filters"><button data-goal-source="local" class="${S.source==='local'?'active':''}">${options.project.originalMode?'原版 · 保存到当前模组':'当前模组'}</button><button data-goal-source="reference" class="${S.source==='reference'?'active':''}">原版参考</button></nav><input data-goal-search placeholder="搜索目标名称或编号" value="${esc(S.query)}"><div data-goal-list></div></aside><main class="goal-main"><header class="goal-preview-toolbar"><strong>游戏内目标预览</strong><label title="仅用于预览截止回合，不写入模组">当前回合<input data-goal-preview-round type="number" min="1" step="1" value="${S.currentRound}"></label><label>显示状态<select data-goal-preview-state>${[['progress','进行中'],['complete','已完成'],['failed','已失败']].map(([v,l])=>`<option value="${v}" ${S.previewState===v?'selected':''}>${l}</option>`).join('')}</select></label><button data-goal-action="zoom">放大预览</button></header><div class="goal-preview-frame" data-goal-preview></div><section class="goal-settings"><header><h3>目标设置</h3><nav class="character-filters">${[['basic','基本设置'],['demand','完成要求'],['reward','奖励与失败'],['advanced','扩展设置']].map(([v,l])=>`<button data-goal-tab="${v}" class="${S.tab===v?'active':''}">${l}</button>`).join('')}</nav><button data-goal-save class="primary">保存</button></header><div data-goal-form></div><p data-goal-error role="status"></p></section></main></section>`;list();form();preview();notify();}
 function list(){const node=$('[data-goal-list]');if(!node)return;node.innerHTML=Object.values(rows()).filter(r=>StudentAgeSearch.matches(S.query,r.id,r.name,r.desc)).map(r=>`<button class="goal-list-card ${String(r.id)===S.selected?'active':''}" data-goal-id="${r.id}"><img loading="lazy" src="${esc(head(r.npc))}" alt="${esc(S.refs.PersonCfg?.[r.npc]?.name||'目标图像')}"><span><strong>${StudentAgeRecordLabels.html(r.id,r.name||'未命名目标')}</strong><small>${esc((r.desc||'').replace(/<[^>]*>/g,'').slice(0,60))}</small></span></button>`).join('')||'<p class="helper">'+(S.query?'没有匹配目标。':'点击上方添加目标。')+'</p>';}
 function input(field,r){const v=r[field],label=labels[field]||'扩展参数 '+field;
 if(field==='npc')return `<label>${label}<button class="goal-image-select" data-goal-action="image"><img src="${esc(head(v))}" alt="目标图像"><span>选择目标图像 ▾</span></button></label>`;
 if(field==='finishType')return `<label>${label}<select data-goal-field="finishType" data-number>${removals.map(([id,name])=>`<option value="${id}" ${Number(v||0)===id?'selected':''}>${name}</option>`).join('')}</select></label>`;
 if(field==='before')return `<label>${label}<button data-goal-reference="before" data-goal-table="IntentCfg">${esc(S.refs.IntentCfg?.[v]?.name||(v?'目标 '+v:'不需要前置目标'))} ▾</button></label>`;
 if(field==='renshengguan')return `<label>${label}<select data-goal-field="${field}" data-number><option value="0">不限</option>${Object.values(S.refs.RenshengguanTypeCfg||{}).map(r=>`<option value="${r.id}" ${Number(v)===r.id?'selected':''}>${esc(r.name||r.title||'人生观 '+r.id)}</option>`).join('')}</select></label>`;
 if(['finishTalk','failTalk'].includes(field))return `<label>${label}<div class="goal-talk-links">${(v||[]).map((id,i)=>`<button data-goal-talk="${field}" data-goal-index="${i}">${esc(S.refs.TalkCfg?.[id]?.content||'对话 '+id)} <span data-goal-talk-remove="${i}" data-goal-talk-field="${field}" role="button" aria-label="移除对话">×</span></button>`).join('')}<button data-goal-talk="${field}" data-goal-index="-1">＋ 选择对话</button></div></label>`;
 if(field==='desc')return `<label class="goal-wide">${label}<textarea data-goal-field="desc" rows="2">${esc(v||'')}</textarea></label>`;
 if(field==='tag')return `<label>${label}<select data-goal-field="tag" data-number>${[[0,'支线'],[1,'主线'],[2,'计划']].map(([id,l])=>`<option value="${id}" ${Number(v||0)===id?'selected':''}>${l}</option>`).join('')}${![0,1,2].includes(Number(v||0))?`<option value="${v}" selected>原有分类 ${v}</option>`:''}</select></label>`;
 if(typeof v==='boolean')return `<label>${esc(label)}<select data-goal-field="${field}" data-boolean><option value="true" ${v?'selected':''}>开启</option><option value="false" ${v?'':'selected'}>关闭</option></select></label>`;
 if(v&&typeof v==='object')return `<label>${esc(label)}<textarea data-goal-json="${field}">${esc(JSON.stringify(v))}</textarea></label>`;
 return `<label>${esc(label)}<input data-goal-field="${field}" ${typeof v==='number'||['round','group','targetRound','weight','next'].includes(field)?'type="number" data-number':''} ${['round','targetRound','weight'].includes(field)?'min="0"':''} step="${field==='weight'?'any':'1'}" value="${esc(v??'')}">${({round:'0 表示持续存在',targetRound:'0 不设置；设置后优先于持续回合',weight:'同一目标组随机抽取时使用',next:'移除后，从这个目标组随机选择后续目标',group:'999 为普通自定义目标组'})[field]?`<small>${esc(({round:'0 表示持续存在',targetRound:'0 不设置；设置后优先于持续回合',weight:'同一目标组随机抽取时使用',next:'移除后，从这个目标组随机选择后续目标',group:'999 为普通自定义目标组'})[field])}</small>`:''}</label>`;
 }
 function mountCommand(field,node){const r=row(),condition=['demand','condition'].includes(field),lib=condition?StudentAgeConditions:StudentAgeEffects;lib.mount(node,{rows:r[field]||[],templates:options.info.commands?.[condition?'condition':'effect']||[],refs:{...S.refs,IntentCfg:{...S.refs.IntentCfg,...S.rows}},localIds:S.localIds,projectId:options.project.id,readOnly:readonly(),description:field==='demand'?'所有要求达成后，目标完成。':field==='condition'?'控制目标何时可出现。':'',onError:error,onChange:value=>{change(()=>r[field]=value);preview();}});}
 function form(){const node=$('[data-goal-form]'),r=row();if(!node)return;if(!r){node.innerHTML='<div class="empty-state">选择左侧目标，或添加一个目标。</div>';return;}
 let fields=[],body='';if(S.tab==='basic')fields=['name','npc','finishType','round','desc'];
 if(S.tab==='demand')body='<section data-goal-command="demand"></section>';
 if(S.tab==='reward')body='<div class="goal-effect-columns"><section><h4>完成奖励</h4><div data-goal-command="reward"></div></section><section><h4>失败效果</h4><div data-goal-command="fail"></div></section></div><div class="goal-fields">'+['finishTalk','failTalk'].map(k=>input(k,r)).join('')+'</div>';
 if(S.tab==='advanced'){fields=['group','before','next','targetRound','weight','tag','renshengguan'];const known=new Set(['id','name','npc','finishType','round','desc','demand','reward','fail','finishTalk','failTalk','condition',...fields]);fields.push(...Object.keys(r).filter(k=>!known.has(k)));body='<section><h4>出现条件</h4><div data-goal-command="condition"></div></section>';}
 node.innerHTML=`<div class="goal-current-name"><strong>${esc(r.name||'未命名目标')}</strong>${readonly()?'':`<button data-record-table="IntentCfg" data-record-id="${r.id}">编号 ${r.id} · 修改</button>`}${S.source==='reference'&&!options.project.readOnly?'<button data-goal-action="duplicate" class="primary">复制到当前模组</button>':''}</div><fieldset ${readonly()||S.busy?'disabled':''}><div class="goal-fields">${fields.map(k=>input(k,r)).join('')}</div>${body}</fieldset>`;node.querySelectorAll('[data-goal-command]').forEach(n=>mountCommand(n.dataset.goalCommand,n));notify();}
 function sprite(key,extra=''){const info=S.native?.sprites?.[key];if(!info)return '';const border=info.border||[0,0,0,0],url=esc(nativeURL(info.file));return border.some(n=>n>0)?`<div class="goal-native-sprite ${extra}" aria-hidden="true" style="border-width:${border.map(n=>n+'px').join(' ')};border-image-source:url('${url}');border-image-slice:${border.join(' ')} fill;border-image-repeat:stretch"></div>`:`<img class="goal-native-sprite ${extra}" src="${url}" alt="">`;}
 function conditionTotal(c){const [type,sub]=c.map(Number);let value=1;if(type===4&&[1,2,4,308].includes(sub))value=c[sub===4?2:3];else if(type===60&&[3,4,5,6,7,20].includes(sub))value=c[sub===7?3:2];else if(type===7&&sub===1)value=c[3];return Number.isFinite(Number(value))&&Number(value)>0?Number(value):1;}
 function rich(value){return esc(value??'').replace(/&lt;(\/)?(b|i|u)&gt;/gi,'<$1$2>').replace(/&lt;color=(#[0-9a-f]{6,8})&gt;/gi,'<span style="color:$1">').replace(/&lt;\/color&gt;/gi,'</span>').replace(/\n/g,'<br>');}
 function commandsText(rows,kind){const templates=options.info.commands?.[kind]||[];if(kind==='condition')return StudentAgeConditions.summary(rows,templates,S.refs);return (rows||[]).map(row=>{const t=templates.find(t=>StudentAgeEffects.match(row,t));if(!t)return '自定义效果 '+row.join(',');return t.label+' '+(t.parameters||[]).map(p=>p.range?.table?(S.refs[p.range.table]?.[row[p.index]]?.name||row[p.index]):p.choices?.find(v=>Number(v.id)===Number(row[p.index]))?.label??row[p.index]).join(' ');}).join('，');}
 function nativeMarkup(){const r=row();if(!r)return '<p class="goal-preview-message">选择一个目标进行预览。</p>';if(!S.native)return `<p class="goal-preview-message">${esc(S.resourceError||'正在加载目标界面…')}</p>`;
 const complete=S.previewState==='complete',failed=S.previewState==='failed',progress=complete?1:S.progress,round=failed?0:Number(r.targetRound)>0?Math.max(0,Number(r.targetRound)-S.currentRound):Math.max(0,Number(r.round)||0),button=complete?(r.finishType===0?'完成':''):failed?(r.finishType===0?'好的':''):S.focused?'取消关注':'关注';
 return `<div class="goal-native-canvas">${sprite('background','goal-native-bg')}<section class="goal-native-list">${sprite('list')}<div class="goal-native-card">${sprite('card')}<img class="goal-native-avatar" src="${esc(head(r.npc))}" alt="目标图像"><div class="goal-native-card-title">${rich(r.name)}</div>${S.focused?sprite('pin','goal-native-pin'):''}${round>0?`<div class="goal-native-card-round">${sprite('card-round')}<span>${round}</span></div>`:''}${complete||failed?sprite(complete?'success':'fail','goal-native-card-stamp'):`<div class="goal-native-progress"><i style="width:${progress*100}%">${sprite('progress')}</i></div>`}</div></section><section class="goal-native-panel">${sprite('panel')}<h3>${rich(r.name)}</h3><p class="goal-native-desc">${rich(r.desc||commandsText(r.demand,'condition'))}</p><div class="goal-native-conditions">${(r.demand||[]).map(c=>`<div class="goal-native-condition" style="--goal-condition-tint:${complete?'#fff':'#eee7d5'}">${sprite(complete?'condition-complete':'condition')}<span>• ${rich(commandsText([c],'condition'))} (${complete?conditionTotal(c):0}/${conditionTotal(c)})</span>${complete?sprite('check','goal-native-check'):''}</div>`).join('')}</div>${r.reward?.length?`<div class="goal-native-reward">${sprite('reward')}<div class="goal-native-reward-label">${sprite('reward-label')}<span>奖<br>励</span></div><span>${rich(commandsText(r.reward,'effect'))}</span></div>`:''}${round>0?`<div class="goal-native-round">${sprite('round')}<span>${round}</span></div>`:''}${failed||complete&&r.finishType===0?sprite(failed?'fail':'success','goal-native-stamp'):''}${button?`<button class="goal-native-button" data-goal-native-button>${sprite('button')}<span>${button}</span></button>`:''}</section></div>`;
 }
 function size(frame){const canvas=frame?.querySelector('.goal-native-canvas');if(!canvas)return;const scale=Math.min(frame.clientWidth/1700,frame.clientHeight/1100);canvas.style.transform=`translate(-50%,-50%) scale(${scale})`;}
 const observer=new ResizeObserver(entries=>entries.forEach(e=>size(e.target)));
 function preview(){const frame=$('[data-goal-preview]');if(frame){frame.innerHTML=nativeMarkup();observer.observe(frame);size(frame);}if(zoom?.open){const area=zoom.querySelector('.goal-preview-frame');area.innerHTML=nativeMarkup();size(area);}}
 async function add(duplicate=false){if(Object.keys(S.invalid).length||host.querySelector('[data-effect-invalid],[aria-invalid="true"]'))throw Error('请先修正当前目标的参数。');const basis=duplicate?row():null;S.source='local';change(()=>{const id=STUDIO_IDS.allocate('IntentCfg',{...S.data.goals.rows,...S.rows}),defaults=Object.fromEntries((S.data.goals.schema.fields||[]).map(f=>[f.name,clone(f.default??(/^list/.test(f.type)?[]:f.type==='string'?'':0))]));S.rows[id]=basis?{...clone(basis),id,name:(basis.name||'目标')+' · 副本'}:{...defaults,id,name:'未命名目标',group:999,npc:0,finishType:0,round:0,weight:1};S.selected=String(id);});S.tab='basic';render();}
 async function remove(id=S.selected){if(readonly()||!S.rows[id])return;const r=S.rows[id],choice=await UI.choices('删除目标“'+r.name+'”？',[{id:'cancel',name:'取消'},{id:'delete',name:'删除目标'}]);if(choice?.id!=='delete')return;if(S.rows[id]!==r)throw Error('目标已变化，请重新选择。');change(()=>{delete S.rows[id];if(id===S.selected)S.selected=Object.keys(S.rows)[0]||null;});render();}
 async function save(){if(!dirty())return;if(S.busy)throw Error('正在保存目标。');if(options.project.readOnly)throw Error('当前模组为只读。');if(Object.keys(S.invalid).length||host.querySelector('[data-effect-invalid],[aria-invalid="true"]'))throw Error('请先修正尚未填写完整的目标参数。');S.busy=true;notify();try{const result=await api('/api/goals-save',{projectId:options.project.id,revision:S.revision,rows:S.rows,images:S.pending.filter(id=>Object.values(S.rows).some(r=>Number(r.npc)===id)).map(id=>({id:Number(id),name:S.uploads[id].name,data:S.uploads[id].data}))});if(!alive)return;S.rows=result.rows;S.images=result.images;S.refs.PersonCfg={...S.data.people.referenceRows,...result.people};S.data.people.rows=S.refs.PersonCfg;S.data.people.localRows=result.people;S.data.goals.localRows=clone(S.rows);S.data.goals.rows={...S.data.goals.referenceRows,...S.rows};S.refs.IntentCfg=S.data.goals.rows;S.localIds.IntentCfg=Object.keys(S.rows);S.localIds.PersonCfg=Object.keys(result.people);S.pending=[];S.revision=result.revision;S.saved=snapshot();S.undo=[];S.redo=[];S.last=null;await options.onSaved?.();render();options.status('目标已保存。');}finally{S.busy=false;if(alive)notify();}}
 async function imagePicker(){const selected=S.selected,d=document.createElement('dialog');d.className='goal-image-library';document.body.append(d);let source='original',q='';d.innerHTML='<header><h2>选择目标图像</h2><button data-image-close>×</button></header><nav class="character-filters">'+[['original','原版人物'],['mod','模组人物'],['custom','自定义图像']].map(([v,l])=>`<button data-image-source="${v}">${l}</button>`).join('')+'</nav><input data-image-search placeholder="搜索人物或图像名称"><div class="goal-image-grid"></div><p role="status"></p>';
 const paint=()=>{const ids=source==='original'?Object.keys(S.data.people.referenceRows):source==='mod'?Object.keys(S.data.people.localRows).filter(id=>!S.images[id]):[...new Set([...Object.keys(S.images),...S.pending.map(String)])];d.querySelector('.goal-image-grid').innerHTML=ids.map(id=>({id,name:S.uploads[id]?.name||S.images[id]?.name||S.refs.PersonCfg[id]?.name||'主角'})).filter(r=>StudentAgeSearch.matches(q,r.name,r.id)).map(r=>`<button data-image-id="${r.id}" class="${Number(row()?.npc)===Number(r.id)?'active':''}"><img src="${esc(head(r.id))}" alt="${esc(r.name)}" loading="lazy"><span>${esc(r.name)}</span></button>`).join('')+'<button data-image-add class="goal-image-add">＋<span>添加图像</span></button>';d.querySelectorAll('[data-image-source]').forEach(b=>b.classList.toggle('active',b.dataset.imageSource===source));};const end=()=>{d.close();d.remove();};d.oncancel=e=>{e.preventDefault();end();};d.onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-image-close'))end();if(b.dataset.imageSource){source=b.dataset.imageSource;paint();}if(b.dataset.imageId!==undefined&&selected===S.selected){change(()=>row().npc=Number(b.dataset.imageId));end();form();list();preview();}if(b.hasAttribute('data-image-add')){const file=document.createElement('input');file.type='file';file.accept='image/png,image/jpeg,image/webp';file.onchange=async()=>{try{const f=file.files[0];if(!f)return;if(f.size>8*1024*1024)throw Error('图像需小于 8 MB。');const encoded=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(f);});if(!alive||selected!==S.selected||!d.open)return;const id=STUDIO_IDS.allocate('PersonCfg',{...S.refs.PersonCfg,...Object.fromEntries(Object.keys(S.uploads).map(id=>[id,{id:Number(id)}]))});S.uploads[id]={name:f.name.replace(/\.[^.]+$/,''),data:encoded.split(',')[1],preview:encoded};change(()=>{S.pending.push(id);row().npc=id;});end();form();list();preview();}catch(e){d.querySelector('[role=status]').textContent=e.message;}};file.click();}};d.querySelector('[data-image-search]').oninput=e=>{q=e.target.value;paint();};paint();d.showModal();}
 async function pickReference(field,table,index=null){if(!S.refs[table])S.refs[table]=(await api('/api/table?'+new URLSearchParams({projectId:options.project.id,name:table}))).rows;const list=Object.values(table==='IntentCfg'?{...S.refs[table],...S.rows}:S.refs[table]).filter(r=>table!=='IntentCfg'||r.id!==Number(S.selected)).map(r=>({...r,name:r.name||r.title||r.content||'编号 '+r.id})),picked=await UI.choices(labels[field],[{id:0,name:index===null?'不设置':'移除此对话'},...list],{table,projectId:options.project.id});if(!picked)return;change(()=>{if(index===null)row()[field]=picked.id;else{const arr=row()[field]||=[];if(index<0){if(picked.id)arr.push(picked.id);}else if(picked.id)arr[index]=picked.id;else arr.splice(index,1);}});form();preview();}
 host.onclick=e=>{const b=e.target.closest('button'),removeTalk=e.target.closest('[data-goal-talk-remove]');if(!b)return;(async()=>{if(removeTalk){change(()=>row()[removeTalk.dataset.goalTalkField].splice(Number(removeTalk.dataset.goalTalkRemove),1));form();return;}if(b.dataset.goalId){if(Object.keys(S.invalid).length||host.querySelector('[data-effect-invalid],[aria-invalid="true"]'))throw Error('请先修正当前目标的参数。');S.selected=b.dataset.goalId;S.last=null;list();form();preview();}if(b.dataset.goalTab){if(Object.keys(S.invalid).length||host.querySelector('[data-effect-invalid],[aria-invalid="true"]'))throw Error('请先修正当前参数。');S.tab=b.dataset.goalTab;form();}if(b.dataset.goalSource){S.last=null;if(Object.keys(S.invalid).length||host.querySelector('[data-effect-invalid],[aria-invalid="true"]'))throw Error('请先修正当前目标的参数。');S.source=b.dataset.goalSource;S.selected=Object.keys(rows())[0]||null;render();}if(b.hasAttribute('data-goal-save'))await save();if(b.dataset.goalReference)await pickReference(b.dataset.goalReference,b.dataset.goalTable);if(b.dataset.goalTalk)await pickReference(b.dataset.goalTalk,'TalkCfg',Number(b.dataset.goalIndex));if(b.hasAttribute('data-goal-native-button')){if(S.previewState==='progress')S.focused=!S.focused;else S.previewState='progress';preview();}const a=b.dataset.goalAction;if(a==='home')await options.home();if(a==='add')await add();if(a==='duplicate')await add(true);if(a==='image')await imagePicker();if(a==='zoom'){zoom=document.createElement('dialog');zoom.className='goal-preview-zoom';zoom.innerHTML='<button data-zoom-close>返回目标编辑</button><div class="goal-preview-frame"></div>';document.body.append(zoom);zoom.querySelector('[data-zoom-close]').onclick=()=>{observer.unobserve(zoom.querySelector('.goal-preview-frame'));zoom.close();zoom.remove();zoom=null;};zoom.oncancel=e=>{e.preventDefault();zoom.querySelector('[data-zoom-close]').click();};zoom.onclick=e=>{if(e.target.closest('[data-goal-native-button]')){if(S.previewState==='progress')S.focused=!S.focused;else S.previewState='progress';preview();}};zoom.showModal();observer.observe(zoom.querySelector('.goal-preview-frame'));preview();}})().catch(error);};
 host.oninput=e=>{const el=e.target;if(el.hasAttribute('data-goal-search')){S.query=el.value;list();return;}if(el.dataset.goalJson){try{const v=JSON.parse(el.value);delete S.invalid[el.dataset.goalJson];change(()=>row()[el.dataset.goalJson]=v,el.dataset.goalJson);}catch{S.invalid[el.dataset.goalJson]=true;notify();}return;}if(el.hasAttribute('data-goal-preview-round')){const n=Number(el.value);if(Number.isInteger(n)&&n>=1){S.currentRound=n;preview();}return;}if(!el.dataset.goalField)return;const field=el.dataset.goalField,raw=el.value,numeric=el.hasAttribute('data-number'),value=el.hasAttribute('data-boolean')?raw==='true':numeric?Number(raw):raw;if(numeric&&(!raw.trim()||!Number.isFinite(value)||field!=='weight'&&!Number.isInteger(value)||['round','targetRound','weight'].includes(field)&&value<0)){S.invalid[field]=true;el.setAttribute('aria-invalid','true');notify();return;}delete S.invalid[field];el.removeAttribute('aria-invalid');try{change(()=>row()[field]=value,field);list();preview();}catch(e){error(e);}};
 host.onchange=e=>{if(e.target.hasAttribute('data-goal-preview-state')){S.previewState=e.target.value;preview();}};
 host.oncontextmenu=e=>{const card=e.target.closest('[data-goal-id]');if(!card||options.project.readOnly)return;e.preventDefault();const id=card.dataset.goalId,r=rows()[id];UI.choices(r.name||'目标',S.source==='reference'?[{id:'duplicate',name:'在当前模组创建副本'}]:[{id:'duplicate',name:'创建副本'},{id:'delete',name:'删除目标'}]).then(async picked=>{if(!alive)return;if(picked?.id==='delete')await remove(id);if(picked?.id==='duplicate'){S.selected=id;await add(true);}}).catch(error);};
 const premise=e=>{if(!S.data||!S.saved)return;if(e.detail.projectId!==options.project.id)return;const clean=v=>window.STUDIO_STRIP_PREMISES?.(v,new Set(e.detail.pairs));clean(S.rows);clean(S.refs);for(const stack of ['undo','redo'])S[stack]=S[stack].map(text=>{const v=JSON.parse(text);clean(v.rows);return JSON.stringify(v);});const baseline=JSON.parse(S.saved);clean(baseline.rows);S.saved=JSON.stringify(baseline);S.revision=e.detail.revision;render();};window.addEventListener('studio-premises-removed',premise);const onPremiseCreated=e=>{if(options.project.id===e.detail.projectId&&S.revision===e.detail.previousRevision){S.revision=e.detail.revision;notify();}};window.addEventListener('studio-premise-created',onPremiseCreated);
 return {jsonRead:name=>{const path={"IntentCfg": ["rows"]}[name];if(!path||!S.data)return null;return path.reduce((v,k)=>v?.[k],JSON.parse(snapshot()));},
 jsonWrite(name,rows){const path={"IntentCfg": ["rows"]}[name];if(!path)return false;if(readonly()||S.busy)throw Error('当前页面暂不可编辑。');const data=JSON.parse(snapshot());let parent=data;for(const k of path.slice(0,-1))parent=parent[k];if(JSON.stringify(parent[path.at(-1)])===JSON.stringify(rows))return true;S.undo.push(snapshot());if(S.undo.length>60)S.undo.shift();S.redo=[];parent[path.at(-1)]=structuredClone(rows);restored(JSON.stringify(data));notify();return true;},
 jsonSaved(name,rows,revision){const path={"IntentCfg": ["rows"]}[name];if(!path)return;const data=JSON.parse(S.saved);let parent=data;for(const k of path.slice(0,-1))parent=parent[k];parent[path.at(-1)]=structuredClone(rows);S.saved=JSON.stringify(data);S.revision=revision;notify();},load,save,dirty,snapshot,restore:restored,discard(){restored(S.saved);S.undo=[];S.redo=[];notify();},undo:()=>history('undo','redo'),redo:()=>history('redo','undo'),delete:remove,focusSearch:()=> $('[data-goal-search]')?.focus(),destroy(){window.removeEventListener('studio-premise-created',onPremiseCreated);alive=false;observer.disconnect();host.onclick=host.oninput=host.onchange=host.oncontextmenu=null;zoom?.close();zoom?.remove();window.removeEventListener('studio-premises-removed',premise);host.replaceChildren();},navigation:{capture:()=>({selected:S.selected,tab:S.tab,source:S.source,query:S.query}),restore(v){Object.assign(S,{selected:v.selected||Object.keys(S.rows)[0],tab:v.tab||'basic',source:v.source||'local',query:v.query||''});render();}}};
}
window.StudentAgeGoals={create};})();
