/* Workshop shortcuts share the editors' catalogues; browsing never creates records. */
(()=>{'use strict';
const UI=()=>StudentAgeCharacterUI,esc=v=>UI().esc(v);
const definitions=[['portraits','立绘与服装','按人物与服装筛选立绘。'],['expressions','人物表情','查看立绘的表情差分。'],['item-images','物品图片','查看原版、模组与自己的物品图片。'],['social-images','动态配图','按角色查找企鹅动态照片。'],['goal-images','目标图像','查看用于目标的人物头像。'],['emojis','企鹅表情','查看短信、评论和动态使用的表情。'],['map-images','地图素材','查看原版地图画面与各地点的场景图片。'],['conditions','条件目录','查找条件与保存的条件配置。'],['effects','效果目录','分类查看效果及其参数。'],['action-library','行动目录','按分类与地点查找行动。'],['event-types','事件类型目录','查看事件类型与触发参数。']];
const entries=definitions.filter(([id])=>!['conditions','effects','action-library','event-types'].includes(id)).map(([library,label,description])=>({id:'library-'+library,library,label,description,resourceOnly:true,native:true}));
async function referenceData(context,kind){const templates=context.info.commands?.[kind]||[],names=[...new Set(['PersonCfg','PersonAttrCfg',kind==='effect'?'EffectTypeCfg':'ConditionTypeCfg',...templates.flatMap(t=>(t.parameters||[]).map(p=>p.range?.table).filter(Boolean))])],tables=await Promise.all(names.map(name=>context.api('/api/table?'+new URLSearchParams({projectId:context.project.id,name}))));return {templates,refs:Object.fromEntries(tables.map(t=>[t.name,t.rows])),localIds:Object.fromEntries(tables.map(t=>[t.name,t.localIds])),projectId:context.project.id};}
async function open(id,context){
 if(['conditions','effects'].includes(id)){const opts=await referenceData(context,id==='effects'?'effect':'condition');return (id==='effects'?StudentAgeEffects:StudentAgeConditionLibrary).open({...opts,rows:[]});}
 if(id==='event-types')return UI().eventType(context.project.id,0);
 if(id==='map-images')return maps(context);
 if(id==='action-library'){const data=await context.api('/api/table?'+new URLSearchParams({projectId:context.project.id,name:'ActionCfg'}));return StudentAgeEventBindings.actionPicker(context.project.id,Object.values(data.rows));}
 if(id==='emojis'){const d=document.createElement('dialog');d.className='social-dialog social-emoji-dialog';const atlas='/api/social-emojis?'+new URLSearchParams({token:context.token});d.innerHTML='<header><h2>企鹅表情素材库</h2><button data-close>×</button></header><div class="social-emoji-grid">'+StudentAgeSocialMedia.glyphs.map((g,i)=>'<button data-emoji="'+i+'" title="表情 '+i+'">'+StudentAgeSocialMedia.renderText('<sprite='+i+'>',atlas)+'</button>').join('')+'</div><p role="status">点击表情查看它在游戏中的编号。</p>';document.body.append(d);const close=()=>{d.close();d.remove();};d.onclick=e=>{if(e.target.closest('[data-close]'))close();const b=e.target.closest('[data-emoji]');if(b)d.querySelector('[role=status]').textContent='表情 '+b.dataset.emoji+' · <sprite='+b.dataset.emoji+'>';};d.oncancel=e=>{e.preventDefault();close();};d.showModal();return;}
 const kind={'portraits':'portrait','expressions':'portrait','item-images':'item','social-images':'social','goal-images':'portrait'}[id];
 const extraImages=id==='goal-images'?(await context.api('/api/goals?'+new URLSearchParams({projectId:context.project.id}))).images:{};
 return images({...context,extraImages,kind,title:definitions.find(x=>x[0]===id)?.[1]+'素材库',full:true,mode:id==='expressions'?'expression':'portrait',headshot:id==='goal-images',revision:()=>window.STUDIO_PICKER_CONTEXT().revision});
}
// Original map art: each MapCfg location with its scene backgrounds, then the map screen sprites.
async function maps(context){
 const {project,api,token}=context,data=await api('/api/map-library?'+new URLSearchParams({projectId:project.id}));
 const d=document.createElement('dialog');d.className='catalogue-warehouse warehouse-icon-picker map-library';d.dataset.full='true';document.body.append(d);
 const src=(path,thumbnail=true)=>'/api/assets?'+new URLSearchParams({projectId:project.id,path,token,...(thumbnail?{thumbnail:'1'}:{})});
 const card=(image,label)=>`<button data-map-image="${esc(image.path)}" data-map-label="${esc(label)}"><img loading="lazy" src="${esc(src(image.path))}" alt="${esc(label)}"><strong>${esc(label)}</strong></button>`;
 let query='';
 const paint=()=>{const match=(...v)=>!query||StudentAgeSearch.matches(query,...v);
  const places=data.locations.map(l=>({...l,images:l.images.filter(i=>match(l.name,l.shortName,i.name,i.path))})).filter(l=>l.images.length);
  const screens=data.screens.filter(s=>match(s.name,s.path));
  d.querySelector('[data-map-body]').innerHTML=(places.length?'<h3>地点场景</h3>'+places.map(l=>`<section class="map-library-place"><h4>${esc(l.name)}${l.shortName&&l.shortName!==l.name?` <small>${esc(l.shortName)}</small>`:''} <small>地点 ${esc(l.id)}</small></h4><div class="warehouse-grid">${l.images.map(i=>card(i,i.name)).join('')}</div></section>`).join(''):'')+(screens.length?`<h3>地图画面</h3><div class="warehouse-grid">${screens.map(s=>card(s,s.name)).join('')}</div>`:'')||'<p>没有符合搜索的地图素材。</p>';};
 d.innerHTML=`<header><h2>地图素材库</h2><button data-map-reveal title="在文件管理器中打开全部地图素材，文件按地点与名称排列">打开缓存位置</button><button data-map-close aria-label="关闭素材库">×</button></header><div class="warehouse-search"><input data-map-search placeholder="搜索地点或图片名称"></div><p role="status">原版 ${data.locations.length} 个地点、${data.screens.length} 张地图画面。点击图片查看大图。</p><div class="map-library-preview" hidden><img alt=""><p></p><button data-map-preview-close>收起大图</button></div><div class="map-library-body" data-map-body></div>`;
 const say=t=>{d.querySelector('[role=status]').textContent=t;};
 let resolve;const done=new Promise(r=>resolve=r),end=()=>{d.close();d.remove();resolve(null);};
 d.oncancel=e=>{e.preventDefault();end();};
 d.querySelector('[data-map-search]').oninput=e=>{query=e.target.value.trim();paint();};
 d.onclick=async e=>{const b=e.target.closest('button');if(!b)return;
  if(b.hasAttribute('data-map-close'))return end();
  if(b.hasAttribute('data-map-preview-close')){d.querySelector('.map-library-preview').hidden=true;return;}
  if(b.dataset.mapImage){const box=d.querySelector('.map-library-preview');box.querySelector('img').src=src(b.dataset.mapImage,false);box.querySelector('img').alt=b.dataset.mapLabel;box.querySelector('p').textContent=b.dataset.mapLabel+' · '+b.dataset.mapImage;box.hidden=false;box.scrollIntoView({block:'nearest'});return;}
  if(b.hasAttribute('data-map-reveal')){b.disabled=true;try{const r=await api('/api/map-library-reveal',{projectId:project.id});say('已打开地图素材文件夹：'+r.count+' 个文件'+(r.skipped?'，另有 '+r.skipped+' 个尚未缓存':'')+'。');}catch(error){say(error.message||String(error));}finally{b.disabled=false;}}
 };
 paint();d.showModal();return done;
}
async function images(options){const {kind,project,api,token}=options,d=document.createElement('dialog');d.className='catalogue-warehouse warehouse-icon-picker';d.dataset.full=String(!!options.full);let source=window.STUDIO_ORIGINAL_MODE?.()?'original':options.full?'custom':'original',sourceProjectId='',query='',category='',affection='',person='',page=0,sequence=0,items=[],folders=null,closed=false,busy=false,imageObserver=null;const imageTimers=new Set();document.body.append(d);
 const refreshOnFocus=()=>{if(!closed&&!busy&&d.open)reload();};window.addEventListener('focus',refreshOnFocus);
 const end=value=>{if(busy)return;window.removeEventListener('focus',refreshOnFocus);closed=true;sequence++;imageObserver?.disconnect();imageTimers.forEach(clearTimeout);d.close();d.remove();resolve(value);};let resolve;const promise=new Promise(r=>resolve=r),q=s=>d.querySelector(s),say=e=>{if(!closed)q('[role=status]').textContent=e?.message||String(e||'');};
 d.innerHTML=`<header><h2>${esc(options.title||'物品图片素材库')}</h2><button data-lib-reveal title="在文件管理器中打开当前列表的素材，文件按名称排列">打开缓存位置</button><button data-lib-close aria-label="关闭素材库">×</button></header><nav class="character-filters">${[['original','原版'],['mod','模组'],['custom','自定义']].map(([s,l])=>`<button data-lib-source="${s}">${l}</button>`).join('')}</nav><div class="library-folders" hidden><input data-lib-folder placeholder="选择一个文件夹作为固定素材库"><button data-lib-browse>选择文件夹</button><button data-lib-read>读取文件夹</button></div><select data-lib-project hidden aria-label="来源模组"><option value="">全部模组</option>${(window.STUDIO_PROJECTS?.()||[]).map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('')}</select><nav class="character-filters" data-lib-affection ${kind!=='portrait'?'hidden':''}>${[['','全部人物'],['yes','好感角色'],['no','非好感角色']].map(([v,l])=>`<button data-lib-affection-value="${v}">${l}</button>`).join('')}</nav><div class="warehouse-search"><input data-lib-search placeholder="搜索名称"><button data-lib-refresh title="重新扫描新增或修改的素材">刷新</button><select data-lib-category aria-label="素材分类"><option value="">全部分类</option></select><select data-lib-person aria-label="配图角色" hidden></select></div><p role="status"></p><div class="warehouse-grid"></div><footer><button data-lib-page="-1">上一页</button><span data-lib-count></span><button data-lib-page="1">下一页</button></footer>`;
 const params=()=>({projectId:project.id,revision:options.revision(),kind,source,sourceProjectId,q:query,page:String(page),pageSize:'36',variantMode:options.mode||'portrait',...(kind==='portrait'?{affection,clothingCategory:category}:kind==='item'?{type:category}:{}),personName:source==='custom'?'':person});
 const url=(item,thumbnail=false)=>item.previewUrl+'&'+new URLSearchParams({token,...(thumbnail?{thumbnail:'1'}:{}),...(options.headshot?{headshot:'1'}:{})});
 async function reload(){imageObserver?.disconnect();const serial=++sequence;q('.warehouse-grid').innerHTML='<p>正在读取素材…</p>';q('.library-folders').hidden=source!=='custom';q('[data-lib-project]').hidden=source!=='mod';d.querySelectorAll('[data-lib-source]').forEach(b=>b.classList.toggle('active',b.dataset.libSource===source));d.querySelectorAll('[data-lib-affection-value]').forEach(b=>b.classList.toggle('active',b.dataset.libAffectionValue===affection));try{const result=await api('/api/asset-catalog?'+new URLSearchParams(params()));if(closed||serial!==sequence)return;items=result.items;page=result.page;if(source==='custom'&&page===0){items=[...Object.entries(options.extraImages||{}).filter(([id,r])=>!query||StudentAgeSearch.matches(query,r.name,id)).map(([id,r])=>({assetId:'goal:'+id,name:r.name,origin:'goal',previewUrl:'/api/assets?'+new URLSearchParams({projectId:project.id,path:r.head||r.url})})),...items];}q('.warehouse-grid').innerHTML=items.map((item,i)=>`<button data-lib-item="${i}"><img loading="lazy" data-library-image="${esc(url(item,true))}" alt="${esc(item.name)}"><strong>${esc(item.name)}</strong>${item.expressionName?`<small>${esc(item.expressionName)}</small>`:''}</button>`).join('')||'<p>没有符合筛选条件的素材。</p>';q('[data-lib-count]').textContent=`${result.total} 项 · ${page+1} / ${Math.max(1,Math.ceil(result.total/36))}`;q('[data-lib-page="-1"]').disabled=page===0;q('[data-lib-page="1"]').disabled=(page+1)*36>=result.total;q('[data-lib-person]').hidden=kind!=='social'||source==='custom';q('[data-lib-person]').innerHTML='<option value="">全部角色</option>'+(result.personFilters||[]).map(r=>`<option value="${esc(r.name)}" ${r.name===person?'selected':''}>${esc(r.name)}</option>`).join('');say(result.warnings?.join('；')||'');loadImages(serial);}catch(e){if(serial===sequence){q('.warehouse-grid').innerHTML='';say(e);}}}
 function loadImages(serial){imageObserver=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting){imageObserver.unobserve(e.target);const img=e.target;let attempts=0;const load=async()=>{if(closed||serial!==sequence||!img.isConnected)return;try{const response=await fetch(img.dataset.libraryImage);if(response.status===425&&attempts++<45){const timer=setTimeout(()=>{imageTimers.delete(timer);load();},1000);imageTimers.add(timer);return;}if(!response.ok){img.alt='预览暂不可用';return;}const blob=await response.blob();if(closed||serial!==sequence||!img.isConnected)return;const object=URL.createObjectURL(blob);img.onload=img.onerror=()=>URL.revokeObjectURL(object);img.src=object;}catch{img.alt='预览暂不可用';}};load();}},{root:q('.warehouse-grid'),rootMargin:'160px'});d.querySelectorAll('[data-library-image]').forEach(img=>imageObserver.observe(img));}
 async function setFolder(path){if(!folders)folders=await api('/api/asset-folders');folders=await api('/api/asset-folders',{kind,path,settingsRevision:folders.revision});q('[data-lib-folder]').value=folders.folders[kind]?.path||'';source='custom';page=0;await reload();}
 const inspect=async item=>{const modal=document.createElement('dialog');modal.className='asset-library-detail';modal.innerHTML='<header><h2>'+esc(item.name)+'</h2><button aria-label="关闭预览">×</button></header><img alt="'+esc(item.name)+'" src="'+esc(url(item))+'">';document.body.append(modal);const close=()=>{modal.close();modal.remove();};modal.querySelector('button').onclick=close;modal.oncancel=e=>{e.preventDefault();close();};modal.showModal();};
 d.onclick=async e=>{const b=e.target.closest('button');if(!b||busy)return;try{if(b.hasAttribute('data-lib-close'))return end(null);if(b.hasAttribute('data-lib-reveal')){b.disabled=true;try{const r=await api('/api/asset-catalog-reveal',{...params(),title:(options.title||'素材').replace(/素材库$/,'')});say('已打开素材文件夹：'+r.count+' 个文件'+(r.skipped?'，另有 '+r.skipped+' 个尚未缓存（先在列表中预览即可缓存）':'')+'。');}finally{b.disabled=false;}return;}if(b.hasAttribute('data-lib-refresh'))return reload();if(b.dataset.libSource){source=b.dataset.libSource;category='';q('[data-lib-category]').value='';person='';page=0;return reload();}if(b.hasAttribute('data-lib-affection-value')){affection=b.dataset.libAffectionValue;page=0;return reload();}if(b.dataset.libPage){page+=Number(b.dataset.libPage);return reload();}if(b.hasAttribute('data-lib-browse')){const path=await window.STUDIO_CHOOSE_ASSET_FOLDER?.(kind);if(path)await setFolder(path);return;}if(b.hasAttribute('data-lib-read'))return setFolder(q('[data-lib-folder]').value.trim());if(b.dataset.libItem!==undefined){const item=items[Number(b.dataset.libItem)];if(!options.onSelect)return inspect(item);busy=true;b.disabled=true;try{if(item.imagePath&&(source==='original'||item.sourceProjectId===project.id||source==='custom'&&item.origin==='imported')){await options.onSelect({path:item.imagePath,name:item.name});busy=false;end(item);return;}const response=await fetch(url(item));if(!response.ok)throw Error('图片尚未读取完成，请稍后重试。');const blob=await response.blob(),data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(blob);});await options.onSelect({data,fileName:(item.fileName||item.name+'.png'),name:item.name});busy=false;end(item);}finally{busy=false;b.disabled=false;}}}catch(e){say(e);}};
 d.onchange=e=>{if(e.target.hasAttribute('data-lib-project'))sourceProjectId=e.target.value;else if(e.target.hasAttribute('data-lib-category'))category=e.target.value;else if(e.target.hasAttribute('data-lib-person'))person=e.target.value;else return;page=0;reload();};let timer;d.oninput=e=>{if(!e.target.hasAttribute('data-lib-search'))return;query=e.target.value;page=0;sequence++;clearTimeout(timer);timer=setTimeout(()=>{if(!closed)reload();},180);};d.oncancel=e=>{e.preventDefault();end(null);};d.oncontextmenu=e=>{const b=e.target.closest('[data-lib-item]'),item=b&&items[Number(b.dataset.libItem)];if(source==='custom'&&item?.origin==='folder'&&!project.readOnly)StudentAgeContextMenu(e,'删除自定义素材',async()=>{if(await STUDIO_DELETE_CUSTOM_ASSET(item,params()))await reload();});};d.showModal();
 try{folders=await api('/api/asset-folders');if(closed)return promise;q('[data-lib-folder]').value=folders.folders[kind]?.path||'';if(kind==='item'){const types=await api('/api/table?'+new URLSearchParams({projectId:project.id,name:'ItemTypeCfg'}));if(closed)return promise;q('[data-lib-category]').innerHTML='<option value="">全部类型</option>'+Object.values(types.rows).filter(r=>r.id>0&&r.id<100).map(r=>`<option value="${r.id}">${esc(r.name)}</option>`).join('');}else if(kind==='portrait')q('[data-lib-category]').innerHTML='<option value="">全部服装</option>'+['夏季校服','冬季校服','日常服','其他'].map(c=>`<option>${c}</option>`).join('');else q('[data-lib-category]').hidden=true;await reload();}catch(e){say(e);}return promise;
}
const premiseCache=new Map();
window.addEventListener('studio-premises-removed',event=>{const pairs=new Set(event.detail.pairs),defs=premiseCache.get(event.detail.projectId);if(defs)for(const [key,p] of Object.entries(defs))if(pairs.has(p.eventId+':'+p.slot))delete defs[key];});

async function premiseOptions(options){const projectId=options.projectId||window.STUDIO_CURRENT_PROJECT?.();if(!projectId)return options;if(options.onCreatePremise&&options.getPremises)return options;const current=await UI().api('premise-state?projectId='+encodeURIComponent(projectId));premiseCache.set(projectId,current.premises||{});return {...options,projectId,getPremises:options.getPremises||(()=>premiseCache.get(projectId)||{}),onCreatePremise:options.onCreatePremise||(()=>createPremise(projectId))};}
async function createPremise(projectId){const current=await UI().api('project?id='+encodeURIComponent(projectId)),events=Object.values(current.events||current.doc?.events||{});const eventRows=events.length?events:Object.values((await UI().api('table?'+new URLSearchParams({projectId,name:'EvtCfg'}))).localRows);if(!eventRows.length)throw Error('请先创建一个剧情事件，再创建前提。');const proposal=await UI().api('premises/new',{projectId,revision:current.revision,eventId:Number(eventRows[0].id)}),d=document.createElement('dialog');d.className='character-picker premise-create-dialog';document.body.append(d);let finish;const promise=new Promise(r=>finish=r),end=v=>{d.close();d.remove();finish(v);};d.innerHTML=`<header><h2>创建前提</h2></header><p>前提用作条件的判断标准。例如：获得物品后达成“拿到钥匙”，后续剧情以“拿到钥匙已达成”判断是否触发。</p><label>所属剧情<select data-premise-event>${eventRows.map(e=>`<option value="${e.id}">${esc(e.title||e.name||e.id)}</option>`).join('')}</select></label><label>前提名称<input data-premise-create-name maxlength="120" value="${esc(proposal.premise.name)}"></label><label>前提编号<input data-premise-slot type="number" min="0" max="16777215" step="1" value="${proposal.premise.slot}"></label><p role="status"></p><footer><button data-premise-cancel>取消</button><button class="primary" data-premise-create>创建</button></footer>`;let busy=false;d.oncancel=e=>{e.preventDefault();if(!busy)end(null);};d.onclick=async e=>{if(busy)return;if(e.target.closest('[data-premise-cancel]'))return end(null);const b=e.target.closest('[data-premise-create]');if(!b)return;busy=true;b.disabled=true;try{const name=d.querySelector('[data-premise-create-name]').value.trim(),slot=d.querySelector('[data-premise-slot]').value;if(!name||!slot.trim()||!Number.isInteger(Number(slot)))throw Error('请填写名称和有效的整数编号。');const result=await UI().api('premises/create',{projectId,revision:current.revision,eventId:Number(d.querySelector('[data-premise-event]').value),name,slot:Number(slot)});const defs=premiseCache.get(projectId)||{};defs[result.premise.id]=result.premise;premiseCache.set(projectId,defs);window.dispatchEvent(new CustomEvent('studio-premise-created',{detail:result}));end(result.premise);}catch(error){d.querySelector('[role=status]').textContent=error.message;}finally{busy=false;b.disabled=false;}};d.showModal();return promise;}
window.StudentAgeLibraries={entries,open,images,premiseOptions,getPremises:projectId=>premiseCache.get(projectId||window.STUDIO_CURRENT_PROJECT?.())||{}};
})();
