/* Phone message authoring and an isolated, non-mutating native-layout player. */
(()=>{'use strict';
const UI=StudentAgeCharacterUI,G=StudentAgeMessageGraph,esc=UI.esc,clone=v=>structuredClone(v);
function create(host,options){
 const api=options.api,S={data:null,rows:{},editor:{titles:{},previewDelays:{}},source:'local',root:null,selected:null,choices:{},query:'',saved:'',revision:null,busy:false,undo:[],redo:[],last:null,native:null,resourceError:'',invalid:{}};
 const branchFolds=new Map();
 let alive=true,previewDialog=null,sim=null,contact=null,previewRoot=null;
 const $=s=>host.querySelector(s),readonly=()=>!!options.project.readOnly||S.source==='reference',rows=()=>S.source==='reference'?S.data?.table.referenceRows||{}:S.rows;
 const root=()=>rows()[S.root],row=()=>rows()[S.selected],path=()=>G.path(rows(),S.root,S.choices),account=id=>S.data.accounts.find(a=>Number(a.id)===Number(id)),name=id=>Number(id)===0?'白雨':account(id)?.personName||account(id)?.name||'未选择联系人';
 const snapshot=()=>JSON.stringify({rows:S.rows,editor:S.editor}),invalid=()=>Object.keys(S.invalid).length||!!host.querySelector('[data-effect-invalid],[aria-invalid="true"]'),dirty=()=>!!S.data&&(snapshot()!==S.saved||!!invalid());
 const title=r=>S.editor.titles[r.id]||r.content?.replace(/<[^>]*>/g,'').slice(0,32)||name(r.role)+'的短信';
 const nativeURL=file=>'/api/phone-ui?'+new URLSearchParams({resource:file,token:options.token});
 const media=StudentAgeSocialMedia.create({api,token:options.token,project:options.project,revision:()=>S.revision});
 const rich=text=>media.render(text||'');
 function notify(){options.onState?.({busy:S.busy,dirty:dirty(),readOnly:!!options.project.readOnly,canUndo:!!S.undo.length,canRedo:!!S.redo.length,revision:S.revision});host.querySelectorAll('[data-message-save]').forEach(b=>b.disabled=!!options.project.readOnly||S.busy||!dirty());host.querySelectorAll('.messages-settings fieldset').forEach(f=>f.disabled=readonly()||S.busy);}
 function error(e){options.status(e.message||String(e),true);const n=$('[data-message-error]');if(n)n.textContent=e.message||String(e);window.STUDIO_REPORT_ERROR?.(e);}
 function change(fn,key=null){if(readonly()||S.busy)throw Error('当前短信不可编辑。');if(!key||S.last!==key){S.undo.push(snapshot());if(S.undo.length>50)S.undo.shift();}S.last=key;S.redo=[];fn();notify();}
 function restore(text){const d=JSON.parse(text);S.rows=d.rows;S.editor=d.editor;S.invalid={};S.last=null;if(!rows()[S.root])S.root=String(G.roots(rows())[0]?.id||'');if(!rows()[S.selected])S.selected=S.root;render();}
 function history(from,to){if(options.project.readOnly||S.busy||!S[from].length)return;S.source='local';S[to].push(snapshot());restore(S[from].pop());}
 async function load(){S.busy=true;notify();try{const d=await api('/api/messages?'+new URLSearchParams({projectId:options.project.id}));if(!alive)return;S.data=d;S.rows=clone(d.table.localRows);S.editor={titles:{},previewDelays:{},...clone(d.editor)};S.revision=d.revision;S.saved=snapshot();S.invalid={};S.undo=[];S.redo=[];S.root=rows()[S.root]?S.root:String(G.roots(rows())[0]?.id||'');S.selected=S.root;render();loadNative();}finally{S.busy=false;if(alive)notify();}}
 async function loadNative(){try{const d=await api('/api/phone-ui');if(!alive)return;S.native=d;S.resourceError='';if(d.fonts?.body){const f=new FontFace('MessageNative',`url("${nativeURL(d.fonts.body)}")`);f.load().then(font=>{if(alive)document.fonts.add(font);}).catch(()=>{});}renderPhone();paintPreview();}catch(e){if(alive){S.resourceError=e.message;renderPhone();paintPreview();}}}
 function sprite(key,extra=''){const info=S.native?.sprites?.[key];if(!info)return '';const url=esc(nativeURL(info.file)),b=info.border||[0,0,0,0];return b.some(n=>n>0)?`<span class="message-native-sprite ${extra}" style="border-width:${b.map(n=>n+'px').join(' ')};border-image-source:url('${url}');border-image-slice:${b.join(' ')} fill" aria-hidden="true"></span>`:`<img class="message-native-sprite ${extra}" src="${url}" alt="">`;}
 function bubble(r,editing=false){return `<div class="message-native-row ${r.role===0?'outgoing':'incoming'}"><button ${editing?`data-message-select="${r.id}"`: 'tabindex="-1"'} class="message-native-bubble ${editing&&String(r.id)===S.selected?'editing':''}">${sprite(r.role===0?'right':'left')}<span>${rich(r.content||'点击填写短信')}</span></button></div>`;}
 function phone(content,heading,editing=false,footer=''){return `<div class="message-native-phone">${sprite('screen','message-native-screen')}${sprite('wallpaper','message-native-wallpaper')}${sprite('frame','message-native-frame')}<div class="message-native-status"><span>12:00</span></div>${sprite('battery','message-native-battery')}${sprite('signal','message-native-signal')}<header class="message-native-heading">${sprite('title')}<strong>${esc(heading)}</strong></header><section class="message-native-scroll">${content}</section>${footer}<button class="message-native-back" ${editing?'data-message-action="preview"':'data-message-preview-back'} title="${editing?'进入游戏预览':'返回联系人'}">${sprite('back')}<span class="sr-only">${editing?'进入游戏预览':'返回'}</span></button></div>`;}
 const resize=new ResizeObserver(entries=>entries.forEach(e=>fit(e.target)));
 function fit(frame){const canvas=frame?.querySelector('.message-native-phone');if(canvas)canvas.style.transform=`translate(-50%,-50%) scale(${Math.min(frame.clientWidth/917,frame.clientHeight/1393)})`;}
 function render(){if(!S.data||!alive)return;resize.disconnect();host.innerHTML=`<section class="messages-workspace"><aside class="messages-sidebar"><button class="text-button" data-message-action="home">← 工坊主页</button><header><h2>短信</h2><button class="primary" data-message-action="new" ${options.project.readOnly?'disabled':''}>＋ 创建短信</button></header><nav class="character-filters"><button data-message-source="local" class="${S.source==='local'?'active':''}">${options.project.originalMode?'原版 · 保存到当前模组':'当前模组'}</button><button data-message-source="reference" class="${S.source==='reference'?'active':''}">原版参考</button></nav><input data-message-search value="${esc(S.query)}" placeholder="搜索联系人或短信"><div data-message-list></div><section class="messages-branches"><h3>回复分支</h3><div data-message-branches></div></section></aside><main class="messages-center"><header><strong>${root()?esc(name(root().role)):'短信编辑'}</strong><button data-message-action="preview">游戏内预览</button></header><div class="message-phone-frame" data-message-phone></div><div class="messages-compose-buttons">${root()&&!readonly()?`<button data-message-action="append-contact">＋ 添加${esc(name(root().role))}信息</button><button data-message-action="append-player">＋ 添加白雨信息</button><button data-message-action="alternative">＋ 添加第二种回复</button>`:''}</div><p class="helper">选择气泡可编辑，点击“游戏内预览”可从联系人开始试发短信。</p></main><aside class="messages-settings"><header><h3>短信设置</h3><button class="primary" data-message-save>保存</button></header><div data-message-form></div><p data-message-error role="status"></p></aside></section>`;renderList();renderBranches();renderPhone();renderForm();notify();}
 function renderList(){const n=$('[data-message-list]');if(!n)return;n.innerHTML=G.roots(rows()).filter(r=>StudentAgeSearch.matches(S.query,r.id,title(r),name(r.role))).map(r=>`<button class="message-list-card ${String(r.id)===S.root?'active':''}" data-message-root="${r.id}">${account(r.role)?.avatarUrl?`<img src="${esc(account(r.role).avatarUrl)}" alt="">`:''}<span><strong>${esc(name(r.role))}</strong><span>${esc(title(r))}</span><small>${r.id} · ${G.reachable(rows(),r.id).size} 条消息</small></span></button>`).join('')||'<p class="helper">创建短信后选择发送消息的人。</p>';}
 function renderBranches(){const n=$('[data-message-branches]');if(!n)return;const scope=S.source+':'+S.root;if(!branchFolds.has(scope))branchFolds.set(scope,new Set());StudentAgeBranchTree.mount(n,G.branches(rows(),S.root),{choices:S.choices,collapsed:branchFolds.get(scope),attributes:i=>`data-message-branch="${i}"`,title:entry=>rows()[entry.id]?.option||rows()[entry.id]?.content||'白雨回复'});}
 function renderPhone(){const frame=$('[data-message-phone]');if(!frame)return;frame.innerHTML=!root()?'<div class="messages-empty">先创建一段短信</div>':!S.native?`<div class="messages-empty">${esc(S.resourceError||'正在加载手机界面…')}</div>`:phone('<p class="message-native-time">短信</p>'+path().map(r=>bubble(r,true)).join(''),name(root().role),true);resize.observe(frame);fit(frame);}
 function renderForm(){const node=$('[data-message-form]'),r=row();if(!node)return;if(!r){node.innerHTML='<p class="helper">选择短信气泡查看设置。</p>';return;}const first=String(r.id)===S.root,player=r.role===0,unknown=Object.fromEntries(Object.entries(r).filter(([k])=>!['id','role','content','next','option','cond','effect'].includes(k)));
 node.innerHTML=`<fieldset ${readonly()||S.busy?'disabled':''}>${first?`<label>短信名称<input data-message-title value="${esc(S.editor.titles[r.id]||'')}" placeholder="仅用于编辑时区分短信"></label><button data-message-action="sender">发送人：${esc(name(r.role))} · 更换</button>`:`<strong>${esc(name(r.role))}的信息</strong>`}<button data-record-table="PhoneMsgCfg" data-record-id="${r.id}">编号 ${r.id} · 修改</button><label>短信内容<textarea id="message-content" data-message-content rows="4">${esc(r.content||'')}</textarea></label><button data-message-action="emoji">☺ 表情</button>${player?`<label>回复选项文字<input data-message-option value="${esc(r.option||'')}" placeholder="默认与短信内容相同"></label>`:!first?`<label>预览等待时间（秒）<input type="number" min="0" max="120" step="0.1" data-message-delay value="${S.editor.previewDelays[r.id]??1.2}"></label><p class="helper">只影响编辑器预览。游戏中使用原版正在输入动画。</p>`:''}<details open><summary>${first?'短信触发条件':player?'回复可选条件':'此条回复的出现条件'}</summary><div data-message-command="cond"></div></details><details open><summary>阅读／发送后的效果</summary><div data-message-command="effect"></div></details>${Object.keys(unknown).length?`<details><summary>其他原有参数</summary><textarea data-message-extra>${esc(JSON.stringify(unknown))}</textarea></details>`:''}<button data-message-action="delete-node" class="danger-text">删除${first?'这段短信':'此消息及后续分支'}</button></fieldset>`;
 for(const n of node.querySelectorAll('[data-message-command]')){const field=n.dataset.messageCommand,condition=field==='cond',lib=condition?StudentAgeConditions:StudentAgeEffects;lib.mount(n,{rows:r[field]||[],templates:S.data.commands[condition?'condition':'effect'],refs:{...S.data.refs,PhoneMsgCfg:{...S.data.table.referenceRows,...S.rows}},localIds:S.data.localIds,projectId:options.project.id,readOnly:readonly(),description:first&&condition?'满足时自动收到这段短信。':'',emptyText:first&&condition?'留空时由剧情的“发出短信”效果触发。':'空列表不限制。',onChange:value=>{change(()=>r[field]=value);renderList();},onError:error});}notify();}
 async function pickSender(){const a=await UI.choices('选择发送短信的人',S.data.accounts.filter(r=>Number(r.id)>0&&S.data.refs.PersonCfg[r.id]).map(r=>({...r,name:r.personName||r.name})),{image:r=>r.avatarUrl});return a?.id;}
 function newId(){return STUDIO_IDS.allocate('PhoneMsgCfg',{...S.data.table.rows,...S.rows});}
 function nextId(){const start=Math.floor(Number(S.root)/100)*100;for(let id=start+2;id<=start+99;id++)if(!S.data.table.rows[id]&&!S.rows[id])return id;throw Error('这段短信已达到原版同组的 99 条上限，请新建另一段短信。');}
 async function newConversation(){if(invalid())throw Error('请先完成当前参数。');const role=await pickSender();if(role==null)return;S.source='local';change(()=>{const id=newId();S.rows[id]={...clone(S.data.defaults),id,role:Number(role)};S.root=S.selected=String(id);S.choices={};});render();$('#message-content')?.focus();}
 async function textDialog(heading){const d=document.createElement('dialog');d.className='message-text-dialog';document.body.append(d);return new Promise(resolve=>{d.innerHTML=`<header><h2>${esc(heading)}</h2></header><textarea rows="5" placeholder="输入短信内容"></textarea><footer><button data-cancel>取消</button><button class="primary" data-submit>添加</button></footer><p role="status"></p>`;const finish=v=>{d.close();d.remove();resolve(v);};d.onclick=e=>{if(e.target.closest('[data-cancel]'))finish(null);if(e.target.closest('[data-submit]')){const text=d.querySelector('textarea').value;if(text.trim())finish(text);else d.querySelector('[role=status]').textContent='请填写短信内容。';}};d.oncancel=e=>{e.preventDefault();finish(null);};d.showModal();d.querySelector('textarea').focus();});}
 async function append(player,alternative=false){if(!root()||readonly())return;if(invalid())throw Error('请先完成当前参数。');let owner=alternative?row():path().at(-1);if(!owner)owner=root();if(alternative&&owner.role===0){const parent=path().find(r=>(r.next||[]).includes(owner.id));if(parent)owner=parent;}const next=owner.next||[];if(alternative&&(next.length>=2||next.length&&rows()[next[0]]?.role!==0))throw Error('请选择已有白雨回复的上一条消息，每次最多两个回复。');if(!alternative&&next.length)throw Error('请在左侧选择要继续编辑的分支。');const originalRoot=S.root,ownerId=owner.id,text=await textDialog(player?'添加白雨信息':'添加'+name(root().role)+'信息');if(text===null||S.root!==originalRoot||rows()[ownerId]!==owner)return;
 change(()=>{if(!player&&String(owner.id)===S.root&&!next.length){owner.content=(owner.content?owner.content+'\n':'')+text;S.selected=String(owner.id);return;}const id=nextId();S.rows[id]={...clone(S.data.defaults),id,role:player?0:root().role,content:text,option:player?text:''};owner.next=[...next,id];S.selected=String(id);S.choices={...S.choices,[owner.id]:id};});render();}
 async function removeSelected(){if(readonly()||!row())return;const id=S.selected,selected=row(),yes=await UI.choices('删除这条短信及后续分支？',[{id:'cancel',name:'取消'},{id:'delete',name:'删除'}]);if(yes?.id!=='delete'||rows()[id]!==selected)return;change(()=>{const removed=G.remove(S.rows,id);for(const n of removed){delete S.editor.titles[n];delete S.editor.previewDelays[n];}if(!root())S.root=String(G.roots(S.rows)[0]?.id||'');S.selected=S.root;S.choices={};});render();}
 async function duplicate(rootId=S.root){const source=rows(),ids=[...G.reachable(source,rootId)];if(ids.length>99)throw Error('此原版短信超过当前可复制的 99 条上限，请分段整理后复制。');const basis=clone(source),oldTitle=title(source[rootId]);S.source='local';change(()=>{const id=newId(),map=Object.fromEntries(ids.map((old,i)=>[old,id+i]));for(const old of ids){const r=clone(basis[old]);r.id=map[old];r.next=(r.next||[]).map(n=>map[n]||n);for(const [field,kind] of [['cond','condition'],['effect','effect']])for(const command of r[field]||[]){const template=(S.data.commands[kind]||[]).find(t=>command.length===t.template?.length&&Object.entries(t.match||{}).every(([i,v])=>Number(command[i])===Number(v)));for(const parameter of template?.parameters||[])if(parameter.range?.table==='PhoneMsgCfg'&&map[command[parameter.index]])command[parameter.index]=map[command[parameter.index]];}S.rows[r.id]=r;if(S.editor.previewDelays[old]!==undefined)S.editor.previewDelays[r.id]=S.editor.previewDelays[old];}S.root=S.selected=String(id);S.editor.titles[id]=oldTitle+' · 副本';S.choices={};});render();}
 async function save(){if(!dirty())return;if(S.busy||options.project.readOnly)throw Error('当前短信不可保存。');if(invalid()&&!await STUDIO_SAVE_REVIEW.confirm(['短信的条件、效果或参数尚未完成。继续将保存已生效的内容，未能解析的输入沿用上一次有效值。']))return;S.busy=true;notify();try{const result=await api('/api/messages-save',{projectId:options.project.id,revision:S.revision,...JSON.parse(snapshot())});S.rows=result.rows;S.editor=result.editor;S.revision=result.revision;S.data.table.rows={...S.data.table.referenceRows,...S.rows};S.saved=snapshot();S.undo=[];S.redo=[];await options.onSaved?.();render();options.status('短信和回复分支已保存。');}finally{S.busy=false;if(alive)notify();}}
 function stopSimulation(){if(sim)clearTimeout(sim.timer);sim=null;}
 function available(r){return !(r.cond||[]).some(c=>StudentAgeConditions.evaluateExact(c)===false);}
 function advance(){if(!sim)return;const last=rows()[sim.visible.at(-1)],next=(last?.next||[]).map(id=>rows()[id]).filter(Boolean);sim.options=[];if(!next.length){paintPreview();return;}if(next[0].role===0){sim.options=next.filter(available);paintPreview();return;}const r=next[0];if(!available(r)||sim.visible.includes(r.id)){paintPreview();return;}sim.typing=true;paintPreview();const current=sim;sim.timer=setTimeout(()=>{if(sim!==current||!previewDialog?.open)return;sim.typing=false;sim.visible.push(r.id);advance();},(S.editor.previewDelays[r.id]??1.2)*1000);}
 function play(id){stopSimulation();previewRoot=Number(id);sim={visible:[Number(id)],options:[],typing:false,timer:null};advance();}
 function paintPreview(){if(!previewDialog?.open)return;const frame=previewDialog.querySelector('.message-phone-frame');if(!S.native){frame.innerHTML=`<p>${esc(S.resourceError||'正在读取原版手机…')}</p>`;return;}const roots=G.roots(rows()),contacts=[...new Set(roots.map(r=>Number(r.role)))];let content='',footer='',heading='短信';
 if(contact===null)content=contacts.map(id=>`<button class="message-native-contact" data-message-contact="${id}">${sprite('contact')}<strong>${esc(name(id))}</strong><span>${rich(roots.filter(r=>r.role===id).at(-1)?.content||'')}</span></button>`).join('')||'<p class="message-native-time">还没有短信</p>';
 else if(!sim){heading=name(contact);content=roots.filter(r=>Number(r.role)===contact).map(r=>`<button class="message-native-contact" data-message-play="${r.id}">${sprite('contact')}<strong>${esc(title(r))}</strong><span>${rich(r.content)}</span></button>`).join('');}
 else{heading=name(contact);content='<p class="message-native-time">短信</p>'+sim.visible.map(id=>bubble(rows()[id])).join('')+(sim.typing?`<div class="message-native-row incoming"><div class="message-native-bubble typing">${sprite('left')}<span><i></i><i></i><i></i></span></div></div>`:'');if(sim.options.length)footer=`<div class="message-native-options">${sprite('options')}${sim.options.map(r=>`<button data-message-reply="${r.id}">${sprite('option')}<span>${esc(r.option||r.content)}</span></button>`).join('')}</div>`;else if(!sim.typing)content+='<p class="message-native-time">没有更多短信了</p>';}
 frame.innerHTML=phone(content,heading,false,footer);resize.observe(frame);fit(frame);const scroll=frame.querySelector('.message-native-scroll');if(scroll&&sim)scroll.scrollTop=scroll.scrollHeight;
 }
 function openPreview(){if(previewDialog?.open)return;previewDialog=document.createElement('dialog');previewDialog.className='messages-preview-dialog';previewDialog.innerHTML='<header><strong>短信预览</strong><span>按条件满足演示；游戏效果不在预览中执行。</span><button data-message-preview-close>返回编辑</button></header><div class="message-phone-frame"></div>';document.body.append(previewDialog);contact=null;previewRoot=null;stopSimulation();const close=()=>{stopSimulation();resize.unobserve(previewDialog.querySelector('.message-phone-frame'));previewDialog.close();previewDialog.remove();previewDialog=null;};previewDialog.oncancel=e=>{e.preventDefault();close();};previewDialog.onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-message-preview-close'))return close();if(b.hasAttribute('data-message-preview-back')){if(sim){stopSimulation();previewRoot=null;}else contact=null;return paintPreview();}if(b.dataset.messageContact){contact=Number(b.dataset.messageContact);const list=G.roots(rows()).filter(r=>Number(r.role)===contact);if(list.length===1)play(list[0].id);else paintPreview();}if(b.dataset.messagePlay)play(b.dataset.messagePlay);if(b.dataset.messageReply&&sim?.options.some(r=>r.id===Number(b.dataset.messageReply))){sim.visible.push(Number(b.dataset.messageReply));advance();}};previewDialog.showModal();paintPreview();}
 host.onclick=e=>{const b=e.target.closest('button');if(!b){if(e.target.closest('[data-message-phone]')&&root())openPreview();return;}(async()=>{if(b.dataset.messageRoot){if(invalid())throw Error('请先修正当前参数。');S.root=S.selected=b.dataset.messageRoot;S.choices={};S.last=null;render();}if(b.dataset.messageSelect){if(invalid())throw Error('请先修正当前参数。');S.selected=b.dataset.messageSelect;S.last=null;renderPhone();renderForm();}if(b.dataset.messageBranch!==undefined){if(invalid())throw Error('请先修正当前参数。');const branch=G.branches(rows(),S.root)[Number(b.dataset.messageBranch)];S.choices=branch?.choices||{};S.selected=String(branch?.id||S.root);S.last=null;renderBranches();renderPhone();renderForm();}if(b.dataset.messageSource){if(invalid())throw Error('请先修正当前参数。');S.source=b.dataset.messageSource;S.root=S.selected=String(G.roots(rows())[0]?.id||'');S.choices={};render();}if(b.hasAttribute('data-message-save'))await save();const a=b.dataset.messageAction;if(a==='home')await options.home();if(a==='new')await newConversation();if(a==='append-contact')await append(false);if(a==='append-player')await append(true);if(a==='alternative')await append(true,true);if(a==='delete-node')await removeSelected();if(a==='preview')openPreview();if(a==='emoji')media.emoji($('#message-content'));if(a==='sender'){const old=root()?.role,id=await pickSender();if(id!=null){change(()=>{for(const n of G.reachable(S.rows,S.root))if(S.rows[n].role===old)S.rows[n].role=Number(id);});render();}}})().catch(error);};
 host.oninput=e=>{const el=e.target;if(el.hasAttribute('data-message-search')){S.query=el.value;renderList();return;}if(readonly())return;try{if(el.hasAttribute('data-message-content')){const r=row(),old=r.content;change(()=>{r.content=el.value;if(r.role===0&&(!r.option||r.option===old))r.option=el.value;},S.selected+':content');renderPhone();renderList();renderBranches();}if(el.hasAttribute('data-message-title')){change(()=>S.editor.titles[S.selected]=el.value,S.selected+':title');renderList();}if(el.hasAttribute('data-message-option')){change(()=>row().option=el.value,S.selected+':option');renderBranches();}if(el.hasAttribute('data-message-delay')){const value=Number(el.value);if(!el.value.trim()||!Number.isFinite(value)||value<0||value>120){S.invalid.delay=true;el.setAttribute('aria-invalid','true');notify();return;}delete S.invalid.delay;el.removeAttribute('aria-invalid');change(()=>S.editor.previewDelays[S.selected]=value,S.selected+':delay');}if(el.hasAttribute('data-message-extra')){let value;try{value=JSON.parse(el.value);if(!value||Array.isArray(value)||typeof value!=='object'||Object.keys(value).some(k=>['id','role','content','next','option','cond','effect','__proto__','constructor','prototype'].includes(k)))throw Error();}catch{S.invalid.extra=true;el.setAttribute('aria-invalid','true');notify();return;}delete S.invalid.extra;el.removeAttribute('aria-invalid');change(()=>{for(const key of Object.keys(row()))if(!['id','role','content','next','option','cond','effect'].includes(key))delete row()[key];Object.assign(row(),value);},S.selected+':extra');}}catch(e){error(e);}};
 host.oncontextmenu=e=>{const card=e.target.closest('[data-message-root]'),bubble=e.target.closest('[data-message-select]');if((!card&&!bubble)||options.project.readOnly)return;e.preventDefault();const id=card?.dataset.messageRoot||bubble.dataset.messageSelect;UI.choices(card?'短信操作':'消息操作',S.source==='reference'?[{id:'copy',name:'复制这段短信到当前模组'}]:[{id:'copy',name:'创建整段副本'},{id:'delete',name:card?'删除这段短信':'删除此消息及后续分支'}]).then(async choice=>{if(choice?.id==='copy')await duplicate(card?id:S.root);if(choice?.id==='delete'){S.selected=id;if(card)S.root=id;await removeSelected();}}).catch(error);};
 const premise=e=>{if(!S.data||e.detail.projectId!==options.project.id)return;const clean=v=>window.STUDIO_STRIP_PREMISES?.(v,new Set(e.detail.pairs));clean(S.rows);clean(S.data.refs);for(const stack of ['undo','redo'])S[stack]=S[stack].map(text=>{const d=JSON.parse(text);clean(d.rows);return JSON.stringify(d);});const d=JSON.parse(S.saved);clean(d.rows);S.saved=JSON.stringify(d);S.revision=e.detail.revision;render();};window.addEventListener('studio-premises-removed',premise);const onPremiseCreated=e=>{if(options.project.id===e.detail.projectId&&S.revision===e.detail.previousRevision){S.revision=e.detail.revision;notify();}};window.addEventListener('studio-premise-created',onPremiseCreated);
 return {jsonRead:name=>{const path={"PhoneMsgCfg": ["rows"]}[name];if(!path||!S.data)return null;return path.reduce((v,k)=>v?.[k],JSON.parse(snapshot()));},
 jsonWrite(name,rows){const path={"PhoneMsgCfg": ["rows"]}[name];if(!path)return false;if(readonly()||S.busy)throw Error('当前页面暂不可编辑。');const data=JSON.parse(snapshot());let parent=data;for(const k of path.slice(0,-1))parent=parent[k];if(JSON.stringify(parent[path.at(-1)])===JSON.stringify(rows))return true;S.undo.push(snapshot());if(S.undo.length>60)S.undo.shift();S.redo=[];parent[path.at(-1)]=structuredClone(rows);restore(JSON.stringify(data));notify();return true;},
 jsonSaved(name,rows,revision){const path={"PhoneMsgCfg": ["rows"]}[name];if(!path)return;const data=JSON.parse(S.saved);let parent=data;for(const k of path.slice(0,-1))parent=parent[k];parent[path.at(-1)]=structuredClone(rows);S.saved=JSON.stringify(data);S.revision=revision;notify();},load,save,snapshot,dirty,discard(){restore(S.saved);S.undo=[];S.redo=[];notify();},undo:()=>history('undo','redo'),redo:()=>history('redo','undo'),delete:removeSelected,focusSearch:()=>$('[data-message-search]')?.focus(),destroy(){window.removeEventListener('studio-premise-created',onPremiseCreated);alive=false;stopSimulation();resize.disconnect();media.destroy();previewDialog?.close();previewDialog?.remove();window.removeEventListener('studio-premises-removed',premise);host.onclick=host.oninput=host.oncontextmenu=null;host.replaceChildren();},navigation:{capture:()=>({root:S.root,selected:S.selected,choices:S.choices,source:S.source,query:S.query}),restore(v){Object.assign(S,{root:v.root,selected:v.selected,choices:v.choices||{},source:v.source||'local',query:v.query||''});render();}}};
}
window.StudentAgeMessages={create};})();
