/* Native 6x6 social Sudoku: SudokuMiniGameView.OnOpen/Refresh/FillCell.
 * The preview owns its timer and board; it never runs game rewards or writes saves. */
(()=>{'use strict';
const initial=[2,5,4,6,3,1,6,1,3,5,2,4,4,2,6,1,5,3,1,3,5,2,4,6,5,4,1,3,6,2,3,6,2,4,1,5];
function board(empty,random=Math.random){if(!Number.isInteger(empty)||empty<1||empty>36)throw Error('数独关卡空格数必须为 1–36。');const permutation=[];for(let i=1;i<=6;i++)permutation.splice(Math.floor(random()*Math.max(1,permutation.length)),0,i);const answer=initial.map(v=>permutation[(permutation.indexOf(v)+1)%6]),values=[...answer],editable=Array(36).fill(false);let count=0;while(count<empty){const i=Math.floor(random()*36);if(!editable[i]){editable[i]=true;values[i]=0;count++;}}return {answer,values,editable};}
function solved(values){if(values.length!==36||values.some(v=>!Number.isInteger(v)||v<1||v>6))return false;const unique=a=>new Set(a).size===6;for(let row=0;row<6;row++){if(!unique(values.slice(row*6,row*6+6))||!unique(Array.from({length:6},(_,i)=>values[i*6+row])))return false;}for(let r=0;r<6;r+=2)for(let c=0;c<6;c+=3)if(!unique([0,1,2,6,7,8].map(i=>values[r*6+c+i])))return false;return true;}
function mount(host,level){const data=board(Number(level.mode)),history=[];let selected=-1,started=0,ended=false,timer;
host.className='minigame-sudoku';host.innerHTML='<header><strong>数独</strong><span data-sudoku-time>80 秒</span></header><progress max="80" value="80"></progress><div class="sudoku-paper"><div class="sudoku-grid"></div><div class="sudoku-numbers">'+[1,2,3,4,5,6].map(n=>`<button data-sudoku-number="${n}">${n}</button>`).join('')+'</div></div><footer><button data-sudoku-restart>重新开始</button><button data-sudoku-undo disabled>撤销</button><button data-sudoku-clear disabled>清空</button><p role="status">每行、每列和每个 2×3 宫格填入不重复的 1–6。</p></footer>';
const q=s=>host.querySelector(s),status=t=>q('[role=status]').textContent=t;
function paint(){q('.sudoku-grid').innerHTML=data.values.map((v,i)=>`<button data-sudoku-cell="${i}" ${!started||!data.editable[i]||ended?'disabled':''} class="${data.editable[i]?'editable':''} ${selected===i?'selected':''}" aria-label="第 ${Math.floor(i/6)+1} 行第 ${i%6+1} 列" style="border-right-width:${i%6===2?3:1}px;border-bottom-width:${Math.floor(i/6)%2===1?3:1}px">${v||''}</button>`).join('');q('[data-sudoku-undo]').disabled=!history.length||ended;q('[data-sudoku-clear]').disabled=!started||ended;q('.sudoku-numbers').querySelectorAll('button').forEach(b=>b.disabled=selected<0||ended);}
function fill(n){if(selected<0||ended||!started)return;const i=selected;history.push({i,value:data.values[i]});data.values[i]=n;selected=-1;if(solved(data.values)){ended=true;clearInterval(timer);status('挑战成功');}paint();}
const key=e=>{if(!host.isConnected||!e.target.closest('.minigame-sudoku'))return;if(/^[1-6]$/.test(e.key)){e.preventDefault();fill(Number(e.key));}};host.tabIndex=0;host.addEventListener('keydown',key);
function start(){clearInterval(timer);ended=false;started=performance.now();q('progress').value=80;q('[data-sudoku-time]').textContent='80 秒';status('每行、每列和每个 2×3 宫格填入不重复的 1–6。');host.focus();timer=setInterval(()=>{const remaining=Math.max(0,80-(performance.now()-started)/1000);q('progress').value=remaining;q('[data-sudoku-time]').textContent=Math.ceil(remaining)+' 秒';if(!remaining){ended=true;clearInterval(timer);status('时间到了');paint();}},100);paint();}
host.onclick=e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.hasAttribute('data-sudoku-restart')){Object.assign(data,board(Number(level.mode)));history.length=0;selected=-1;start();}if(b.dataset.sudokuCell!==undefined){selected=Number(b.dataset.sudokuCell);paint();host.focus();}if(b.dataset.sudokuNumber)fill(Number(b.dataset.sudokuNumber));if(b.hasAttribute('data-sudoku-clear')){for(let i=0;i<36;i++)if(data.editable[i])data.values[i]=0;selected=-1;paint();}if(b.hasAttribute('data-sudoku-undo')){const last=history.pop();if(last){data.values[last.i]=last.value;selected=last.i;paint();}}};start();
return {data,fill,get running(){return !!started&&!ended;},destroy(){clearInterval(timer);host.removeEventListener('keydown',key);host.onclick=null;host.replaceChildren();}};
}
window.StudentAgeSudoku={board,solved,mount};
})();
