(()=>{'use strict';
const guideIds={5:4005,9:4009,10:4010,20:4020,24:4024,26:4026,46:4035,48:4034};
async function pick({rules,selected,people,growth}){const imageURL=path=>'/api/minigame-image?'+new URLSearchParams({path,token:window.STUDIO_TOKEN});const esc=StudentAgeCharacterUI.esc,d=document.createElement('dialog');d.className='character-picker minigame-library';document.body.append(d);let resolve,current=Number(selected)||5,filter=(rules.pluginGameIds||[]).includes(String(selected))?'plugin':'social',query='',player=null,levelId=null,imageTasks=[],imageEpoch=0;const finishImages=()=>{imageEpoch++;imageTasks.forEach(k=>window.STUDIO_CACHE_TASKS?.finish(k));imageTasks=[];};const result=new Promise(r=>resolve=r),games=Object.values(rules.MinigameCfg||{}),social=new Set(Object.values(growth).map(r=>r.minigame).filter(Boolean));
const pluginIds=new Set((rules.pluginGameIds||[]).map(Number));
const stop=()=>{player?.destroy();player=null;d.classList.remove('minigame-playing');};const close=value=>{finishImages();stop();d.close();d.remove();resolve(value);};
function levels(){return Object.values(rules.MinigameActionCfg||{}).filter(r=>Math.floor(r.id/100)===current).sort((a,b)=>a.id-b.id);}
function paint(){finishImages();stop();const game=games.find(r=>r.id===current),rows=games.filter(g=>(filter==='plugin'?pluginIds.has(g.id):!pluginIds.has(g.id)&&(filter==='all'||social.has(g.id)))&&StudentAgeSearch.matches(query,g.id,g.name)),guide=rules.GuideCfg?.[guideIds[current]*100+1];d.innerHTML=`<header><h2>小游戏库</h2><button data-mini-close aria-label="关闭">×</button></header><nav><button data-mini-filter="social" aria-pressed="${filter==='social'}">人物社交</button><button data-mini-filter="all" aria-pressed="${filter==='all'}">原版小游戏</button>${pluginIds.size?`<button data-mini-filter="plugin" aria-pressed="${filter==='plugin'}">插件</button>`:''}<input data-mini-search placeholder="搜索小游戏" value="${esc(query)}"></nav><div class="minigame-library-layout"><div class="minigame-library-list">${rows.map(g=>{const guide=rules.GuideCfg?.[guideIds[g.id]*100+1];return `<button data-mini-id="${g.id}" class="${g.id===current?'active':''}">${guide?.url?`<img src="${esc(imageURL(guide.url))}" alt="${esc(g.name)}原版说明配图">`:'<span class="minigame-no-image">暂无原版说明配图</span>'}<strong>[${g.id}] ${esc(g.name)}</strong></button>`;}).join('')}</div><section class="minigame-library-detail"><h3>${esc(game?.name||'选择小游戏')}</h3><p>${esc(Object.values(growth).filter(r=>r.minigame===current).map(r=>people[r.id]?.name||'人物 '+r.id).join('、'))}</p>${guide?.url?`<img class="minigame-native-guide" src="${esc(imageURL(guide.url))}" alt="原版玩法说明"><p>${esc((guide.tips||'').replace(/<[^>]+>/g,''))}</p>`:''}<section class="minigame-level-section"><h4>选择关卡</h4><div class="minigame-levels">${levels().map((r,i)=>`<button data-mini-level="${r.id}" aria-pressed="${(levelId||levels()[0]?.id)===r.id}" title="精力消耗 ${r.cost}">${i+1}</button>`).join('')||'<p>原版未配置社交关卡</p>'}</div></section><p>${esc(game?.tips||'')}</p><div data-mini-stage></div><p class="minigame-status" role="status">${current===5?'数独复刻试玩：原版 6×6、关卡空格数及 80 秒限时；画面与原版逐帧对照尚未完成。':current===28?'原版“卖货”入口直接结算社交成功，没有独立小游戏画面。':'此小游戏的试玩尚未接入。'}</p><footer><button data-mini-back hidden>返回关卡</button><button data-mini-play ${current===5&&levels().length?'':'disabled'}>在编辑器中试玩</button><button data-mini-select class="primary" ${game?'':'disabled'}>关联此小游戏</button></footer></section></div>`;
d.querySelector('[data-mini-search]').oninput=e=>{query=e.target.value;const old=e.target,position=old.selectionStart;paint();const next=d.querySelector('[data-mini-search]');next.focus();next.setSelectionRange(position,position);};const images=[...d.querySelectorAll('img')],epoch=imageEpoch,task='minigame-images:'+epoch;let remaining=images.length;const progress=()=>{if(epoch!==imageEpoch)return;if(remaining)window.STUDIO_CACHE_TASKS?.update(task,'读取小游戏配图',Math.round(100*(images.length-remaining)/images.length));else window.STUDIO_CACHE_TASKS?.finish(task);};imageTasks.push(task);progress();images.forEach(img=>{let settled=false;const done=()=>{if(settled)return;settled=true;remaining--;progress();};img.onload=done;img.onerror=()=>{done();const n=document.createElement('span');n.className='minigame-no-image';n.textContent='配图读取失败，点击重试';n.onclick=e=>{e.stopPropagation();settled=false;remaining++;progress();n.replaceWith(img);img.src=img.src;};img.replaceWith(n);};if(img.complete&&img.naturalWidth)done();});}
d.onclick=e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.hasAttribute('data-mini-close'))close(null);if(b.dataset.miniFilter){filter=b.dataset.miniFilter;paint();}if(b.dataset.miniId){current=Number(b.dataset.miniId);levelId=null;paint();}if(b.dataset.miniLevel){levelId=Number(b.dataset.miniLevel);paint();}if(b.hasAttribute('data-mini-back'))paint();if(b.hasAttribute('data-mini-select'))close(games.find(g=>g.id===current));if(b.hasAttribute('data-mini-play')){stop();const level=levels().find(r=>r.id===(levelId||levels()[0]?.id));try{d.classList.add('minigame-playing');player=StudentAgeSudoku.mount(d.querySelector('[data-mini-stage]'),level);d.querySelector('[data-mini-stage]').scrollIntoView({block:'nearest'});}catch(err){d.querySelector('[role=status]').textContent=err.message;}}};d.oncancel=e=>{e.preventDefault();close(null);};paint();d.showModal();return result;}
window.StudentAgeMinigameLibrary={pick};
})();
