/* Penguin Space authoring. The game uses two display levels and a separate
 * trigger graph; a reply's parent is always its root comment. */
(()=>{
'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const copy=v=>structuredClone(v),values=v=>Object.values(v||{}),asId=v=>Number(Array.isArray(v)?v[0]:v);
function create(host,options){
 const branchFolds=new Map();
 const S={data:null,posts:{},comments:{},editor:{disabledOptions:{}},selected:null,target:null,source:'local',search:'',preview:false,pendingComment:null,undo:[],redo:[],saved:'',revision:null,busy:false,lastEdit:null,simulation:null,branchChoices:{}};
 const dialog=document.createElement('dialog');dialog.className='social-dialog';document.body.append(dialog);
 const accountDialog=document.createElement('dialog');accountDialog.className='social-dialog social-account-dialog';document.body.append(accountDialog);
 const imageInput=document.createElement('input');imageInput.type='file';imageInput.accept='image/png,image/jpeg,image/webp';imageInput.multiple=true;imageInput.hidden=true;document.body.append(imageInput);
 let destroyed=false,avatarTimer=null;dialog.addEventListener('error',e=>{if(e.target.matches?.('.social-emoji img'))e.target.closest('.social-emoji').classList.add('missing');},true);
 const $=selector=>host.querySelector(selector),api=options.api,status=(message,error=false)=>options.status?.(message,error);
 const readonly=()=>!!(S.data?.project?.readOnly||S.data?.project?.readonly||String(options.project.id).startsWith('workshop:')||S.source==='reference');
 const posts=()=>{if(S.source==='reference')return S.data.referencePosts||{};const result={...S.posts},owners=new Set(Object.keys(S.comments).map(id=>Math.floor(Number(id)/100)));for(const key of Object.keys(S.editor.disabledOptions||{})){const [kind,id]=key.split(':');owners.add(kind==='post'?Number(id):Math.floor(Number(id)/100));}for(const id of owners)if(!result[id]&&S.data.referencePosts?.[id])result[id]=S.data.referencePosts[id];return result;};
 const comments=()=>S.source==='reference'?S.data.referenceComments||{}:{...S.data.referenceComments,...S.comments};
 const localPost=(id=S.selected)=>S.posts[id]||(S.posts[id]=copy(S.data.referencePosts[id]));
 const localComment=(id=S.target)=>S.comments[id]||(S.comments[id]=copy(S.data.referenceComments[id]));
 const localTarget=()=>S.target?localComment():localPost();
 const post=()=>posts()[S.selected];
 const target=()=>S.target?comments()[S.target]:post();
 const targetKey=()=>S.target?'comment:'+S.target:'post:'+S.selected;
 const account=id=>S.data.accounts?.find(row=>Number(row.id)===Number(id))||{id,name:Number(id)===0?'白雨':'未载入的空间账号',avatarUrl:''};
 const accountName=id=>account(id).name||account(id).personName||'空间用户';
 const avatar=(id,className='')=>{const a=account(id);return `<span class="social-avatar ${className}" data-social-avatar="${esc(id)}">${a.avatarUrl?`<img src="${esc(a.avatarUrl)}" alt="${esc(a.name)}的企鹅头像" loading="lazy">`:`<span aria-hidden="true">${esc(String(a.name||'?').slice(0,1))}</span>`}</span>`;};
 const imageURL=path=>'/api/social-image?projectId='+encodeURIComponent(options.project.id)+'&path='+encodeURIComponent(path)+'&token='+encodeURIComponent(options.token||'');
 const media=StudentAgeSocialMedia.create({api,token:options.token,project:options.project,revision:()=>S.revision,onUpload:()=>imageInput.click(),onBusy:value=>{S.busy=value;changed();},onSelect:result=>{S.revision=result.revision;S.busy=false;change(()=>{localPost().imgs=[...(localPost().imgs||[]),result.url];});renderFeed();status('配图已添加。');}});
 const rich=value=>media.render(value);
 const emojiButton=id=>`<div class="social-composer-toolbar"><button type="button" data-social="emoji" data-input="${id}" aria-label="选择表情">☺ 表情</button></div>`;
 const snapshot=()=>JSON.stringify({posts:S.posts,comments:S.comments,editor:S.editor});
 const dirty=()=>!!S.data&&(snapshot()!==S.saved||!!S.pendingComment?.content?.trim());
 const changed=()=>options.onState?.({dirty:dirty(),busy:S.busy,readOnly:readonly(),canUndo:S.undo.length>0,canRedo:S.redo.length>0,revision:S.revision});
 function restore(serialized){const value=JSON.parse(serialized);S.posts=value.posts;S.comments=value.comments;S.editor=value.editor||{disabledOptions:{}};if(!posts()[S.selected])S.selected=Object.keys(posts())[0]||null;if(!comments()[S.target])S.target=null;S.lastEdit=null;resetSimulation();render();changed();}
 function change(fn,key=null){if(readonly())throw Error('这是只读内容。请复制为本地模组后编辑。');if(S.busy)throw Error('正在保存，请稍候。');const stamp=Date.now();if(!key||S.lastEdit?.key!==key||stamp-S.lastEdit.time>900){S.undo.push(snapshot());if(S.undo.length>60)S.undo.shift();}S.lastEdit=key?{key,time:stamp}:null;S.redo=[];S.simulation?.stop?.();S.simulation=null;fn();changed();}
 function history(direction){if(readonly()||S.busy)return;const from=S[direction],to=S[direction==='undo'?'redo':'undo'];if(!from.length)return;to.push(snapshot());restore(from.pop());}
 function selectPost(id){S.selected=String(id);S.target=null;S.branchChoices={};S.preview=false;S.lastEdit=null;resetSimulation();render();}
 function accountPicker(title){return new Promise(resolve=>{
  let source='all';accountDialog.innerHTML=`<header><h2>${esc(title)}</h2><button data-social-account-cancel aria-label="关闭账号选择">×</button></header><p>企鹅空间账号与剧情人物分别列出。使用游戏中的默认头像。</p><div class="social-source-tabs"><button data-account-source="all" class="active">全部</button><button data-account-source="original">原版</button><button data-account-source="mod">模组</button></div><input type="search" id="social-account-search" placeholder="搜索人物或企鹅昵称" aria-label="搜索企鹅空间账号"><div id="social-account-grid" class="social-account-grid"></div>`;
  const paint=()=>{const q=accountDialog.querySelector('input').value.trim().toLocaleLowerCase();const rows=(S.data.accounts||[]).filter(a=>(source==='all'||(source==='original'?['original','game'].includes(a.source):!['original','game'].includes(a.source)))&&StudentAgeSearch.matches(q,a.id,a.name,a.profileName,a.personName));accountDialog.querySelector('#social-account-grid').innerHTML=rows.map(a=>`<button data-social-account="${a.id}" class="social-account-card">${avatar(a.id)}<strong>${StudentAgeRecordLabels.html(a.id,a.name)}</strong>${a.profileName&&a.profileName!==a.name?`<small>${esc(a.profileName)}</small>`:''}</button>`).join('')||'<p class="helper">没有匹配的空间账号</p>';};
  const finish=value=>{accountDialog.close();resolve(value);};
  accountDialog.onclick=e=>{const button=e.target.closest('button');if(!button)return;if(button.hasAttribute('data-social-account'))finish(Number(button.dataset.socialAccount));else if(button.hasAttribute('data-social-account-cancel'))finish(null);else if(button.dataset.accountSource){source=button.dataset.accountSource;accountDialog.querySelectorAll('[data-account-source]').forEach(b=>b.classList.toggle('active',b.dataset.accountSource===source));paint();}};
  accountDialog.oninput=paint;accountDialog.oncancel=e=>{e.preventDefault();finish(null);};paint();accountDialog.showModal();accountDialog.querySelector('input').focus();
 });}
 function nextPostId(){return STUDIO_IDS.allocate('KZoneContentCfg',{...S.data.referencePosts,...S.posts});}
 function nextCommentId(postId){return STUDIO_IDS.allocate('KZoneCommentCfg',{...S.data.referenceComments,...S.comments},Number(postId));}
 async function newPost(author=null){if(readonly()&&S.source!=='reference')return;const role=author??await accountPicker('选择发布动态的人物');if(role===null)return;S.source='local';change(()=>{const id=nextPostId();S.posts[id]={...copy(S.data.defaults?.post||{}),id,role,content:'',imgs:[],thumbs:[],comments:[],options:[],cond:[]};S.selected=String(id);S.target=null;});S.preview=false;render();$('#social-post-content')?.focus();status('已添加动态。设置发布条件后，可直接填写正文和评论。');}
 function allLinks(row){return [...(row?.comments||[]).map(asId),...(row?.options||[]).map(asId)];}
 function descendants(id,set=new Set()){if(set.has(Number(id)))return set;set.add(Number(id));for(const child of allLinks(comments()[id]))descendants(child,set);for(const row of values(comments()))if(Number(row.parent)===Number(id))descendants(row.id,set);for(const child of S.editor.disabledOptions?.['comment:'+id]||[])descendants(child,set);return set;}
 function removeComments(ids){for(const row of values(posts()))if(allLinks(row).some(id=>ids.has(Number(id)))){const own=localPost(row.id);own.comments=(own.comments||[]).filter(pair=>!ids.has(asId(pair)));own.options=(own.options||[]).filter(id=>!ids.has(Number(id)));}for(const row of values(comments()))if(!ids.has(Number(row.id))&&allLinks(row).some(id=>ids.has(Number(id)))){const own=localComment(row.id);own.comments=(own.comments||[]).filter(pair=>!ids.has(asId(pair)));own.options=(own.options||[]).filter(id=>!ids.has(Number(id)));}for(const id of ids)delete S.comments[id];for(const [key,list]of Object.entries(S.editor.disabledOptions||{})){if(key.startsWith('comment:')&&ids.has(Number(key.slice(8))))delete S.editor.disabledOptions[key];else S.editor.disabledOptions[key]=list.filter(id=>!ids.has(Number(id)));}}
 function confirmDelete(title,description){return new Promise(resolve=>{dialog.innerHTML=`<header><h2>${esc(title)}</h2></header><p>${esc(description)}</p><footer><button data-social-confirm="cancel">取消</button><button class="danger-button" data-social-confirm="delete">删除</button></footer>`;dialog.onclick=e=>{const b=e.target.closest('[data-social-confirm]');if(!b)return;dialog.close();resolve(b.dataset.socialConfirm==='delete');};dialog.oninput=null;dialog.onchange=null;dialog.oncancel=e=>{e.preventDefault();dialog.close();resolve(false);};dialog.showModal();});}
 async function deleteTarget(commentId=null){if(readonly())return;const id=commentId??S.target;if(id){if(!await confirmDelete('删除这条评论？','这条评论以及由它触发的回复和白雨选项会一起删除。保存前可以撤销。'))return;change(()=>removeComments(descendants(id)));S.target=null;}else{if(!post()||!await confirmDelete('删除这条动态？','动态、评论、回复和白雨选项会一起删除。保存前可以撤销。'))return;change(()=>{const id=Number(S.selected),ids=new Set(values(S.comments).filter(c=>Math.floor(Number(c.id)/100)===id).map(c=>Number(c.id)));removeComments(ids);delete S.posts[S.selected];delete S.editor.disabledOptions['post:'+S.selected];});S.selected=Object.keys(posts())[0]||null;S.target=null;}render();}
 function addComment(author,content,parentId,player=false,delay=0){const p=post();if(!p)throw Error('请先选择动态。');let owner=parentId?comments()[parentId]:p;if(!owner)throw Error('这条评论已被移除。');const ownerKey=parentId?'comment:'+parentId:'post:'+p.id;if(player&&(owner.options||[]).length+(S.editor.disabledOptions[ownerKey]||[]).length>=2)throw Error('同一次白雨回复最多两个选项；选择其中一个后可以继续添加子分支。');let id;change(()=>{owner=parentId?localComment(parentId):localPost(p.id);id=nextCommentId(p.id);const parent=parentId?Number(owner.parent)||Number(parentId):0;S.comments[id]={...copy(S.data.defaults?.comment||{}),id,roles:parentId?[Number(author),Number(owner.roles?.[0]??p.role)]:[Number(author)],parent,content:String(content),comments:[],options:[],effect:[],condition:[]};if(player){S.branchChoices[ownerKey]=id;owner.options=[...(owner.options||[]),id];const key=parentId?'comment:'+parentId:'post:'+p.id,parked=S.editor.disabledOptions[key]||[];if(parked.length){owner.options=[...new Set([...parked,...owner.options])];delete S.editor.disabledOptions[key];}}else owner.comments=[...(owner.comments||[]),[id,Math.max(0,Number(delay)||0)]];S.target=String(id);});render();return id;}
 async function compose(parentId=null,player=false){if(readonly())return;const author=player?0:await accountPicker(parentId?'选择回复的人物':'选择评论的人物');if(author===null)return;const p=post(),parent=parentId?comments()[parentId]:null;if(!p||parentId&&!parent)return;
  S.pendingComment={author,parentId,player,content:'',delay:0,postId:Number(p.id)};
  dialog.innerHTML=`<header><h2>${player?'白雨可选'+(parent?'回复':'评论'):parent?'添加回复':'添加评论'}</h2><button data-social-compose-cancel aria-label="关闭评论编辑">×</button></header><div class="social-compose-person">${avatar(author)}<strong>${esc(accountName(author))}</strong>${parent?`<span>回复 ${esc(accountName(parent.roles?.[0]))}</span>`:''}</div><textarea id="social-comment-draft" rows="4" placeholder="输入${parent?'回复':'评论'}内容" aria-label="评论内容"></textarea>${emojiButton("social-comment-draft")}<div class="social-draft-preview" data-draft-preview></div>${!player?`<label class="social-delay-label">${parent?'这条评论发布':'首次查看动态'}后等待 <input id="social-comment-delay" type="number" min="0" step="1" value="0"> 秒再出现</label>`:'<p class="helper">玩家点击这条内容后发布。条件与评论效果可在右侧设置。</p>'}<footer><button data-social-compose-cancel>取消</button><button class="primary" data-social-compose-submit>添加${parent?'回复':'评论'}</button></footer><p class="social-dialog-message" role="status"></p>`;
  const syncDraft=()=>{if(!S.pendingComment)return;S.pendingComment.content=dialog.querySelector('textarea').value;S.pendingComment.delay=Number(dialog.querySelector('#social-comment-delay')?.value||0);dialog.querySelector('[data-draft-preview]').innerHTML=rich(S.pendingComment.content);changed();};const cancelDraft=(discard=false)=>{if(!discard&&S.pendingComment?.content?.trim()){if(!dialog.querySelector('.social-draft-confirm')){const note=document.createElement('div');note.className='social-draft-confirm';note.innerHTML='<p>这条评论还没有添加。</p><button data-social-compose-keep>继续编辑</button><button class="danger-text" data-social-compose-discard>放弃这条评论</button>';dialog.append(note);}return;}S.pendingComment=null;dialog.close();changed();};dialog.oninput=syncDraft;dialog.onchange=syncDraft;dialog.onclick=e=>{const emoji=e.target.closest('[data-social=emoji]');if(emoji){media.emoji(dialog.querySelector('#'+emoji.dataset.input));return;}if(e.target.closest('[data-social-compose-discard]')){cancelDraft(true);return;}if(e.target.closest('[data-social-compose-keep]')){dialog.querySelector('.social-draft-confirm')?.remove();dialog.querySelector('textarea').focus();return;}if(e.target.closest('[data-social-compose-cancel]')){cancelDraft();return;}if(e.target.closest('[data-social-compose-submit]')){syncDraft();try{commitPendingComment();}catch(error){dialog.querySelector('.social-dialog-message').textContent=error.message;}}};dialog.oncancel=e=>{e.preventDefault();cancelDraft();};dialog.showModal();dialog.querySelector('textarea').focus();
 }
 function commitPendingComment(){const pending=S.pendingComment;if(!pending)return;const content=pending.content.trim();if(!content)throw Error('请填写评论内容。');if(!Number.isFinite(pending.delay)||pending.delay<0)throw Error('等待秒数必须为非负数。');if(Number(post()?.id)!==pending.postId)throw Error('动态已切换，请重新打开评论。');addComment(pending.author,content,pending.parentId,pending.player,pending.delay);S.pendingComment=null;dialog.close();changed();}
 function commentLabel(row){const recipient=Number(row.roles?.[1]),author=Number(row.roles?.[0]);return (S.preview&&author===0?'你':accountName(author))+(row.roles?.length>1&&recipient>=0&&recipient!==Number(post()?.role)?' 回复 '+accountName(recipient):'');}
 function socialBranches(){const map=comments(),result=[];function walk(row,key,choices={},label='',parentKey=null,seen=new Set()){if(!row||seen.has(key))return;seen=new Set(seen);seen.add(key);for(const pair of row.comments||[])walk(map[asId(pair)],'comment:'+asId(pair),choices,label,parentKey,seen);const opts=[...(row.options||[]),...(S.source==='local'?S.editor.disabledOptions?.[key]||[]:[])];if(opts.length>1)opts.forEach((id,i)=>{const nextLabel=label?label+'.'+(i+1):String(i+1),next={...choices,[key]:Number(id)},treeKey=(parentKey||'root')+'/'+key+':'+id;result.push({id:Number(id),owner:key,key:treeKey,parentKey,choices:next,label:nextLabel,depth:nextLabel.split('.').length-1});walk(map[id],'comment:'+id,next,nextLabel,treeKey,seen);});else if(opts.length)walk(map[opts[0]],'comment:'+opts[0],choices,label,parentKey,seen);}walk(post(),'post:'+S.selected);return result;}
 function renderBranchList(){const node=$('#social-branches');if(!node)return;const scope=S.source+':'+S.selected;if(!branchFolds.has(scope))branchFolds.set(scope,new Set());node.innerHTML='<h3>白雨回复分支</h3><div data-social-branch-tree></div>';StudentAgeBranchTree.mount(node.querySelector('[data-social-branch-tree]'),socialBranches(),{choices:S.branchChoices,collapsed:branchFolds.get(scope),attributes:i=>`data-social="branch" data-index="${i}"`,title:b=>comments()[b.id]?.content||'白雨回复'});}

 function linkedComments(){const map=comments(),p=post(),seen=new Set(),all=new Set(),out=[];
 function discover(row,key){if(!row||all.has(key))return;all.add(key);for(const id of [...allLinks(row),...(S.source==='local'?S.editor.disabledOptions?.[key]||[]:[])])discover(map[id],'comment:'+id);}discover(p,'post:'+p?.id);
 function options(row,key,depth){const choices=[...(row.options||[]),...(S.source==='local'?S.editor.disabledOptions?.[key]||[]:[])],chosen=choices.includes(Number(S.branchChoices[key]))?Number(S.branchChoices[key]):choices[0];if(chosen)visit(chosen,depth,(row.options||[]).includes(chosen)?true:'disabled');}
 function visit(id,depth=0,option=false,delay=0){id=Number(id);if(seen.has(id)||!map[id])return;seen.add(id);out.push({row:map[id],option,delay,depth});for(const pair of map[id].comments||[])visit(asId(pair),depth+1,false,Number(pair[1])||0);options(map[id],'comment:'+id,depth+1);}
 for(const pair of p?.comments||[])visit(asId(pair),0,false,Number(pair[1])||0);if(p)options(p,'post:'+p.id,0);for(const row of values(S.source==='reference'?map:S.comments))if(Math.floor(Number(row.id)/100)===Number(p?.id)&&!all.has('comment:'+row.id))out.push({row,option:'unlinked',depth:0,delay:0});return out;}
 function groupComments(entries){const groups=new Map();for(const entry of entries){const key=Number(entry.row.parent)||Number(entry.row.id);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(entry);}return [...groups].flatMap(([root,group])=>{const head=group.find(entry=>Number(entry.row.id)===root);return head?[head,...group.filter(entry=>entry!==head)]:group;});}
 function commentHTML(entry,preview=false){const row=entry.row,selected=String(row.id)===S.target,reply=Number(row.parent)>0;return `<article class="social-comment ${reply?'social-reply':''} ${selected&&!preview?'selected':''}" data-comment-card="${row.id}">${avatar(row.roles?.[0])}<div class="social-comment-main"><button class="social-comment-text" data-social="${preview?'preview-comment':'reply'}" data-id="${row.id}" ${readonly()&&!preview?'disabled':''}><strong>${esc(commentLabel(row))}</strong><span>${rich(row.content||'未填写评论')}</span></button>${!preview?`<div class="social-comment-tags">${entry.option?`<span>${entry.option==='disabled'?'已关闭的白雨选项':entry.option==='unlinked'?'尚未关联到发布流程':'白雨可选'+(reply?'回复':'评论')}</span>`:entry.delay>0?`<span>等待 ${entry.delay} 秒</span>`:''}${row.condition?.length?'<span>有出现条件</span>':''}${row.effect?.length?'<span>有评论效果</span>':''}${(row.options||[]).length?'<span>白雨可跟评</span>':''}</div>`:''}</div>${!preview?`<div class="social-comment-tools"><button data-social="settings" data-id="${row.id}">设置</button>${!readonly()?`<button data-social="delete-comment" data-id="${row.id}" aria-label="删除评论">×</button>`:''}</div>`:''}</article>`;}
 function renderList(){const q=S.search.toLocaleLowerCase();$('#social-post-list').innerHTML=values(posts()).filter(p=>StudentAgeSearch.matches(q,p.id,accountName(p.role),p.content,p.title)).sort((a,b)=>Number(b.id)-Number(a.id)).map(p=>`<button data-social="select-post" data-id="${p.id}" class="social-post-list-item ${String(p.id)===S.selected?'active':''}">${avatar(p.role)}<span><strong>${StudentAgeRecordLabels.html(p.id,accountName(p.role))}</strong><span>${p.title?`<b class="social-post-title">${esc(p.title)}</b>`:''}${rich(p.content||(!p.title?'空白动态':''))}</span><small>${(p.cond||[]).length?'按条件发布':'由剧情效果发布'} · ${values(comments()).filter(c=>Math.floor(Number(c.id)/100)===Number(p.id)).length} 条评论</small></span></button>`).join('')||'<p class="helper">没有动态</p>';}
 function render(){if(destroyed)return;const p=post();host.classList.add('social-workspace');host.innerHTML=`<div class="social-page-head"><div><h2>企鹅空间动态</h2><p>发布动态、添加评论与回复。</p></div><div class="social-source-tabs"><button data-social="source" data-source="local" class="${S.source==='local'?'active':''}">${options.project.originalMode?'原版 · 默认覆盖':'当前模组'}</button><button data-social="source" data-source="reference" class="${S.source==='reference'?'active':''}">原版参考</button></div>${!String(options.project.id).startsWith('workshop:')?'<button class="primary" data-social="new-post">＋ 发布动态</button>':''}</div>${readonly()?'<p class="social-readonly">'+(S.source==='reference'?'原版内容仅供预览。':'订阅模组仅供预览，复制为本地模组后可编辑。')+'</p>':''}<div class="social-layout"><aside class="social-list"><input id="social-search" type="search" value="${esc(S.search)}" placeholder="搜索动态或发布人物" aria-label="搜索动态"><div id="social-post-list"></div><section id="social-branches" class="social-branch-nav"></section></aside><section class="social-center">${p?`<div class="social-view-tabs"><button data-social="edit" class="${!S.preview?'active':''}">编辑</button><button data-social="preview" class="${S.preview?'active':''}">游戏内版式预览</button>${S.preview?'<button data-social="reset-preview">重新预览</button>':''}</div><div id="social-feed"></div>`:`<div class="social-empty"><h3>添加一条企鹅动态</h3><p>先选择发布的人物，再设置发布条件和内容。</p>${!readonly()?'<button class="primary" data-social="new-post">＋ 发布动态</button>':''}</div>`}</section><aside id="social-settings"></aside></div>`;renderList();renderBranchList();if(p){renderFeed();renderSettings();}changed();}
 function renderFeed(){const p=post(),feed=$('#social-feed');if(!p||!feed)return;const preview=S.preview,likes=(p.thumbs||[]).map(pair=>accountName(asId(pair)));let list=linkedComments();if(preview){if(!S.simulation)resetSimulation();list=S.simulation.visible.map(id=>({row:comments()[id]})).filter(x=>x.row);}
  feed.innerHTML=`<article class="social-feed-card"><header class="social-feed-author">${avatar(p.role)}<div>${!preview&&!readonly()?`<button data-social="choose-author" class="social-author-name">${esc(accountName(p.role))} <span>更换</span></button>`:`<strong>${esc(accountName(p.role))}</strong>`}<small>${String(p.id).startsWith('99')?'企鹅日志':'企鹅空间'} · ${preview?'发布时间随触发条件':'发布后显示'}</small></div>${!preview?'<button class="social-card-settings" data-social="settings">动态设置</button>':''}</header>${preview?(p.title?`<h3 class="social-post-title">${esc(p.title)}</h3>`:''):`<input class="social-log-title" data-social-field="title" placeholder="说说标题（可留空）" aria-label="说说标题" value="${esc(p.title||'')}" ${readonly()?'readonly':''}>`}${preview?`<div class="social-post-copy">${rich(p.content||'')}</div>`:`<textarea id="social-post-content" data-social-field="content" class="social-post-content" placeholder="输入动态内容" aria-label="动态正文" ${readonly()?'readonly':''}>${esc(p.content||'')}</textarea>${!readonly()?emojiButton('social-post-content'):''}<div class="social-draft-preview" data-post-preview>${rich(p.content||'')}</div>`}<div class="social-post-images">${(p.imgs||[]).map((path,i)=>`<figure><img src="${esc(imageURL(path))}" alt="动态配图 ${i+1}" loading="lazy">${!preview&&!readonly()?`<button data-social="remove-image" data-index="${i}" aria-label="移除配图">×</button>`:''}</figure>`).join('')}${!preview&&!readonly()?'<button class="social-add-image" data-social="add-image">＋<span>添加配图</span></button>':''}</div><div class="social-feed-actions">${!preview?`<button data-social="likes" ${readonly()?'disabled':''}>♡ 点赞人物</button><button data-social="comment" ${readonly()?'disabled':''}>▤ 评论</button>`:`<span>时间随剧情进度</span><button data-social="preview-comment" ${!(p.options||[]).length||S.simulation?.used.has('post:'+p.id)?'disabled':''}>▤ 评论</button>`}</div>${likes.length?`<p class="social-likes">♡ ${esc(likes.join('、'))}</p>`:''}<div class="social-comments">${groupComments(list).map(entry=>commentHTML(entry,preview)).join('')||'<p class="social-no-comments">暂无评论</p>'}</div>${preview?'<div id="social-preview-options"></div><p id="social-preview-message" class="social-preview-message">按条件满足预览；评论按设置的延迟出现，回复从上一级评论出现时计时。</p>':''}</article>`;
  if(preview&&S.simulation?.message)$('#social-preview-message').textContent=S.simulation.message;if(preview&&S.simulation?.optionsFor!==undefined)renderPreviewOptions(S.simulation.optionsFor);
 }
 function renderSettings(){const node=$('#social-settings'),p=post(),row=target();if(!p||!row){node.innerHTML='';return;}if(S.preview){node.innerHTML='<div class="social-settings-card"><h3>预览说明</h3><p>点击动态或评论旁的评论按钮，可以模拟白雨选择评论后的展示。</p><p>预览不会执行金钱、好感度等游戏效果。</p></div>';return;}
  const isComment=!!S.target,key=targetKey(),parked=S.editor.disabledOptions?.[key]||[],enabled=(row.options||[]).length>0,opts=enabled?row.options:parked;
  node.innerHTML=`<div class="social-settings-card"><header><h3>${isComment?'评论设置':'动态设置'}</h3>${!readonly()?`<button data-record-table="${isComment?'KZoneCommentCfg':'KZoneContentCfg'}" data-record-id="${row.id}">ID ${row.id} · 修改</button>`:''}${isComment?'<button data-social="settings">返回动态</button>':''}</header>${isComment?`<button class="social-setting-author" data-social="choose-comment-author">${avatar(row.roles?.[0])}<strong>${esc(accountName(row.roles?.[0]))}</strong></button><textarea id="social-current-comment" data-social-comment-field="content" rows="3" aria-label="修改评论内容" ${readonly()?'readonly':''}>${esc(row.content)}</textarea>${!readonly()?emojiButton('social-current-comment'):''}`:''}<details open><summary>${isComment?'评论出现条件':'动态发布条件'}</summary><div id="social-condition-editor"></div></details><section class="social-player-settings"><label class="social-toggle"><input type="checkbox" id="social-player-enabled" ${enabled?'checked':''} ${readonly()?'disabled':''}><span>白雨可以${isComment?'跟评':'评论'}</span></label><div class="social-player-options">${opts.map(id=>comments()[id]).filter(Boolean).map(option=>`<button data-social="settings" data-id="${option.id}" class="social-option-chip">${rich(option.content||'未填写的选项')}${!enabled?'<small>已关闭 · 内容保留</small>':''}</button>`).join('')}</div>${!readonly()?`<button data-social="player-option" data-id="${S.target||''}">＋ 添加白雨可选${isComment?'回复':'评论'}</button>`:''}<p>玩家从可选内容中选择一条。关闭后会保留已写内容。</p></section>${isComment?'<details open><summary>评论发布后的效果</summary><div id="social-effect-editor"></div></details>':''}${!readonly()?`<div class="social-settings-actions">${isComment?`<button data-social="reply" data-id="${S.target}">＋ 附加回复</button>`:''}<button data-social="delete" class="danger-text">删除这条${isComment?'评论':'动态'}</button></div>`:''}</div>`;
  const refs=S.data.refs||{},templates=S.data.commands?.condition||S.data.conditions||[];
  window.StudentAgeConditions?.mount($('#social-condition-editor'),{rows:row[isComment?'condition':'cond']||[],templates,refs,localIds:S.data.localIds,readOnly:readonly(),description:isComment?'全部满足后才可发布这条评论。':'全部满足后发布动态。',emptyText:isComment?'空列表表示不限制。':'空列表表示由剧情效果发布。',onChange:rows=>{change(()=>localTarget()[isComment?'condition':'cond']=rows);renderList();}});
  if(isComment){const effectHost=$('#social-effect-editor');window.StudentAgeEffects?.mount(effectHost,{rows:row.effect||[],templates:S.data.commands?.effect||S.data.effects||[],refs,readOnly:readonly(),description:'这条评论成功发布时执行。',onChange:rows=>{change(()=>localTarget().effect=rows);renderList();},onError:error=>status(error.message,true)});effectHost.querySelectorAll('[data-effect-new-premise],option[value="premise-new"]').forEach(el=>el.remove());const empty=effectHost.querySelector('.effect-empty');if(empty)empty.textContent='这条评论尚未添加效果';}
 }
 function resetSimulation(){S.simulation?.stop?.();const sim={visible:[],used:new Set(),optionsFor:undefined};S.simulation=sim;if(!S.preview||!post())return;let painting=false;const clock=StudentAgeSocialMedia.timeline(comments(),()=>{if(painting)return;painting=true;queueMicrotask(()=>{painting=false;if(!destroyed&&S.preview&&S.simulation===sim)renderFeed();});});sim.visible=clock.visible;sim.stop=clock.stop;sim.publish=clock.publish;clock.start(post());}
 function renderPreviewOptions(commentId){if(!S.preview)return;S.simulation.optionsFor=commentId;const row=commentId?comments()[commentId]:post(),key=commentId?'comment:'+commentId:'post:'+post()?.id,node=$('#social-preview-options');if(!node)return;node.innerHTML=S.simulation.used.has(key)?'<p class="helper">这里已经选择过一条评论。</p>':`<div class="social-game-options"><strong>白雨的${commentId?'回复':'评论'}</strong>${(row?.options||[]).map(id=>comments()[id]).filter(Boolean).map(c=>`<button data-social="preview-option" data-id="${c.id}" data-parent="${commentId||''}">${rich(c.content)}</button>`).join('')||'<p>没有可选评论</p>'}</div>`;}
 function choosePreviewOption(id,parentId){const owner=parentId?comments()[parentId]:post(),key=parentId?'comment:'+parentId:'post:'+post().id;if(S.simulation.used.has(key)||!(owner?.options||[]).map(Number).includes(Number(id)))return;S.simulation.used.add(key);S.simulation.publish(id);S.simulation.optionsFor=undefined;renderFeed();const effect=comments()[id]?.effect||[];if(effect.length)S.simulation.message=$('#social-preview-message').textContent='已预览这条评论；它配置了 '+effect.length+' 项发布效果，仅在游戏中实际执行。';}
 async function togglePlayer(enabled){if(readonly())return;const row=target(),key=targetKey();if(!row)return;if(enabled){const cached=S.editor.disabledOptions[key]||[];if(!cached.length){await compose(S.target,true);render();return;}change(()=>{localTarget().options=copy(cached);delete S.editor.disabledOptions[key];});}else change(()=>{S.editor.disabledOptions[key]=copy(row.options||[]);localTarget().options=[];});render();}
 async function importImages(files){if(!files.length||readonly())return;const id=S.selected;S.busy=true;changed();try{for(const file of files){if(file.size>24*1024*1024)throw Error('单张配图需小于 24 MB。');const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(Error('无法读取图片。'));reader.readAsDataURL(file);});const result=await api('/api/image-import',{projectId:options.project.id,revision:S.revision,fileName:file.name,name:file.name,data});S.revision=result.revision;S.busy=false;change(()=>{localPost(id).imgs=[...(localPost(id).imgs||[]),result.url||result.assetPath];});S.busy=true;}status('配图已导入。保存动态后应用到模组。');}finally{S.busy=false;render();changed();}}
 async function save(){if(S.pendingComment?.content?.trim())commitPendingComment();if(S.busy)throw Error('正在保存，请稍候。');if(!dirty())return;if(String(options.project.id).startsWith('workshop:'))throw Error('订阅模组只读。');const value=JSON.parse(snapshot());S.busy=true;changed();try{const data=await api('/api/social-save',{projectId:options.project.id,revision:S.revision,...value});S.revision=data.revision;S.posts=copy(data.posts||value.posts);S.comments=copy(data.comments||value.comments);S.editor=copy(data.editor||value.editor);S.saved=snapshot();S.undo=[];S.redo=[];S.lastEdit=null;status('动态、评论和回复已一起保存。修改前的文件已自动备份。');await options.onSaved?.(data);render();}finally{S.busy=false;changed();}}
 async function action(button){const name=button.dataset.social,id=button.dataset.id;if(name==='branch'){const branch=socialBranches()[Number(button.dataset.index)];S.branchChoices=branch?.choices||{};S.target=branch?String(branch.id):null;S.preview=false;S.lastEdit=null;return render();}if(name==='select-post')return selectPost(id);if(name==='source'){S.source=button.dataset.source;S.selected=Object.keys(posts())[0]||null;S.target=null;S.preview=S.source==='reference';resetSimulation();return render();}if(name==='new-post')return newPost();if(name==='settings'){S.target=id||null;return render();}if(name==='edit'||name==='preview'){S.preview=name==='preview';resetSimulation();return render();}if(name==='reset-preview'){resetSimulation();return renderFeed();}if(name==='preview-comment')return renderPreviewOptions(id||null);if(name==='preview-option')return choosePreviewOption(id,button.dataset.parent||null);
  if(readonly()||S.busy)return;
  if(name==='choose-author'||name==='choose-comment-author'){const author=await accountPicker('选择企鹅空间人物');if(author===null)return;if(name==='choose-comment-author'&&Number(target()?.roles?.[0])===0&&linkedComments().find(x=>String(x.row.id)===S.target)?.option){if(author!==0)throw Error('白雨可选评论的发言者是白雨。其他人物请通过“附加回复”加入。');}change(()=>{if(name==='choose-author')localPost().role=author;else {const row=localTarget(),previous=Number(row.roles[0]);row.roles[0]=author;const linked=[...allLinks(row),...(S.editor.disabledOptions['comment:'+row.id]||[])];for(const id of linked){const reply=comments()[id];if(reply?.roles?.length>1&&Number(reply.roles[1])===previous)localComment(id).roles[1]=author;}}});return render();}
  if(name==='comment')return compose();if(name==='reply')return compose(id||S.target);if(name==='player-option')return compose(id||null,true);if(name==='delete')return deleteTarget();if(name==='delete-comment')return deleteTarget(id);if(name==='emoji'){media.emoji(host.querySelector('#'+button.dataset.input));return;}if(name==='add-image')return media.photos();if(name==='remove-image'){change(()=>localPost().imgs.splice(Number(button.dataset.index),1));return renderFeed();}if(name==='likes'){const author=await accountPicker('选择点赞的人物');if(author===null)return;change(()=>{const list=localPost().thumbs||[],index=list.findIndex(pair=>asId(pair)===author);if(index>=0)list.splice(index,1);else list.push([author,0]);localPost().thumbs=list;});return renderFeed();}
 }
 const onPremisesRemoved=event=>{if(destroyed||options.project.id!==event.detail.projectId)return;const pairs=new Set(event.detail.pairs),clean=value=>window.STUDIO_STRIP_PREMISES(value,pairs),strip=text=>{const data=JSON.parse(text);clean(data);return JSON.stringify(data);};clean(S.posts);clean(S.comments);clean(S.data);S.saved=strip(S.saved);S.undo=S.undo.map(strip);S.redo=S.redo.map(strip);S.revision=event.detail.revision;render();};window.addEventListener('studio-premises-removed',onPremisesRemoved);const onPremiseCreated=e=>{if(options.project.id===e.detail.projectId&&S.revision===e.detail.previousRevision){S.revision=e.detail.revision;changed();}};window.addEventListener('studio-premise-created',onPremiseCreated);
 host.addEventListener('contextmenu',event=>{const card=event.target.closest('[data-social=select-post]');if(!card||readonly())return;window.StudentAgeContextMenu(event,'删除企鹅动态',async()=>{selectPost(card.dataset.id);S.target=null;await deleteTarget();});});
 host.addEventListener('click',event=>{const button=event.target.closest('[data-social]');if(button&&!button.disabled){event.preventDefault();Promise.resolve(action(button)).catch(error=>{status(error.message,true);changed();});}});
 host.addEventListener('input',event=>{const input=event.target;if(input.id==='social-search'){S.search=input.value;renderList();return;}try{if(input.dataset.socialField){const key=input.dataset.socialField;change(()=>localPost()[key]=input.value,'post:'+S.selected+':'+key);renderList();if(key==='content'&&$('[data-post-preview]'))$('[data-post-preview]').innerHTML=rich(input.value);}if(input.dataset.socialCommentField){const key=input.dataset.socialCommentField;change(()=>localTarget()[key]=input.value,'comment:'+S.target+':'+key);renderFeed();renderBranchList();}}catch(error){status(error.message,true);}});
 host.addEventListener('change',event=>{if(event.target.id==='social-player-enabled')togglePlayer(event.target.checked).catch(error=>status(error.message,true));});
 host.addEventListener('error',event=>{const img=event.target;if(img.matches?.('.social-emoji img')){img.closest('.social-emoji').classList.add('missing');return;}if(!img.matches?.('.social-avatar img,.social-post-images img'))return;img.hidden=true;const fallback=document.createElement('span');fallback.className='social-image-missing';fallback.textContent=img.closest('.social-avatar')?'头像暂不可用':'图片暂不可用';img.parentNode.append(fallback);},true);
 imageInput.addEventListener('change',()=>{const files=Array.from(imageInput.files);imageInput.value='';importImages(files).catch(error=>status(error.message,true));});
 async function refreshAvatars(){if(destroyed)return;try{const resource=await api('/api/resource-status');if(['running','queued'].includes(resource.status)){avatarTimer=setTimeout(refreshAvatars,2000);return;}const next=await api('/api/social?projectId='+encodeURIComponent(options.project.id));if(destroyed)return;S.data.accounts=next.accounts||S.data.accounts;for(const root of [host,accountDialog,dialog])for(const node of root.querySelectorAll('[data-social-avatar]')){const span=document.createElement('span');span.innerHTML=avatar(node.dataset.socialAvatar);node.replaceWith(span.firstElementChild);}}catch(error){if(!destroyed)status('头像读取未完成，可重新打开人物目录重试。',true);}}
 async function load(){S.busy=true;changed();try{S.data=await api('/api/social?projectId='+encodeURIComponent(options.project.id));S.posts=copy(S.data.posts||{});S.comments=copy(S.data.comments||{});S.editor=copy(S.data.editor||{disabledOptions:{}});S.editor.disabledOptions||={};S.revision=S.data.revision;S.selected=Object.keys(posts())[0]||null;S.saved=snapshot();render();if(['running','queued'].includes(S.data.resourceStatus?.status))avatarTimer=setTimeout(refreshAvatars,2000);if(S.data.warnings?.length)status(S.data.warnings.join('；'),true);}finally{S.busy=false;changed();}}
 return {jsonRead:name=>{const path={"KZoneContentCfg": ["posts"], "KZoneCommentCfg": ["comments"]}[name];if(!path||!S.data)return null;return path.reduce((v,k)=>v?.[k],JSON.parse(snapshot()));},
 jsonWrite(name,rows){const path={"KZoneContentCfg": ["posts"], "KZoneCommentCfg": ["comments"]}[name];if(!path)return false;if(readonly()||S.busy)throw Error('当前页面暂不可编辑。');const data=JSON.parse(snapshot());let parent=data;for(const k of path.slice(0,-1))parent=parent[k];if(JSON.stringify(parent[path.at(-1)])===JSON.stringify(rows))return true;S.undo.push(snapshot());if(S.undo.length>60)S.undo.shift();S.redo=[];parent[path.at(-1)]=structuredClone(rows);restore(JSON.stringify(data));changed();return true;},
 jsonSaved(name,rows,revision){const path={"KZoneContentCfg": ["posts"], "KZoneCommentCfg": ["comments"]}[name];if(!path)return;const data=JSON.parse(S.saved);let parent=data;for(const k of path.slice(0,-1))parent=parent[k];parent[path.at(-1)]=structuredClone(rows);S.saved=JSON.stringify(data);S.revision=revision;changed();},navigation:{capture:()=>({selected:S.selected,target:S.target,source:S.source,search:S.search,preview:S.preview,branchChoices:S.branchChoices}),restore:v=>{S.source=v.source||'local';S.search=v.search||'';S.selected=posts()[v.selected]?v.selected:Object.keys(posts())[0]||null;S.target=comments()[v.target]?v.target:null;S.preview=!!v.preview;S.branchChoices=v.branchChoices||{};resetSimulation();render();}},newPost,selectPost,load,save,dirty,snapshot,restore,undo:()=>history('undo'),redo:()=>history('redo'),discard(){S.pendingComment=null;dialog.close();restore(S.saved);S.undo=[];S.redo=[];changed();},delete:()=>deleteTarget(),focusSearch:()=>$('#social-search')?.focus(),get state(){return S;},destroy(){window.removeEventListener('studio-premise-created',onPremiseCreated);destroyed=true;window.removeEventListener('studio-premises-removed',onPremisesRemoved);S.simulation?.stop?.();media.destroy();clearTimeout(avatarTimer);dialog.remove();accountDialog.remove();imageInput.remove();host.classList.remove('social-workspace');},test:{addComment,groupComments,nextPostId,nextCommentId,descendants,linkedComments,socialBranches,accountPicker,selectPost,resetSimulation,choosePreviewOption}};
}
window.StudentAgeSocial={create};
})();
