/* KZoneView.RefreshTabFont / SetTheme / OnSliderFontSize / cancel and save. */
(()=>{'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let glyphPromise;const images=new Map(),fallbackFonts=new Map();
async function fallbackFont(id){if(!fallbackFonts.has(id))fallbackFonts.set(id,(async()=>{try{const font=await new FontFace('StudioSpace'+id,`url("${resource(id+'.otf')}")`).load();document.fonts.add(font);return '"'+font.family+'", sans-serif';}catch{return 'sans-serif';}})());return fallbackFonts.get(id);}
const resource=name=>'/api/space-ui?'+new URLSearchParams({resource:name,token:window.STUDIO_TOKEN});
function image(name){if(!images.has(name))(images.clear(),images.set(name,new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=()=>{images.delete(name);reject(Error('原版签名字体图集读取失败'));};i.src=resource(name);})));return images.get(name);}
async function draw(canvas,p,fonts){const epoch=canvas.signatureEpoch=(canvas.signatureEpoch||0)+1;
try{glyphPromise??=fetch(resource('glyphs.json')).then(r=>{if(!r.ok)throw Error('原版字体读取失败');return r.json();}).catch(e=>{glyphPromise=null;throw e;});const data=await glyphPromise,font=data[p.font||101];if(!font)throw Error('此字体的原版图集不可用');const atlases=await Promise.all(font.atlases.map(image));if(epoch!==canvas.signatureEpoch)return;
const hasMissing=[...String(p.desc||'')].some(ch=>ch!=='\n'&&!font.characters[ch.codePointAt(0)]),fallback=hasMissing?await fallbackFont(p.font||101):'sans-serif';if(epoch!==canvas.signatureEpoch)return;
const width=canvas.width=1534,height=canvas.height=120,ctx=canvas.getContext('2d'),face=font.face,size=p.fontSize||40,unit=size/(face.m_PointSize||48),line=(face.m_LineHeight||60)*unit,asc=(face.m_AscentLine||48)*unit;let x=0,y=asc;const missing=[];
for(const ch of String(p.desc||'')){if(ch==='\n'){x=0;y+=line;continue;}const g=font.characters[ch.codePointAt(0)];if(!g){missing.push(ch);ctx.font=size+'px '+fallback;const advance=ctx.measureText(ch).width;if(x+advance>width){x=0;y+=line;}ctx.fillText(ch,x,y);x+=advance;continue;}const m=g.m_Metrics,r=g.m_GlyphRect,advance=m.m_HorizontalAdvance*unit;if(x+advance>width){x=0;y+=line;}const atlas=atlases[g.m_AtlasIndex||0];if(r.m_Width&&r.m_Height)ctx.drawImage(atlas,r.m_X,atlas.height-r.m_Y-r.m_Height,r.m_Width,r.m_Height,x+m.m_HorizontalBearingX*unit,y-m.m_HorizontalBearingY*unit,r.m_Width*unit,r.m_Height*unit);x+=advance;}
ctx.globalCompositeOperation='source-in';const colors=fonts[p.fontColor]?.colors||['#ffffff'];const fill=ctx.createLinearGradient(0,0,0,Math.max(size,y));fill.addColorStop(0,colors[0]);fill.addColorStop(1,colors[1]||colors[0]);ctx.fillStyle=fill;ctx.fillRect(0,0,width,height);ctx.globalCompositeOperation='source-over';canvas.setAttribute('aria-label',p.desc||'个性签名');canvas.dataset.ready='true';canvas.dataset.error=missing.length?'以下字符使用备用字体显示：'+[...new Set(missing)].join(''):'';
}catch(e){canvas.dataset.error=e.message;canvas.dataset.ready='false';}}
function create(ctx){const {S,host,profile,change,local,renderPreview,assetURL,picker,dialog,status}=ctx;
function editor(){const original=structuredClone(profile()),draft={...original},fonts=S.data.fonts||{};let tab='theme';
function paint(){const visible=Object.values(fonts).filter(f=>f.show||f.id===draft.font||f.id===draft.fontColor);picker('个性名片',`<nav class="space-style-tabs"><button data-style-tab="theme" aria-pressed="${tab==='theme'}">背景</button><button data-style-tab="font" aria-pressed="${tab==='font'}" ${draft.isVip?'':'disabled'}>字体</button></nav>${tab==='font'?`<div class="space-font-options">${visible.filter(f=>!f.colors?.length).map(f=>`<button data-style-font="${f.id}" aria-pressed="${draft.font===f.id}"><img src="${esc(resource('sample-'+f.id+'.png'))}" alt="${esc(f.name)}字形"><span>${esc(f.name)}</span></button>`).join('')}</div><div class="space-color-options">${visible.filter(f=>f.colors?.length).map(f=>`<button data-style-color="${f.id}" aria-label="${esc(f.name)}" aria-pressed="${draft.fontColor===f.id}" style="background:linear-gradient(${f.colors.map(c=>/^#[\da-f]{6}$/i.test(c)?c:'#fff').join(',')}${f.colors.length===1?','+f.colors[0]:''})"></button>`).join('')}</div><label class="space-size-slider"><span>小</span><input type="range" min="40" max="80" step="1" value="${draft.fontSize}" data-style-size aria-label="签名字号"><span>大</span><output>${draft.fontSize}</output></label>`:`<div class="space-theme-grid">${Object.values(S.data.themes).map(t=>`<button data-style-theme="${t.id}" aria-pressed="${draft.theme===t.id}" ${!draft.isVip&&t.id!==1?'disabled':''}><img src="${esc(assetURL('kzone/img_theme_'+t.id))}" alt="${esc(t.name)}" loading="lazy"><strong>${esc(t.name)}</strong></button>`).join('')}</div>${draft.isVip?'':'<p>原版字体与个性名片设置需要开通黄钻。</p>'}`}<div class="space-style-sample"><canvas data-signature-sample></canvas><p data-style-error role="status"></p></div><footer><button data-style-cancel>取消</button><button data-style-save class="primary">保存设置</button></footer>`,e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.styleTab){tab=b.dataset.styleTab;paint();}if(b.dataset.styleFont){draft.font=Number(b.dataset.styleFont);paint();}if(b.dataset.styleColor){draft.fontColor=Number(b.dataset.styleColor);paint();}if(b.dataset.styleTheme){draft.theme=Number(b.dataset.styleTheme);paint();}if(b.hasAttribute('data-style-cancel')){dialog.close();renderPreview();}if(b.hasAttribute('data-style-save')){change(()=>Object.assign(local(),Object.fromEntries(['font','fontColor','fontSize','theme'].map(k=>[k,draft[k]]))));dialog.close();ctx.render();}});
const canvas=dialog.querySelector('[data-signature-sample]');draw(canvas,draft,fonts).then(()=>{if(canvas.isConnected)dialog.querySelector('[data-style-error]').textContent=canvas.dataset.error;});dialog.oninput=e=>{if(e.target.hasAttribute('data-style-size')){draft.fontSize=Number(e.target.value);dialog.querySelector('output').textContent=draft.fontSize;draw(canvas,draft,fonts);renderPreview(draft);}};renderPreview(draft);
dialog.oncancel=e=>{e.preventDefault();dialog.close();renderPreview();};dialog.onclose=()=>{renderPreview();dialog.onclose=null;};}
paint();}
function bindDrag(node){const handle=node.querySelector('[data-signature-drag]'),area=node.querySelector('.space-native-top');if(!handle||!area||ctx.readonly())return;let start=null;
handle.onpointerdown=e=>{e.preventDefault();const r=area.getBoundingClientRect(),position=S.layouts[S.selected]?.signature||{x:.13176,y:.18444};start={px:e.clientX,py:e.clientY,...position,r};handle.setPointerCapture(e.pointerId);};
handle.onpointermove=e=>{if(!start)return;const x=Math.max(0,Math.min(.8,start.x+(e.clientX-start.px)/start.r.width)),y=Math.max(0,Math.min(.9,start.y+(e.clientY-start.py)/start.r.height));handle.parentElement.style.left=x*100+'%';handle.parentElement.style.top=y*100+'%';start.next={x,y};};
handle.onpointerup=e=>{if(!start)return;const pos=start.next;start=null;if(pos){change(()=>{S.layouts[S.selected]??={};S.layouts[S.selected].signature=pos;});renderPreview();}};handle.onpointercancel=()=>{start=null;renderPreview();};}
return {editor,bindDrag,draw,destroy(){images.clear();glyphPromise=null;}};}
window.StudentAgeSpaceStyle={create,draw};
})();
