/* UP screen videos: imports commit media; applying a video remains a dialogue draft. */
(()=>{'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function open(options){
 const {projectId,api}=options,d=document.createElement('dialog');d.className='character-picker video-library';d.setAttribute('aria-label','视频素材库');document.body.append(d);
 let source='mod',sourceProjectId=projectId,query='',page=0,items=[],projects=[],total=0,pageSize=36,folder={path:'',revision:null},record=null,busy=false,loading=false,closed=false,sequence=0,resolve;
 const done=new Promise(r=>resolve=r),q=s=>d.querySelector(s),token=()=>options.token??window.STUDIO_TOKEN??'';
 const context=()=>{const current=options.getContext?.();if(!current||current.project?.id!==projectId)throw Error('当前模组已变化，请重新打开视频素材库。');return current;};
 const say=(message,error=false)=>{if(closed)return;q('[data-video-status]').textContent=message||'';q('[data-video-status]').classList.toggle('error',error);};
 const previewURL=item=>{if(!item?.previewUrl)return '';const url=new URL(item.previewUrl,location.origin);if(url.origin!==location.origin)return '';url.searchParams.set('token',token());return url.pathname+url.search;};
 const end=value=>{if(busy)return;sequence++;closed=true;const video=q('video');if(video){video.pause();video.removeAttribute('src');video.load();}d.close();d.remove();resolve(value);};
 function controls(){if(closed)return;d.querySelectorAll('button,input,select').forEach(n=>n.disabled=busy||loading);d.querySelectorAll('[data-video-close]').forEach(n=>n.disabled=busy);d.querySelectorAll('[data-video-item]').forEach(n=>n.disabled=busy||loading||items[Number(n.dataset.videoItem)]?.available===false);q('[data-video-apply]').disabled=busy||loading||!record;q('[data-video-prev]').disabled=busy||loading||page===0;q('[data-video-next]').disabled=busy||loading||(page+1)*pageSize>=total;if(record?.roleOnTop)q('[data-video-setting="skippable"]').disabled=true;}
 d.innerHTML=`<header><h2>视频素材库</h2><button data-video-close>关闭</button></header><nav class="video-library-sources"><button data-video-source="mod" class="active">模组</button><button data-video-source="custom">自定义</button></nav><section class="video-library-toolbar"><label data-video-mod-control>选择模组<select data-video-project></select></label><div data-video-custom-control hidden><div class="video-folder-row"><input data-video-folder aria-label="视频素材文件夹" placeholder="视频素材文件夹的完整路径"><button data-video-browse>浏览文件夹</button><button data-video-folder-read>读取文件夹</button></div><label class="video-upload-label">导入视频<input data-video-upload type="file" accept="video/*,.mp4,.mov,.mkv,.avi,.webm,.m4v,.wmv,.mpeg,.mpg"></label><p class="helper">导入时自动转为 H.264＋AAC MP4，单个视频最多 256 MB。无音轨的视频保持无声。</p></div><input data-video-search type="search" placeholder="搜索视频名称" aria-label="搜索视频名称"></section><p data-video-status role="status" aria-live="polite"></p><div class="video-library-columns"><section><div class="video-library-grid" data-video-grid></div><footer class="video-library-pagination"><button data-video-prev>上一页</button><span data-video-count></span><button data-video-next>下一页</button></footer></section><aside class="video-library-settings" data-video-settings><p>选择视频后设置播放参数。</p></aside></div><footer class="video-library-footer"><button data-video-close>取消</button><button data-video-apply class="primary" disabled>应用到本句</button></footer>`;
 function paintItems(){
  q('[data-video-grid]').innerHTML=items.map((item,index)=>`<button data-video-item="${index}" ${item.available===false?'disabled':''} class="${Number(item.videoId)===Number(record?.id)?'active':''}"><span class="video-library-icon" aria-hidden="true">▶</span><strong>${esc(item.name||'未命名视频')}</strong>${item.available===false?'<small>视频文件不可用</small>':''}</button>`).join('')||'<p class="helper">没有可用视频。可在“自定义”中导入视频或读取文件夹。</p>';
  q('[data-video-count]').textContent=total+' 个 · '+(page+1)+' / '+Math.max(1,Math.ceil(total/pageSize));
  q('[data-video-project]').innerHTML=projects.map(project=>`<option value="${esc(project.id)}" ${project.id===sourceProjectId?'selected':''}>${esc(project.name)}${project.id===projectId?' · 当前模组':''}</option>`).join('');controls();
 }
 function paintRecord(){
  const previous=q('video');if(previous)previous.pause();const host=q('[data-video-settings]');if(!record){host.innerHTML='<p>选择视频后设置播放参数。</p>';controls();return;}
  const url=record.previewUrl||'/api/assets?'+new URLSearchParams({projectId,path:'ScreenVideo/'+record.video,token:token()});
  host.innerHTML=`<h3>播放参数</h3><video controls preload="metadata" playsinline aria-label="预览所选视频" src="${esc(url)}" ${record.loop?'loop':''}></video><label>视频名称<input data-video-setting="name" value="${esc(record.name)}"></label><label>音量 <output data-video-volume>${Math.round(Number(record.volume)*100)}%</output><input data-video-setting="volume" type="range" min="0" max="1" step=".01" value="${esc(record.volume)}"></label><label><input type="checkbox" data-video-setting="loop" ${record.loop?'checked':''}>循环播放</label><label><input type="checkbox" data-video-setting="skippable" ${record.skippable?'checked':''}>允许跳过</label><label><input type="checkbox" data-video-setting="roleOnTop" ${record.roleOnTop?'checked':''}>人物显示在视频上方（动态背景）</label><p class="helper" data-video-background-note ${record.roleOnTop?'':'hidden'}>动态背景可继续对话，不响应跳过操作。</p><label>缩放方式<select data-video-setting="scale"><option value="fit" ${record.scale==='fit'?'selected':''}>完整显示（保留比例）</option><option value="fill" ${record.scale==='fill'?'selected':''}>铺满画面（裁剪边缘）</option><option value="stretch" ${record.scale==='stretch'?'selected':''}>拉伸铺满</option></select></label><p class="helper">应用后将视频设置写入模组；本句播放指令在保存剧情后生效。</p>`;
  const video=q('video');video.volume=record.volume;video.style.objectFit=record.scale==='fill'?'cover':record.scale==='stretch'?'fill':'contain';controls();
 }
 function useRecord(row,previewUrl){record={...structuredClone(row),name:String(row.name||''),volume:Number.isFinite(Number(row.volume))?Math.max(0,Math.min(1,Number(row.volume))):1,loop:!!row.loop,skippable:row.skippable!==false,roleOnTop:!!row.roleOnTop,scale:['fit','fill','stretch'].includes(row.scale)?row.scale:'fit',previewUrl};paintRecord();paintItems();}
 async function committed(result){if(result.projectId!==projectId)throw Error('视频导入到了其他模组，请重新打开素材库。');if(result.imported)await options.onCommitted?.(result);context();}
 async function reload(){
  const read=++sequence;loading=true;controls();try{const result=await api('/api/videos?'+new URLSearchParams({projectId,source,sourceProjectId:source==='mod'?sourceProjectId:'',q:query,page}));if(closed||read!==sequence)return;items=result.items||[];projects=result.projects||[];total=result.total??items.length;pageSize=result.pageSize||36;loading=false;paintItems();if(!record&&source==='mod'&&sourceProjectId===projectId&&options.selectedId){const item=items.find(item=>Number(item.videoId)===Number(options.selectedId));if(item?.row&&item.available!==false)useRecord(item.row,previewURL(item));}}catch(error){if(!closed&&read===sequence)say(error.message,true);}finally{if(!closed&&read===sequence){loading=false;controls();}}
 }
 async function select(item){
  if(!item||item.available===false)return;busy=true;controls();say('正在读取并导入视频…');try{const current=context(),result=await api('/api/video-library-import',{projectId,revision:current.revision,source,sourceProjectId:source==='mod'?(item.sourceProjectId||sourceProjectId):undefined,assetId:item.assetId,assetRevision:item.assetRevision,sourceRevision:item.sourceRevision});await committed(result);useRecord(result.row);say('已选择视频。设置播放参数后应用到本句。');}finally{busy=false;controls();}
 }
 async function importFile(file){
  if(!file||busy||loading)return;if(!file.size||file.size>256*1024*1024)throw Error('请选择非空且不超过 256 MB 的视频。');
  busy=true;controls();say('正在转换视频为 H.264＋AAC MP4…');try{const current=context(),params=new URLSearchParams({projectId,revision:current.revision,fileName:file.name}),response=await fetch('/api/video-import?'+params,{method:'POST',headers:{'X-Studio-Token':token(),'Content-Type':'application/octet-stream'},body:file}),result=await response.json();if(!response.ok||result.error)throw Error(result.error||'视频导入没有完成。');await committed(result);useRecord(result.row);await reload();say('视频已转换并导入。设置播放参数后应用到本句。');}finally{busy=false;controls();}
 }
 async function setFolder(path){busy=true;controls();try{folder=await api('/api/video-folder',{path:String(path||'').trim(),revision:folder.revision});q('[data-video-folder]').value=folder.path||'';page=0;await reload();say('视频文件夹已读取。');}finally{busy=false;controls();}}
 d.oninput=e=>{const node=e.target,key=node.dataset.videoSetting;if(key&&record){record[key]=node.type==='checkbox'?node.checked:key==='volume'?Number(node.value):node.value;const video=q('video');if(key==='volume'){q('[data-video-volume]').textContent=Math.round(record.volume*100)+'%';video.volume=record.volume;}if(key==='loop')video.loop=record.loop;if(key==='scale')video.style.objectFit=record.scale==='fill'?'cover':record.scale==='stretch'?'fill':'contain';if(key==='roleOnTop'){q('[data-video-background-note]').hidden=!record.roleOnTop;controls();}}};
 d.onchange=e=>{const node=e.target;if(node.hasAttribute('data-video-upload')){const file=node.files[0];node.value='';importFile(file).catch(error=>say(error.message,true));}else if(node.hasAttribute('data-video-project')){sourceProjectId=node.value;page=0;reload();}else if(node.hasAttribute('data-video-search')){query=node.value.trim();page=0;reload();}};
 d.onclick=async e=>{const button=e.target.closest('button');if(!button||button.disabled||busy)return;try{
  if(button.hasAttribute('data-video-close'))return end(null);if(loading)return;
  if(button.dataset.videoSource){source=button.dataset.videoSource;page=0;d.querySelectorAll('[data-video-source]').forEach(node=>node.classList.toggle('active',node.dataset.videoSource===source));q('[data-video-mod-control]').hidden=source!=='mod';q('[data-video-custom-control]').hidden=source!=='custom';return reload();}
  if(button.dataset.videoItem!==undefined)return await select(items[Number(button.dataset.videoItem)]);
  if(button.hasAttribute('data-video-prev')){page--;return reload();}if(button.hasAttribute('data-video-next')){page++;return reload();}
  if(button.hasAttribute('data-video-folder-read'))return await setFolder(q('[data-video-folder]').value);
  if(button.hasAttribute('data-video-browse')){const bridge=window.STUDIO_CHOOSE_ASSET_FOLDER||window.pywebview?.api?.choose_asset_folder||window.pywebview?.api?.choose_folder;if(!bridge){say('请粘贴视频文件夹的完整路径，再点击“读取文件夹”。');q('[data-video-folder]').focus();return;}const path=await bridge('video');if(path&&!closed)return await setFolder(path);return;}
  if(button.hasAttribute('data-video-apply')&&record){busy=true;controls();say('正在保存视频设置…');try{const current=context(),result=await api('/api/video-settings',{projectId,revision:current.revision,id:Number(record.id),name:record.name,volume:record.volume,loop:record.loop,skippable:record.skippable,roleOnTop:record.roleOnTop,scale:record.scale});await committed(result);busy=false;end({id:result.id,row:result.row});}finally{busy=false;controls();}}
 }catch(error){say(error.message,true);}};
 d.oncancel=e=>{e.preventDefault();end(null);};d.showModal();
 void Promise.allSettled([api('/api/video-folder'),reload()]).then(results=>{if(!closed){if(results[0].status==='fulfilled'){folder=results[0].value;q('[data-video-folder]').value=folder.path||'';}else say(results[0].reason.message,true);controls();}});return done;
}
window.StudentAgeVideoLibrary={open};})();
