/* Item and shop warehouses. Native ItemCfg and BookCfg remain separate tables. */
(()=>{'use strict';
const UI=StudentAgeCharacterUI,esc=UI.esc,copy=v=>structuredClone(v),names=['ItemCfg','BookCfg','ShopCfg'];
const labels={id:'编号',name:'名称',icon:'图片',type:'类型',itemTag:'物品标签',effect:'获得／阅读效果',usingEffect:'使用效果',value:'赠送价值（−1 不可赠送）',sell:'出售价格（−1 不可出售）',desc:'物品说明',talkId:'使用后播放的对话',maxcount:'数量上限',btn:'使用按钮文字',clothType:'服装类别',needDLC:'所需扩展内容编号',precondition:'使用条件',rarity:'稀有度',sex:'适用性别',subType:'细分类别',capacity:'总页数',themes:'书籍主题',need:'阅读要求参数',talk:'阅读提示文字',price:'购买价格',group:'互斥商品组（0 不分组）',next:'售完后的替换商品',time:'开始出售年份',discountRound:'打折回合',probability:'上架概率（0～1）',buyTalk:'购买时的店员台词',disappearTime:'停止出售时间',limcount:'购买数量限制'};
function create(host,options){
 const api=options.api,shop=options.kind==='shop',S={data:{},tables:{},saved:'',revision:null,source:'local',filter:'',query:'',editor:null,migrations:[],invalid:{},tab:'basic',busy:false,undo:[],redo:[]};
 let snapshotCache=null;
 const $=s=>host.querySelector(s),readonly=()=>!!options.project.readOnly,all=t=>({...S.data[t]?.referenceRows,...S.tables[t]}),lookup=(t,id)=>S.tables[t]?.[id]??S.data[t]?.referenceRows?.[id],snapshot=()=>snapshotCache??(snapshotCache=JSON.stringify({tables:S.tables,migrations:S.migrations})),dirty=()=>snapshot()!==S.saved||Object.keys(S.invalid).length>0;
 const image=(path,thumbnail=false)=>'/api/assets?'+new URLSearchParams({projectId:options.project.id,path,token:options.token,...(thumbnail?{thumbnail:'1'}:{})});
 const notify=()=>{options.onState?.({busy:S.busy,dirty:dirty(),readOnly:readonly(),canUndo:!!S.undo.length,canRedo:!!S.redo.length,revision:S.revision});host.querySelectorAll('.warehouse-edit-body fieldset').forEach(n=>n.disabled=readonly()||!!S.editor?.reference||S.busy);host.querySelectorAll('[data-wh=save]').forEach(n=>n.disabled=readonly()||S.busy||!dirty());};
 function change(fn){if(readonly()||S.busy)throw Error('当前内容不可编辑。');S.undo.push(snapshot());if(S.undo.length>50)S.undo.shift();S.redo=[];fn();snapshotCache=null;notify();}
 const item=id=>lookup('ItemCfg',id)||lookup('BookCfg',id),current=()=>S.editor&&(S.editor.reference?S.data[S.editor.table].referenceRows:S.tables[S.editor.table])[S.editor.id];
 function defaults(t){return Object.fromEntries((S.data[t].schema.fields||[]).map(f=>[f.name,copy(f.default??(/^list|array/.test(f.type)?[]:f.type==='string'?'':0))]));}
 function typeName(t,r){return t==='BookCfg'?'书籍':S.refs.ItemTypeCfg?.[r.type]?.name||'其他';}
 function entries(){return (shop?['ShopCfg']:['ItemCfg','BookCfg']).flatMap(t=>Object.values(S.source==='reference'?S.data[t].referenceRows:S.tables[t]).map(r=>({table:t,row:r,visual:t==='ShopCfg'?item(r.id)||{name:'未找到商品 '+r.id}:r})));}
 function render(){host.innerHTML=`<section class="warehouse"><header><button data-wh="home" class="text-button">← 工坊主页</button><h2>${shop?'商店仓库':'物品仓库'}</h2>${!readonly()?'<button data-wh="new" class="primary">＋ '+(shop?'创建商品':'创建物品')+'</button>':''}</header><nav class="character-filters">${[['local','当前模组'],['reference','原版参考']].map(([v,l])=>`<button data-wh-source="${v}" class="${S.source===v?'active':''}">${l}</button>`).join('')}</nav><div class="warehouse-search"><input data-wh-search placeholder="搜索物品名称、编号或说明" value="${esc(S.query)}"><select data-wh-filter><option value="">全部类型</option>${Object.entries(S.refs.ItemTypeCfg||{}).filter(([id])=>+id>0&&+id<100).map(([id,r])=>`<option value="${id}" ${S.filter===id?'selected':''}>${esc(r.name)}</option>`).join('')}</select></div><div class="warehouse-grid"></div><div class="warehouse-editor-host"></div></section>`;grid();if(S.editor)form();notify();}
 function grid(){if(S.editor)return;const rows=entries().filter(v=>(!S.filter||(v.table==='BookCfg'||shop&&lookup('BookCfg',v.row.id)?3:Number(v.visual.type))===Number(S.filter))&&StudentAgeSearch.matches(S.query,v.row.id,v.visual.name,v.visual.desc));$('.warehouse-grid').innerHTML=rows.map(v=>`<button class="warehouse-card" data-wh-card="${v.table}:${v.row.id}">${v.visual.icon?`<img src="${esc(image(v.visual.icon,true))}" alt="${esc(v.visual.name)}" loading="lazy">`:'<span class="warehouse-no-image">暂无图片</span>'}<strong>${esc(v.visual.name||'未命名物品')}</strong><small>${shop?'¥ '+esc(v.row.price??0):esc(typeName(v.table,v.row))}</small></button>`).join('')||'<p class="helper">没有符合筛选条件的物品。</p>';}
 function scalar(f,r){const v=r[f.name],label=labels[f.name]||f.label||f.name;
 if(f.name==='id')return `<label>${label}<div class="warehouse-id"><input data-wh-field="id" type="number" step="1" value="${r.id}" ${S.editor.fresh&&!shop?'':'readonly'}>${!S.editor.fresh&&!S.editor.reference&&!shop?`<button data-record-table="${S.editor.table}" data-record-id="${r.id}">修改编号</button>`:''}${shop?'<button data-wh="product">选择物品</button>':''}</div></label>`;
 if(f.name==='type'&&shop)return `<label>商品类型<input readonly value="${esc(all('BookCfg')[r.id]?'书籍':S.refs.ItemTypeCfg?.[item(r.id)?.type]?.name||'其他')}"></label>`;
 if(f.name==='type')return `<label>类型<select data-wh-type>${Object.values(S.refs.ItemTypeCfg||{}).filter(v=>Number(v.id)>0).map(v=>`<option value="${v.id}" ${(S.editor.table==='BookCfg'?3:r.type)===Number(v.id)?'selected':''}>${esc(v.name)}${[100,101].includes(+v.id)?'（游戏分组）':''}</option>`).join('')}</select></label>`;
 if(f.name==='sex')return `<label>${label}<select data-wh-field="sex" data-value-kind="number">${[[0,'不限'],[1,'男'],[2,'女']].map(([n,l])=>`<option value="${n}" ${Number(v)===n?'selected':''}>${l}</option>`).join('')}</select></label>`;
 if(f.range?.table&&f.name!=='type'&&!Array.isArray(v)&&!/^list|array/.test(f.type))return `<label>${esc(label)}<button data-wh-reference="${f.name}" data-wh-table="${f.range.table}">${esc(S.refs[f.range.table]?.[v]?.name||S.refs[f.range.table]?.[v]?.title||(v?'编号 '+v:'未设置'))} ▾</button></label>`;
 if(typeof v==='boolean')return `<label>${esc(label)}<select data-wh-field="${f.name}" data-value-kind="boolean"><option value="false" ${!v?'selected':''}>关闭</option><option value="true" ${v?'selected':''}>开启</option></select></label>`;
 if(v&&typeof v==='object'&&!Array.isArray(v))return `<label>${esc(label)}<textarea data-wh-object="${f.name}">${esc(JSON.stringify(v))}</textarea></label>`;
 if(Array.isArray(v)||/^list|array/.test(f.type))return `<label>${esc(label)}<textarea data-wh-array="${f.name}" rows="2">${esc(Array.isArray(v)&&v.some(Array.isArray)?v.map(a=>a.join(',')).join('\n'):(v||[]).join(','))}</textarea><small>参数以逗号分隔${v?.some?.(Array.isArray)?'，每行一组':''}</small></label>`;
 return `<label>${esc(label)}${/desc|buyTalk|^talk$/.test(f.name)?`<textarea rows="3" data-wh-field="${f.name}">${esc(v??'')}</textarea>`:`<input data-wh-field="${f.name}" data-value-kind="${/^(int|float|double|long)/.test(f.type)?'number':'string'}" ${/^(int|float|double|long)/.test(f.type)?'type="number" step="any"':''} value="${esc(v??'')}">`}</label>`;
 }
 // ItemTagCfg also stores each character's gift replies as person×100+tag rows; only ids below 100 are item tags.
 const isItemTag=id=>Number(id)>=0&&Number(id)<100;
 function tagName(id){const t=S.refs.ItemTagCfg?.[id];if(!t)return '编号 '+id;return isItemTag(id)?t.name:t.name+' · '+id;}
 function tags(r){return `<div class="warehouse-tags"><label>物品标签</label><div class="warehouse-selected-tags">${(r.itemTag||[]).map(id=>`<button data-wh-tag="${id}" class="active">${esc(tagName(id))} ×</button>`).join('')||'<span>点击下方标签添加</span>'}<input data-wh-tag-id placeholder="也可输入编号，回车添加" inputmode="numeric"></div><input data-wh-tag-search placeholder="搜索标签"><div class="warehouse-tag-options">${Object.values(S.refs.ItemTagCfg||{}).filter(t=>isItemTag(t.id)||r.itemTag?.includes(Number(t.id))).map(t=>`<button data-wh-tag="${t.id}" class="${r.itemTag?.includes(Number(t.id))?'active':''}">${esc(tagName(t.id))}</button>`).join('')}</div></div>`;}
 function form(){const r=current(),ed=S.editor;if(!r){S.editor=null;$('.warehouse-editor-host').innerHTML='';return;}const fields=S.data[ed.table].schema.fields||[],known=new Set(fields.map(f=>f.name)),extra=Object.keys(r).filter(k=>!known.has(k)).map(name=>({name,label:labels[name]||'扩展参数 '+name,type:typeof r[name],advanced:true}));const basic=new Set(shop?['id','price','type','maxcount','probability','time','discountRound','disappearTime','limcount','buyTalk']:['id','name','type','value','sell','maxcount','desc','capacity']);const command=fields.filter(f=>['Effect','Condition'].includes(f.editorType)||['effect','usingEffect','precondition'].includes(f.name));let body='';
 const advanced=[...fields,...extra].filter(f=>!basic.has(f.name)&&!['icon','itemTag'].includes(f.name)&&!command.includes(f));
 if(shop||S.tab!=='tags')body=`<div class="warehouse-fields ${shop?'':'warehouse-item-fields'}">${fields.filter(f=>basic.has(f.name)).sort((a,b)=>[...basic].indexOf(a.name)-[...basic].indexOf(b.name)).map(f=>scalar(f,r)).join('')}${ed.table==='BookCfg'?`<label>书籍类别<select data-wh-field="type" data-value-kind="number">${[3001,3002].map(n=>`<option value="${n}" ${r.type===n?'selected':''}>${esc(S.refs.ItemTypeCfg[n]?.name||n)}</option>`).join('')}</select></label>`:''}</div><div class="warehouse-command-grid">${command.map(f=>`<section><h3>${esc(labels[f.name]||f.label)}</h3><div data-wh-command="${f.name}"></div></section>`).join('')}</div>${advanced.length?`<details class="warehouse-advanced"><summary>高级扩展选项</summary><div class="warehouse-fields">${advanced.map(f=>scalar(f,r)).join('')}</div></details>`:''}`;
 else body=tags(r);
 $('.warehouse-editor-host').innerHTML=`<div class="warehouse-editor" role="dialog" aria-modal="true" aria-label="${shop?'商品':'物品'}编辑"><header><h2>${ed.reference?'原版参考':ed.fresh?'创建'+(shop?'商品':'物品'):'编辑'+(shop?'商品':'物品')}</h2><button data-wh="close" aria-label="返回仓库">×</button></header><nav class="character-filters" ${shop?'hidden':''}>${[['basic','物品信息'],['tags','标签']].map(([v,l])=>`<button data-wh-tab="${v}" class="${S.tab===v?'active':''}">${l}</button>`).join('')}</nav><div class="warehouse-edit-body"><fieldset ${ed.reference||readonly()||S.busy?'disabled':''}>${body}</fieldset><aside><button class="warehouse-image" data-wh="${shop?'product':'image'}" ${ed.reference||readonly()?'disabled':''}>${(shop?item(r.id):r)?.icon?`<img src="${esc(image((shop?item(r.id):r).icon))}" alt="物品图片">`:'＋ 选择物品图片'}</button><strong>${esc((shop?item(r.id):r)?.name||'未命名物品')}</strong><small>${shop?'点击图片更换商品':'点击图片打开物品素材库'}</small></aside></div><p class="warehouse-error" role="status"></p><footer><button data-wh="close">返回仓库</button>${ed.reference&&!readonly()?'<button data-wh="copy" class="primary">在当前模组创建副本</button>':!readonly()?'<button data-wh="save" class="primary">保存</button>':''}</footer></div>`;
 if(shop||S.tab!=='tags')for(const f of command){const isCondition=f.editorType==='Condition'||f.name==='precondition',lib=isCondition?StudentAgeConditions:StudentAgeEffects;lib.mount($(`[data-wh-command="${f.name}"]`),{rows:copy(r[f.name]||[]),templates:options.info.commands?.[isCondition?'condition':'effect']||[],refs:S.refs,localIds:S.localIds,loadReferences:()=>loadCommandRefs(isCondition?'condition':'effect'),projectId:options.project.id,readOnly:ed.reference||readonly(),onChange:rows=>change(()=>r[f.name]=rows),onError:fail});}
 }
 function fail(e){const node=$('.warehouse-error');if(node)node.textContent=e.message||String(e);options.status(e.message||String(e),true);window.STUDIO_REPORT_ERROR?.(e);}
 async function loadCommandRefs(kind){const needed=[...new Set((options.info.commands?.[kind]||[]).flatMap(t=>(t.parameters||[]).map(p=>p.range?.table).filter(Boolean)))].filter(name=>!S.refs[name]);if(!needed.length)return;const revision=S.revision,results=await Promise.all(needed.map(name=>api('/api/table?'+new URLSearchParams({projectId:options.project.id,name}))));if(S.revision!==revision||results.some(v=>v.revision!==revision))throw Error('读取时模组发生变化，当前草稿已保留，请重新打开。');for(const v of results){S.refs[v.name]=v.rows;S.localIds[v.name]=v.localIds;}}
 async function load(){S.busy=true;notify();try{const needed=[...new Set([...names,'ItemTypeCfg','ItemTagCfg','ConditionTypeCfg','EffectTypeCfg'])];const results=await Promise.all(needed.map(name=>api('/api/table?'+new URLSearchParams({projectId:options.project.id,name}))));S.data=Object.fromEntries(results.map(v=>[v.name,v]));S.revision=results[0].revision;if(results.some(v=>v.revision!==S.revision))throw Error('读取时模组发生变化，请重新打开。');S.tables=Object.fromEntries(names.map(n=>[n,copy(S.data[n].localRows)]));S.migrations=[];S.invalid={};S.refs=Object.fromEntries(results.map(v=>[v.name,v.rows]));S.localIds=Object.fromEntries(results.map(v=>[v.name,v.localIds]));snapshotCache=null;S.saved=snapshot();S.undo=[];S.redo=[];render();}finally{S.busy=false;notify();}}
 async function save(){if(!dirty())return;if(S.busy)throw Error('正在保存。');const invalid=host.querySelector('[aria-invalid="true"],[data-effect-invalid]');if(invalid||Object.keys(S.invalid).length)throw Error('请先修正参数格式。');for(const n of ['ItemCfg','BookCfg'])for(const r of Object.values(S.tables[n]))if(JSON.stringify(r)!==JSON.stringify(S.data[n].localRows?.[r.id])&&(!String(r.name||'').trim()||!r.icon))throw Error('请填写物品名称并选择图片。');S.busy=true;notify();try{const result=await api('/api/warehouse-save',{projectId:options.project.id,revision:S.revision,tables:S.tables,migrations:S.migrations});S.revision=result.revision;S.tables=result.tables;S.migrations=[];for(const n of names)S.data[n].localRows=copy(S.tables[n]);snapshotCache=null;S.saved=snapshot();S.undo=[];S.redo=[];if(S.editor)S.editor.fresh=false;await options.onSaved?.();grid();if(S.editor)form();options.status('仓库已保存。');}finally{S.busy=false;notify();}}
 async function chooseProduct(){const rows=[...Object.values(all('ItemCfg')),...Object.values(all('BookCfg'))];return UI.choices('选择出售的物品',rows,{image:r=>r.icon?image(r.icon,true):'',selected:current()?.id});}
 async function add(basis=null,table=null){if(shop){const product=await chooseProduct();if(!product)return;if(S.tables.ShopCfg[product.id]){S.editor={table:'ShopCfg',id:String(product.id)};S.tab='basic';form();return;}change(()=>S.tables.ShopCfg[product.id]={...defaults('ShopCfg'),...(basis?copy(basis):{}),id:product.id,type:all('BookCfg')[product.id]?3:product.type,price:basis?.price??Math.max(0,Number(product.sell)||0),probability:basis?.probability??1});S.editor={table:'ShopCfg',id:String(product.id),fresh:true};}
 else{table=table|| (S.filter==='3'?'BookCfg':'ItemCfg');const id=STUDIO_IDS.allocate(table,all(table)),r=basis?copy(basis):{...defaults(table),name:'',type:table==='BookCfg'?3001:1,value:-1,sell:-1,itemTag:[]};r.id=id;if(basis)r.name+=' · 副本';change(()=>S.tables[table][id]=r);S.editor={table,id:String(id),fresh:true};}S.source='local';S.tab='basic';render();}
 async function remove(ed){if(ed.reference||readonly())return;const r=S.tables[ed.table][ed.id];if(!r)return;const yes=await confirmChoice('删除'+(shop?'商品':'物品')+'？','删除“'+(shop?item(r.id)?.name:r.name)+'”。保存前可以撤销。');if(!yes)return;change(()=>delete S.tables[ed.table][ed.id]);if(S.editor?.id===ed.id)S.editor=null;render();}
 async function confirmChoice(title,text){const result=await UI.choices(title,[{id:0,name:'取消'},{id:1,name:text+' 确认删除'}]);return result?.id===1;}
 async function icons(){await StudentAgeLibraries.images({project:options.project,api,token:options.token,kind:'item',title:'物品图片素材库',revision:()=>S.revision,onSelect:async image=>{if(image.path){change(()=>current().icon=image.path);form();return;}const result=await api('/api/image-import',{projectId:options.project.id,revision:S.revision,...image});S.revision=result.revision;change(()=>current().icon=result.url||result.assetPath);form();}});}

 host.onclick=e=>{const b=e.target.closest('button');if(!b)return;(async()=>{if(b.dataset.whCard){const [table,id]=b.dataset.whCard.split(':');S.editor={table,id,reference:S.source==='reference'};S.tab='basic';form();}if(b.dataset.whSource){S.source=b.dataset.whSource;S.editor=null;render();}if(b.dataset.whTab){if(Object.keys(S.invalid).length)throw Error('请先修正当前参数格式。');S.tab=b.dataset.whTab;form();}if(b.dataset.whTag){const id=Number(b.dataset.whTag);change(()=>{const r=current();r.itemTag=r.itemTag||[];r.itemTag=r.itemTag.includes(id)?r.itemTag.filter(v=>v!==id):[...r.itemTag,id];});form();}if(b.dataset.whReference){const table=b.dataset.whTable;if(!S.refs[table])S.refs[table]=(await api('/api/table?'+new URLSearchParams({projectId:options.project.id,name:table}))).rows;const r=await UI.choices(labels[b.dataset.whReference]||'选择',[{id:0,name:'不设置'},...Object.values(S.refs[table]).map(r=>({...r,name:r.name||r.title||r.content||'编号 '+r.id}))],{table,projectId:options.project.id});if(r){change(()=>current()[b.dataset.whReference]=r.id);form();}}
 const a=b.dataset.wh;if(a==='home')await options.home();if(a==='new')await add();if(a==='copy')await add(current(),S.editor.table);if(a==='save')await save();if(a==='close'){S.editor=null;render();}if(a==='image')await icons();if(a==='product'){const picked=await chooseProduct();if(picked){const before=S.editor.id;if(S.tables.ShopCfg[picked.id]&&String(picked.id)!==before)throw Error('该物品已经在商店中。');change(()=>{const r=current();delete S.tables.ShopCfg[before];r.id=picked.id;r.type=all('BookCfg')[picked.id]?3:picked.type;S.tables.ShopCfg[picked.id]=r;S.editor.id=String(picked.id);});form();grid();}}})().catch(fail);};
 host.oninput=e=>{const el=e.target;if(el.hasAttribute('data-wh-search')){S.query=el.value;grid();return;}if(el.hasAttribute('data-wh-filter')){S.filter=el.value;grid();return;}if(el.hasAttribute('data-wh-tag-search')){host.querySelectorAll('.warehouse-tag-options button').forEach(b=>b.hidden=!StudentAgeSearch.matches(el.value,b.textContent,b.dataset.whTag));return;}if(el.dataset.whField&&el.dataset.whField!=='id'){const r=current(),value=el.dataset.valueKind==='number'?Number(el.value):el.dataset.valueKind==='boolean'?el.value==='true':el.value;if(typeof value==='number'&&!Number.isFinite(value))return;change(()=>r[el.dataset.whField]=value);grid();}if(el.dataset.whObject){try{const v=JSON.parse(el.value);if(!v||typeof v!=='object'||Array.isArray(v))throw Error();delete S.invalid[el.dataset.whObject];change(()=>current()[el.dataset.whObject]=v);}catch{S.invalid[el.dataset.whObject]=true;notify();}}if(el.dataset.whArray){try{const r=current(),f=(S.data[S.editor.table].schema.fields||[]).find(f=>f.name===el.dataset.whArray),text=el.value.replace(/，/g,','),numeric=!f?.type?.includes('string'),parse=line=>line.split(',').map(s=>s.trim()).filter(Boolean).map(s=>numeric?Number(s):s),v=/list<list</.test(f?.type)||r[el.dataset.whArray]?.some(Array.isArray)?text.split('\n').filter(s=>s.trim()).map(parse):parse(text);if(v.flat().some(x=>typeof x==='number'&&!Number.isFinite(x)))throw Error();el.removeAttribute('aria-invalid');delete S.invalid[S.editor.table+':'+S.editor.id+':'+el.dataset.whArray];change(()=>r[el.dataset.whArray]=v);}catch{el.setAttribute('aria-invalid','true');S.invalid[S.editor.table+':'+S.editor.id+':'+el.dataset.whArray]=true;notify();}}};
 host.onchange=e=>{const el=e.target;(async()=>{if(el.dataset.whField==='id'){const n=Number(el.value),ed=S.editor;if(!Number.isInteger(n)||n<=0||S.tables[ed.table][n]&&String(n)!==ed.id){el.value=ed.id;throw Error('编号无效或已被当前模组使用。');}change(()=>{const r=current();for(const m of S.migrations)if(m.toTable===ed.table&&String(m.newId)===ed.id)m.newId=n;delete S.tables[ed.table][ed.id];r.id=n;S.tables[ed.table][n]=r;ed.id=String(n);});grid();}if(el.hasAttribute('data-wh-type')){const ed=S.editor,r=current(),value=Number(el.value),book=[3,3001,3002].includes(value);if(!shop&&book!==(ed.table==='BookCfg')){const table=book?'BookCfg':'ItemCfg',id=STUDIO_IDS.allocate(table,all(table));change(()=>{const previous=S.migrations.find(m=>m.toTable===ed.table&&String(m.newId)===ed.id);if(previous){previous.toTable=table;previous.newId=id;}else if(S.data[ed.table].localRows?.[ed.id])S.migrations.push({fromTable:ed.table,oldId:Number(ed.id),toTable:table,newId:id});delete S.tables[ed.table][ed.id];S.tables[table][id]={...defaults(table),...copy(r),id,type:book?(value===3002?3002:3001):value};ed.table=table;ed.id=String(id);ed.fresh=true;});options.status('已按所选物品类型分配对应编号；保存时会同步原编号的引用。');}else change(()=>r.type=book&&!shop?(value===3002?3002:3001):value);form();grid();}})().catch(fail);};
 host.onkeydown=e=>{if(e.target.hasAttribute('data-wh-tag-id')&&e.key==='Enter'){e.preventDefault();const ids=e.target.value.replace(/，/g,',').split(',').map(s=>Number(s.trim()));if(ids.some(n=>!Number.isInteger(n)||n<0))return fail(Error('标签编号应为非负整数。'));change(()=>current().itemTag=[...new Set([...(current().itemTag||[]),...ids])]);form();}if(e.key==='Escape'&&S.editor){e.preventDefault();e.stopPropagation();S.editor=null;render();}};
 host.oncontextmenu=e=>{const card=e.target.closest('[data-wh-card]');if(!card||readonly())return;e.preventDefault();const [table,id]=card.dataset.whCard.split(':'),ed={table,id,reference:S.source==='reference'},r=ed.reference?S.data[table].referenceRows[id]:S.tables[table][id];UI.choices(r.name||item(id)?.name||'物品',ed.reference?[{id:'copy',name:'在当前模组仓库创建副本'}]:[{id:'copy',name:'创建副本'},{id:'delete',name:'删除'}]).then(async choice=>{if(choice?.id==='copy')await add(r,table);if(choice?.id==='delete')await remove(ed);}).catch(fail);};
 const premise=e=>{if(e.detail.projectId!==options.project.id)return;window.STUDIO_STRIP_PREMISES?.(S.tables,new Set(e.detail.pairs));snapshotCache=null;window.STUDIO_STRIP_PREMISES?.(S.refs,new Set(e.detail.pairs));const strip=text=>{const d=JSON.parse(text);window.STUDIO_STRIP_PREMISES?.(d,new Set(e.detail.pairs));return JSON.stringify(d);};S.saved=strip(S.saved);S.undo=S.undo.map(strip);S.redo=S.redo.map(strip);S.revision=e.detail.revision;render();};window.addEventListener('studio-premises-removed',premise);const onPremiseCreated=e=>{if(options.project.id===e.detail.projectId&&S.revision===e.detail.previousRevision){S.revision=e.detail.revision;notify();}};window.addEventListener('studio-premise-created',onPremiseCreated);
 function restore(s){const data=JSON.parse(s);S.tables=data.tables;S.migrations=data.migrations||[];S.invalid={};snapshotCache=null;render();notify();}
 return {load,save,dirty,snapshot,restore,discard(){restore(S.saved);S.undo=[];S.redo=[];notify();},undo(){if(S.undo.length){S.redo.push(snapshot());restore(S.undo.pop());}},redo(){if(S.redo.length){S.undo.push(snapshot());restore(S.redo.pop());}},focusSearch(){ $('[data-wh-search]')?.focus();},destroy(){window.removeEventListener('studio-premise-created',onPremiseCreated);window.removeEventListener('studio-premises-removed',premise);host.replaceChildren();},navigation:{capture:()=>({kind:shop?'shop':'items',source:S.source,filter:S.filter,query:S.query,editor:S.editor,tab:S.tab}),restore(v){Object.assign(S,{source:v.source||'local',filter:v.filter||'',query:v.query||'',editor:v.editor||null,tab:v.tab||'basic'});render();}}};
}
async function pick(projectId,selected=0,settings={}){
 const d=document.createElement('dialog');d.className='character-picker warehouse-picker';document.body.append(d);
 let source='original',sourceId='',query='',kind='',category='',rows=[],sequence=0,resolve;const selectedRows=new Map();
 const promise=new Promise(r=>resolve=r),end=value=>{sequence++;d.close();d.remove();resolve(value);};
 d.innerHTML='<header><h2>物品仓库 · 选择礼物</h2><button data-gift-close aria-label="关闭">×</button></header><nav class="character-filters">'+[['original','原版'],['custom','自定义'],['mod','模组']].map(([v,l])=>`<button data-gift-source="${v}">${l}</button>`).join('')+'</nav><select data-gift-project hidden aria-label="来源模组"></select><div class="warehouse-search"><input data-gift-search placeholder="搜索物品名称、编号或说明"><select data-gift-kind><option value="">全部物品</option><option value="ItemCfg">物品</option><option value="BookCfg">书籍</option></select></div><div class="warehouse-grid"></div><p class="character-picker-error" role="status"></p>';
 d.querySelector('h2').textContent=settings.title||'物品仓库 · 选择礼物';
 if(settings.multiple){const footer=document.createElement('footer');footer.className='warehouse-multi-actions';footer.innerHTML='<span data-gift-count>已选 0 项</span><button data-gift-apply class="primary">添加所选物品</button>';d.append(footer);}
 const categories=document.createElement('select');categories.setAttribute('aria-label','物品二级分类');categories.dataset.giftCategory='';d.querySelector('.warehouse-search').append(categories);
 const $=s=>d.querySelector(s),notice=s=>$('[role=status]').textContent=s;
 function paint(){
  const types=settings.types||{1:{name:'消耗品'},2:{name:'珍视物品'},4:{name:'工具'},5:{name:'礼物'},6:{name:'服装'},7:{name:'发型'}};const choices=[...new Set(rows.filter(r=>!kind||r.table===kind).map(r=>r.table+':'+r.type))];if(!choices.includes(category))category='';categories.innerHTML='<option value="">全部分类</option>'+choices.map(c=>{const [t,id]=c.split(':');const name=t==='BookCfg'?({3001:'故事',3002:'知识'}[id]||'书籍分类 '+id):(types[id]?.name||'分类 '+id);return `<option value="${esc(c)}" ${category===c?'selected':''}>${esc(name)}</option>`;}).join('');
  d.querySelectorAll('[data-gift-source]').forEach(b=>b.classList.toggle('active',b.dataset.giftSource===source));$('[data-gift-project]').hidden=source!=='mod';
  $('.warehouse-grid').innerHTML=rows.filter(r=>(!kind||kind===r.table)&&(!category||category===r.table+':'+r.type)&&StudentAgeSearch.matches(query,r.id,r.name,r.desc)).map(r=>`<button class="warehouse-card ${settings.multiple?selectedRows.has(r.projectId+':'+r.table+':'+r.id)?'active':'':Number(r.id)===Number(selected)?'active':''}" data-gift-item="${r.table}:${r.id}">${r.icon?`<img loading="lazy" src="${esc('/api/assets?'+new URLSearchParams({projectId:r.projectId,path:r.icon,token:STUDIO_TOKEN,thumbnail:'1'}))}" alt="${esc(r.name)}">`:'<span class="warehouse-no-image">暂无图片</span>'}<strong>${esc('['+r.id+'] '+(r.name||'未命名物品'))}</strong><small>${r.table==='BookCfg'?'书籍':'物品'}${r.sourceName?' · '+esc(r.sourceName):''}</small></button>`).join('')||'<p class="helper">没有符合条件的物品。</p>';
  $('.warehouse-grid').querySelectorAll('img').forEach(img=>img.onerror=()=>{const note=document.createElement('span');note.className='warehouse-no-image';note.textContent='图片未缓存';img.replaceWith(note);});
 }
 async function load(){const request=++sequence,id=source==='mod'?sourceId:projectId;rows=[];paint();if(!id){notice('请选择来源模组。');return;}notice('正在读取物品…');try{
   const tables=await Promise.all(['ItemCfg','BookCfg'].map(name=>UI.api('table?'+new URLSearchParams({projectId:id,name}))));
   if(request!==sequence||!d.open)return;
   rows=tables.flatMap(t=>Object.values(source==='original'?t.referenceRows:t.localRows).map(row=>({...row,table:t.name,projectId:id,sourceName:source==='mod'?t.project.name:''})));paint();notice(settings.multiple?'可跨分类多选，完成后点击添加所选物品。':'点击物品即可选择。');
  }catch(e){if(request===sequence)notice(e.message);}}
 d.oncancel=e=>{e.preventDefault();end(null);};d.onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-gift-apply'))end([...selectedRows.values()]);else if(b.hasAttribute('data-gift-close'))end(null);else if(b.dataset.giftSource){source=b.dataset.giftSource;load();}else if(b.dataset.giftItem){const row=rows.find(r=>r.table+':'+r.id===b.dataset.giftItem);if(row){if(settings.multiple){const key=row.projectId+':'+row.table+':'+row.id;selectedRows.has(key)?selectedRows.delete(key):selectedRows.set(key,row);paint();$('[data-gift-count]').textContent='已选 '+selectedRows.size+' 项';}else end(row);}}};
 categories.onchange=e=>{category=e.target.value;paint();};
 $('[data-gift-search]').oninput=e=>{query=e.target.value;paint();};$('[data-gift-kind]').onchange=e=>{kind=e.target.value;paint();};$('[data-gift-project]').onchange=e=>{sourceId=e.target.value;load();};
 d.showModal();load();UI.api('projects').then(result=>{if(!d.open)return;const projects=(Array.isArray(result)?result:result.projects||[]).filter(p=>p.id!==projectId);$('[data-gift-project]').innerHTML='<option value="">选择来源模组</option>'+projects.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('');}).catch(e=>{if(d.open)notice(e.message);});return promise;
}
window.StudentAgeWarehouse={create,pick};
})();
