"""Generate standalone/noir-tones.css (夜幕 · 剧场) from the 月夜 tone tokens.

The shared glass stylesheets colour every screen through --glass-tone-N variables. This remaps the
moonlit palette instead of redrawing each component: navy surfaces become warm charcoal, the blue
accents become amber stage light, cold white text becomes ivory, and reds (errors) keep their hue.

    python3 tools/build_noir_tones.py > standalone/noir-tones.css
"""
import colorsys
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] / 'standalone'
SOURCE = (ROOT / 'glass-tones.css').read_text(encoding='utf-8')
block = SOURCE[SOURCE.index('html[data-theme="glass-moon"]'):]
block = block[:block.index('}')]
TONES = re.findall(r'--glass-tone-(\d+):rgba\(([\d.]+),([\d.]+),([\d.]+),([\d.]+)\)', block)

WARM = 28 / 360     # charcoal and greys lean toward warm brown
AMBER = 33 / 360    # accent: stage light


def remap(r, g, b):
    h, l, s = colorsys.rgb_to_hls(r / 255, g / 255, b / 255)
    chroma = (max(r, g, b) - min(r, g, b)) / 255
    if chroma > 0.08 and (h < 0.06 or h > 0.93):          # errors and their washes stay red
        return r, g, b
    if chroma > 0.08 and 0.2 < h < 0.47:                   # success greens stay, a touch softer
        return r, g, b
    if l > 0.9:                                            # text: warm ivory
        nh, nl, ns = 30 / 360, 0.93 + (l - 0.9) * 0.4, 0.42
    elif chroma > 0.25 and l > 0.6:                        # accents: amber light
        nh, nl, ns = AMBER, 0.71, 0.86
    elif l > 0.6:                                          # pale tints
        nh, nl, ns = AMBER, 0.78, 0.55
    elif l > 0.3:                                          # borders, raised controls
        nh, nl, ns = WARM, l * 0.60, 0.10
    else:                                                  # surfaces and shadows
        nh, nl, ns = WARM, l * 0.70, 0.12 if l > 0.04 else 0.2
    return tuple(round(x * 255) for x in colorsys.hls_to_rgb(nh, nl, ns))


out = []
for n, r, g, b, a in TONES:
    R, G, B = remap(float(r), float(g), float(b))
    out.append(f'--glass-tone-{n}:rgba({R},{G},{B},{float(a):.3f})')
print('/* 夜幕 · 剧场: warm charcoal, ivory text, amber stage light. Generated by tools/build_noir_tones.py from the 月夜 tones. */')
print('html[data-theme="glass-noir"]{color-scheme:dark;' + ';'.join(out) + ';}')
print(len(out), 'tones', file=sys.stderr)

# glass-palette.css writes most left/right border colours as fixed light blue-greys while top/bottom go
# through the tone variables. On this dark theme those fixed sides would glow; give each such rule the
# same tone as its top border (or a quiet hairline).
PALETTE = (ROOT / 'glass-palette.css').read_text(encoding='utf-8')
fixes = []
for selector, body in re.findall(r'([^{}]+)\{([^{}]*)\}', PALETTE):
    if selector.lstrip().startswith('@') or not re.search(r'border-(?:left|right)-color:\s*rgba?\(', body):
        continue
    top = re.search(r'border-top-color:\s*(var\([^;]*\))', body)
    colour = top.group(1) if top else 'rgba(255,230,205,.12)'
    sides = [side for side in ('left', 'right') if re.search(rf'border-{side}-color:\s*rgba?\(', body)]
    scoped = ','.join('html[data-theme="glass-noir"] ' + part.strip() for part in selector.split(',') if part.strip())
    fixes.append(scoped + '{' + ';'.join(f'border-{side}-color:{colour}' for side in sides) + '}')
print('/* Side borders that glass-palette.css fixes to light greys follow the tone of the top border here. */')
print('\n'.join(fixes))
print(len(fixes), 'side-border fixes', file=sys.stderr)
